In [3]:
import pandas as pd
import geopandas as gpd
import requests
import numpy as np
import orjson
from bs4 import BeautifulSoup

In [2]:
for lang in ['en','fi','sv']:

    url = f"https://pxdata.stat.fi/PxWeb/pxweb/{lang}/Kuntien_avainluvut/Kuntien_avainluvut__uusin/kuntien_avainluvut_viimeisin.px/"

    definitions = []

    soup = BeautifulSoup(requests.get(url).content)
    for h4 in soup.findAll('h4'):
        

        definitions.append({'key_figure':h4.text.split(',')[0],'definition':h4.next.next.text})

    pd.DataFrame(definitions).set_index('key_figure').to_csv(f'definitions_{lang}.csv', encoding = 'utf-8')

In [4]:
pd.read_csv('definitions_fi.csv').set_index('key_figure')#.loc['Taajama-aste']

                                                                                        definition
key_figure
Väkiluku                                         Väestöllä tarkoitetaan alueella vakinaisesti a...
Väkiluvun muutos edellisestä vuodesta            Väkiluvun muutos on väkiluvun muutos prosentte...
Alle 15-vuotiaita                                Alle 15-vuotiaaiden osuus koko väestöstä. Väes...
15-64-vuotiaita                                  15-64-vuotiaiden osuus koko väestöstä. Väestöl...
Yli 64-vuotiaita                                 Yli 64-vuotiaiden osuus koko väestöstä. Väestö...
Ruotsinkielisiä                                  Väestöllä tarkoitetaan alueella vakinaisesti a...
Ulkomaan kansalaisia                             Kansalaisuudella tarkoitetaan jonkin maan kans...
Taajama-aste                                     Taajama-aste tarkoittaa taajamissa asuvien osu...
Syntyneiden enemmyys                             Syntyneiden enemmyys eli luonnollinen väestönl...
Kuntien välistä muuttovoittoa/-tappiota          Kuntien välisellä muuttovoitolla/- tappiolla t...
Perheitä                                         Perheen muodostavat yhdessä asuvat avio- tai a...
Asuntokuntia                                     Asuntokunnan muodostavat kaikki samassa asuinh...
Rivi- ja pientaloissa asuvia asuntokuntia        Rivi- ja pientaloissa asuvien asuntokuntien os...
Vuokra-asunnoissa asuvia asuntokuntia            Vuokra-asunnoissa asuvien asuntokuntien osuus ...
Vähintään toisen asteen tutkinnon suorittaneita  Vähintään toisen asteen tutkinnon suorittaneil...
Korkea-asteen tutkinnon suorittaneita            Korkea-asteen tutkinnon suorittaneisiin luetaa...
Taloudellinen huoltosuhde                        Väestörakennetta mitataan ns. taloudellisella ...
Työpaikkaomavaraisuus                            Työpaikkaomavaraisuus ilmaisee alueella työssä...
Alueella asuva työllinen työvoima                Alueella asuvalla työllisellä työvoimalla tark...
20-64-vuotiaiden työllisyysaste                  Työllisyysaste on työllisten osuus samanikäise...
Asuinkunnassaan työssäkäyviä                     Asuinkunnassaan työssäkäyvien osuus työllisest...
Työttömien osuus työvoimasta                     Työvoimaan kuuluvat 15-74-vuotiaat henkilöt, j...
Eläkeläisten osuus väestöstä                     Eläkeläisiksi katsotaan kaikki ne, jotka Kansa...
Alueella olevia työpaikkoja                      Tietyllä alueella työskentelevien henkilöiden ...
Alkutuotannon työpaikkojen osuus                 Alkutuotanto käsittää TOL 2008 -toimialaluokit...
Jalostuksen työpaikkojen osuus                   Jalostus käsittää TOL 2008 -toimialaluokitukse...
Palvelujen työpaikkojen osuus                    Palvelut käsittää TOL 2008 -toimialaluokitukse...

In [7]:
from gtts import gTTS
from tqdm import tqdm
import re
import time
for lang in ['sv','en','fi']:
    
    definitions = pd.read_csv(f'definitions_{lang}.csv').set_index('key_figure')
    
    for kw in tqdm(definitions.index):
        
        try:
            my_speech = gTTS(text=definitions.loc[kw].definition, lang=lang, slow=False)
        except:
            time.sleep(5)
            my_speech = gTTS(text=definitions.loc[kw].definition, lang=lang, slow=False)
        kw = re.sub(r'\W+','',kw)

        filename = f"recordings/{lang}/{kw}.mp3"
        my_speech.save(filename)

100%|██████████| 27/27 [00:37<00:00,  1.41s/it]
100%|██████████| 27/27 [00:50<00:00,  1.89s/it]
100%|██████████| 27/27 [00:46<00:00,  1.72s/it]

In [29]:
word = re.sub(r'\W+','','Sosiaali- ja terveystoiminta yhteensä')
#f"{re.sub(r'\W+','',word)}.mp3"
word
f"{word}.mp3"

'Sosiaalijaterveystoimintayhteensä.mp3'

In [20]:
'Opetus- ja kulttuuritoiminta yhteensä'.replace(r'\W+','')

'Opetus- ja kulttuuritoiminta yhteensä'

In [12]:

import re

for i in definitions.index:
    print(re.sub(r'\W+','',i))

Taajamaaste
Väkiluku
Väkiluvunmuutosedellisestävuodesta
Alle15vuotiaidenosuusväestöstä
1564vuotiaidenosuusväestöstä
Yli64vuotiaidenosuusväestöstä
Ruotsinkielistenosuusväestöstä
Ulkomaankansalaistenosuusväestöstä
Syntyneidenenemmyys
Kuntienvälinenmuuttovoittotappio
Perheidenlukumäärä
Asuntokuntienlukumäärä
Rivijapientaloissaasuvienasuntokuntienosuus
Vuokraasunnoissaasuvienasuntokuntienosuus
Vähintääntoisenasteentutkinnonsuorittaneidenosuus15vuottatäyttäneistä
Korkeaasteentutkinnonsuorittaneidenosuus15vuottatäyttäneistä
Alueellaasuvantyöllisentyövoimanmäärä
Työllisyysaste
Asuinkunnassaantyössäkäyvienosuus
Työttömienosuustyövoimasta
Eläkeläistenosuusväestöstä
Taloudellinenhuoltosuhde
Alueellaolevientyöpaikkojenlukumäärä
Alkutuotannontyöpaikkojenosuus
Jalostuksentyöpaikkojenosuus
Palvelujentyöpaikkojenosuus
Työpaikkaomavaraisuus
Vuosikate
Lainakanta
Konserninlainakanta
Opetusjakulttuuritoimintayhteensä
Sosiaalijaterveystoimintayhteensä

In [8]:
kunnat = gpd.read_file('https://geo.stat.fi/geoserver/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=tilastointialueet:kunta1000k_2021&outputFormat=json')
kunnat

,id,kunta,vuosi,nimi,namn,name,geometry
0,kunta1000k_2021.1,005,2021,Alajärvi,Alajärvi,Alajärvi,"POLYGON ((366787.924 7001300.583, 364150.540 7..."
1,kunta1000k_2021.2,009,2021,Alavieska,Alavieska,Alavieska,"POLYGON ((382543.364 7120022.976, 380556.177 7..."
2,kunta1000k_2021.3,010,2021,Alavus,Alavo,Alavus,"POLYGON ((343298.204 6961570.195, 340572.015 6..."
3,kunta1000k_2021.4,016,2021,Asikkala,Asikkala,Asikkala,"POLYGON ((436139.680 6798279.085, 432732.949 6..."
4,kunta1000k_2021.5,018,2021,Askola,Askola,Askola,"POLYGON ((426631.036 6720528.076, 425751.505 6..."
...,...,...,...,...,...,...,...
304,kunta1000k_2021.305,977,2021,Ylivieska,Ylivieska,Ylivieska,"POLYGON ((398010.991 7110887.267, 392464.690 7..."
305,kunta1000k_2021.306,980,2021,Ylöjärvi,Ylöjärvi,Ylöjärvi,"POLYGON ((313738.511 6896936.100, 311165.511 6..."
306,kunta1000k_2021.307,981,2021,Ypäjä,Ypäjä,Ypäjä,"POLYGON ((297451.456 6756204.328, 291432.640 6..."
307,kunta1000k_2021.308,989,2021,Ähtäri,Etseri,Ähtäri,"POLYGON ((348733.187 6959704.551, 347302.684 6..."
308,kunta1000k_2021.309,992,2021,Äänekoski,Äänekoski,Äänekoski,"POLYGON ((452626.858 6973610.366, 451491.412 6..."

In [9]:
kunnat.crs

<Derived Projected CRS: EPSG:3067>
Name: ETRS89 / TM35FIN(E,N)
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Finland - onshore and offshore.
- bounds: (19.08, 58.84, 31.59, 70.09)
Coordinate Operation:
- name: TM35FIN
- method: Transverse Mercator
Datum: European Terrestrial Reference System 1989 ensemble
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [10]:
kunnat.to_crs({'init': 'epsg:4326'})

C:\Users\tuomas.poukkula\Anaconda3\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)

,id,kunta,vuosi,nimi,namn,name,geometry
0,kunta1000k_2021.1,005,2021,Alajärvi,Alajärvi,Alajärvi,"POLYGON ((24.35901 63.11643, 24.30441 63.14112..."
1,kunta1000k_2021.2,009,2021,Alavieska,Alavieska,Alavieska,"POLYGON ((24.58205 64.18645, 24.54041 64.19458..."
2,kunta1000k_2021.3,010,2021,Alavus,Alavo,Alavus,"POLYGON ((23.93159 62.75093, 23.87746 62.75778..."
3,kunta1000k_2021.4,016,2021,Asikkala,Asikkala,Asikkala,"POLYGON ((25.80747 61.31340, 25.74179 61.36463..."
4,kunta1000k_2021.5,018,2021,Askola,Askola,Askola,"POLYGON ((25.65965 60.61388, 25.64397 60.60461..."
...,...,...,...,...,...,...,...
304,kunta1000k_2021.305,977,2021,Ylivieska,Ylivieska,Ylivieska,"POLYGON ((24.90637 64.10945, 24.79071 64.13178..."
305,kunta1000k_2021.306,980,2021,Ylöjärvi,Ylöjärvi,Ylöjärvi,"POLYGON ((23.42400 62.15811, 23.37374 62.16501..."
306,kunta1000k_2021.307,981,2021,Ypäjä,Ypäjä,Ypäjä,"POLYGON ((23.26666 60.88911, 23.15524 60.89243..."
307,kunta1000k_2021.308,989,2021,Ähtäri,Etseri,Ähtäri,"POLYGON ((24.03952 62.73648, 24.01216 62.73008..."
308,kunta1000k_2021.309,992,2021,Äänekoski,Äänekoski,Äänekoski,"POLYGON ((26.06824 62.88941, 26.04580 62.89273..."

In [13]:
kunnat = kunnat.to_crs({'init': 'epsg:4326'})

C:\Users\tuomas.poukkula\Anaconda3\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)

In [17]:
kunnat.drop(['id','kunta','vuosi'],axis=1).set_index('nimi').to_file('municipalities_multilang.json')

In [19]:
maakunnat = gpd.read_file('https://geo.stat.fi/geoserver/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=maakunta1000k_2021&outputFormat=json')
maakunnat = maakunnat.to_crs({'init': 'epsg:4326'})
maakunnat.drop(['id','maakunta','vuosi'],axis=1).set_index('nimi').to_file('regions_multilang.json')

C:\Users\tuomas.poukkula\Anaconda3\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)

In [20]:
seutukunnat = gpd.read_file('https://geo.stat.fi/geoserver/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=tilastointialueet:seutukunta1000k_2021&outputFormat=json')
seutukunnat = seutukunnat.to_crs({'init': 'epsg:4326'})
seutukunnat.drop(['id','seutukunta','vuosi'],axis=1).set_index('nimi').to_file('subregions_multilang.json')

C:\Users\tuomas.poukkula\Anaconda3\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)

In [21]:
maakunnat

,id,maakunta,vuosi,nimi,namn,name,geometry
0,maakunta1000k_2021.1,01,2021,Uusimaa,Nyland,Uusimaa,"MULTIPOLYGON (((25.98236 60.46516, 25.98447 60..."
1,maakunta1000k_2021.2,02,2021,Varsinais-Suomi,Egentliga Finland,Southwest Finland,"MULTIPOLYGON (((21.29251 61.00478, 21.29386 61..."
2,maakunta1000k_2021.3,04,2021,Satakunta,Satakunta,Satakunta,"MULTIPOLYGON (((21.35891 61.93050, 21.36042 61..."
3,maakunta1000k_2021.4,05,2021,Kanta-Häme,Egentliga Tavastland,Kanta-Häme,"POLYGON ((24.42368 60.55249, 24.54895 60.55984..."
4,maakunta1000k_2021.5,06,2021,Pirkanmaa,Birkaland,Pirkanmaa,"POLYGON ((23.83937 60.93971, 23.86491 60.95361..."
5,maakunta1000k_2021.6,07,2021,Päijät-Häme,Päijänne-Tavastland,Päijät-Häme,"POLYGON ((25.61087 60.67148, 25.61235 60.67863..."
6,maakunta1000k_2021.7,08,2021,Kymenlaakso,Kymmenedalen,Kymenlaakso,"MULTIPOLYGON (((27.75829 60.56764, 27.76189 60..."
7,maakunta1000k_2021.8,09,2021,Etelä-Karjala,Södra Karelen,South Karelia,"POLYGON ((27.95147 60.66716, 27.98402 60.66865..."
8,maakunta1000k_2021.9,10,2021,Etelä-Savo,Södra Savolax,South Savo,"POLYGON ((27.03117 61.15206, 27.07199 61.15412..."
9,maakunta1000k_2021.10,11,2021,Pohjois-Savo,Norra Savolax,North Savo,"POLYGON ((27.79361 61.98776, 27.85134 62.01434..."
10,maakunta1000k_2021.11,12,2021,Pohjois-Karjala,Norra Karelen,North Karelia,"POLYGON ((29.55927 61.72207, 29.96215 61.82177..."
11,maakunta1000k_2021.12,13,2021,Keski-Suomi,Mellersta Finland,Central Finland,"POLYGON ((26.31504 61.60845, 26.32512 61.60851..."
12,maakunta1000k_2021.13,14,2021,Etelä-Pohjanmaa,Södra Österbotten,South Ostrobothnia,"POLYGON ((21.97469 61.97976, 22.10840 62.03185..."
13,maakunta1000k_2021.14,15,2021,Pohjanmaa,Österbotten,Ostrobothnia,"MULTIPOLYGON (((22.77349 63.91437, 22.77525 63..."
14,maakunta1000k_2021.15,16,2021,Keski-Pohjanmaa,Mellersta Österbotten,Central Ostrobothnia,"MULTIPOLYGON (((23.40880 64.08828, 23.41239 64..."
15,maakunta1000k_2021.16,17,2021,Pohjois-Pohjanmaa,Norra Österbotten,North Ostrobothnia,"MULTIPOLYGON (((25.32947 65.46168, 25.33095 65..."
16,maakunta1000k_2021.17,18,2021,Kainuu,Kajanaland,Kainuu,"POLYGON ((28.27392 63.66881, 28.35959 63.75475..."
17,maakunta1000k_2021.18,19,2021,Lappi,Lappland,Lapland,"MULTIPOLYGON (((24.28393 65.77837, 24.28637 65..."
18,maakunta1000k_2021.19,21,2021,Ahvenanmaa,Åland,Åland,"MULTIPOLYGON (((20.98174 60.64060, 20.98515 60..."

In [52]:
import requests

json = requests.get("https://pxdata.stat.fi:443/PxWeb/api/v1/en/Kuntien_avainluvut/2021/kuntien_avainluvut_2021_viimeisin.px").json()
codes_en = pd.DataFrame([{'code':v,'name':vt} for v, vt in zip(json['variables'][0]['values'],json['variables'][0]['valueTexts'])])
codes_en

      code                                name
0      SSS                       WHOLE COUNTRY
1      020                                Akaa
2      005                            Alajärvi
3      009                           Alavieska
4      010                              Alavus
..     ...                                 ...
393  SK196     Tunturi-Lappi sub-regional unit
394  SK197     Pohjois-Lappi sub-regional unit
395  SK211   Mariehamns stad sub-regional unit
396  SK212  Ålands landsbygd sub-regional unit
397  SK213   Ålands skärgård sub-regional unit

[398 rows x 2 columns]

In [53]:
import requests

json = requests.get("https://pxdata.stat.fi:443/PxWeb/api/v1/sv/Kuntien_avainluvut/2021/kuntien_avainluvut_2021_viimeisin.px").json()
codes_sv = pd.DataFrame([{'code':v,'namn':vt} for v, vt in zip(json['variables'][0]['values'],json['variables'][0]['valueTexts'])])
codes_sv

      code                        namn
0      SSS                 HELA LANDET
1      020                       Ackas
2      005                    Alajärvi
3      009                   Alavieska
4      010                       Alavo
..     ...                         ...
393  SK196    Tunturi-Lappi ekon. reg.
394  SK197  Norra Lapplands ekon. reg.
395  SK211             Mariehamns stad
396  SK212            Ålands landsbygd
397  SK213             Ålands skärgård

[398 rows x 2 columns]

In [54]:
json = requests.get("https://pxdata.stat.fi:443/PxWeb/api/v1/fi/Kuntien_avainluvut/2021/kuntien_avainluvut_2021_viimeisin.px").json()
codes_fi = pd.DataFrame([{'code':v,'nimi':vt} for v, vt in zip(json['variables'][0]['values'],json['variables'][0]['valueTexts'])])
codes_fi

      code                      nimi
0      SSS                  KOKO MAA
1      020                      Akaa
2      005                  Alajärvi
3      009                 Alavieska
4      010                    Alavus
..     ...                       ...
393  SK196  Tunturi-Lapin seutukunta
394  SK197  Pohjois-Lapin seutukunta
395  SK211           Mariehamns stad
396  SK212          Ålands landsbygd
397  SK213           Ålands skärgård

[398 rows x 2 columns]

In [56]:
codes = pd.merge(left=pd.merge(left=codes_fi,right=codes_sv,on='code',how='inner'),right=codes_en, on = 'code', how='inner')
codes

,code,nimi,namn,name
0,SSS,KOKO MAA,HELA LANDET,WHOLE COUNTRY
1,020,Akaa,Ackas,Akaa
2,005,Alajärvi,Alajärvi,Alajärvi
3,009,Alavieska,Alavieska,Alavieska
4,010,Alavus,Alavo,Alavus
...,...,...,...,...
393,SK196,Tunturi-Lapin seutukunta,Tunturi-Lappi ekon. reg.,Tunturi-Lappi sub-regional unit
394,SK197,Pohjois-Lapin seutukunta,Norra Lapplands ekon. reg.,Pohjois-Lappi sub-regional unit
395,SK211,Mariehamns stad,Mariehamns stad,Mariehamns stad sub-regional unit
396,SK212,Ålands landsbygd,Ålands landsbygd,Ålands landsbygd sub-regional unit
397,SK213,Ålands skärgård,Ålands skärgård,Ålands skärgård sub-regional unit

In [58]:
mk = codes[codes.code.str.contains('MK')]
sk = codes[codes.code.str.contains('SK')]
mun = codes[~codes.code.str.contains('SK')]
mun = mun[~mun.code.str.contains('MK')]
mun

    code       nimi         namn           name
0    SSS   KOKO MAA  HELA LANDET  WHOLE COUNTRY
1    020       Akaa        Ackas           Akaa
2    005   Alajärvi     Alajärvi       Alajärvi
3    009  Alavieska    Alavieska      Alavieska
4    010     Alavus        Alavo         Alavus
..   ...        ...          ...            ...
305  977  Ylivieska    Ylivieska      Ylivieska
306  980   Ylöjärvi     Ylöjärvi       Ylöjärvi
307  981      Ypäjä        Ypäjä          Ypäjä
308  989     Ähtäri       Etseri         Ähtäri
309  992  Äänekoski    Äänekoski      Äänekoski

[310 rows x 4 columns]

In [63]:
mun = mun[mun.code!='SSS']
mun

    code       nimi       namn       name
1    020       Akaa      Ackas       Akaa
2    005   Alajärvi   Alajärvi   Alajärvi
3    009  Alavieska  Alavieska  Alavieska
4    010     Alavus      Alavo     Alavus
5    016   Asikkala   Asikkala   Asikkala
..   ...        ...        ...        ...
305  977  Ylivieska  Ylivieska  Ylivieska
306  980   Ylöjärvi   Ylöjärvi   Ylöjärvi
307  981      Ypäjä      Ypäjä      Ypäjä
308  989     Ähtäri     Etseri     Ähtäri
309  992  Äänekoski  Äänekoski  Äänekoski

[309 rows x 4 columns]

In [64]:
mun.code = mun.code.astype(int)

C:\Users\tuomas.poukkula\AppData\Local\Temp\ipykernel_28924\3523821949.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mun.code = mun.code.astype(int)

In [65]:
mun

     code       nimi       namn       name
1      20       Akaa      Ackas       Akaa
2       5   Alajärvi   Alajärvi   Alajärvi
3       9  Alavieska  Alavieska  Alavieska
4      10     Alavus      Alavo     Alavus
5      16   Asikkala   Asikkala   Asikkala
..    ...        ...        ...        ...
305   977  Ylivieska  Ylivieska  Ylivieska
306   980   Ylöjärvi   Ylöjärvi   Ylöjärvi
307   981      Ypäjä      Ypäjä      Ypäjä
308   989     Ähtäri     Etseri     Ähtäri
309   992  Äänekoski  Äänekoski  Äänekoski

[309 rows x 4 columns]

In [59]:
mk.code = mk.code.str.replace('MK','')
sk.code = sk.code.str.replace('SK','')

C:\Users\tuomas.poukkula\AppData\Local\Temp\ipykernel_28924\3672355604.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mk.code = mk.code.str.replace('MK','')
C:\Users\tuomas.poukkula\AppData\Local\Temp\ipykernel_28924\3672355604.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sk.code = sk.code.str.replace('SK','')

In [60]:
mk

,code,nimi,namn,name
310,01,Uudenmaan maakunta,Nylands landskap,Uusimaa
311,02,Varsinais-Suomen maakunta,Egentliga Finlands landskap,Southwest Finland
312,04,Satakunnan maakunta,Satakunta landskap,Satakunta
313,05,Kanta-Hämeen maakunta,Egentliga Tavastlands landskap,Kanta-Häme
314,06,Pirkanmaan maakunta,Birkalands landskap,Pirkanmaa
315,07,Päijät-Hämeen maakunta,Päijänne-Tavastlands landskap,Päijät-Häme
316,08,Kymenlaakson maakunta,Kymmenedalens landskap,Kymenlaakso
317,09,Etelä-Karjalan maakunta,Södra Karelens landskap,South Karelia
318,10,Etelä-Savon maakunta,Södra Savolax landskap,South Savo
319,11,Pohjois-Savon maakunta,Norra Savolax landskap,North Savo
320,12,Pohjois-Karjalan maakunta,Norra Karelens landskap,North Karelia
321,13,Keski-Suomen maakunta,Mellersta Finlands landskap,Central Finland
322,14,Etelä-Pohjanmaan maakunta,Södra Österbottens landskap,South Ostrobothnia
323,15,Pohjanmaan maakunta,Österbottens landskap,Ostrobothnia
324,16,Keski-Pohjanmaan maakunta,Mellersta Österbottens landskap,Central Ostrobothnia
325,17,Pohjois-Pohjanmaan maakunta,Norra Österbottens landskap,North Ostrobothnia
326,18,Kainuun maakunta,Kajanalands landskap,Kainuu
327,19,Lapin maakunta,Lapplands landskap,Lapland
328,21,Ahvenanmaa,Åland,Åland

In [61]:
sk

,code,nimi,namn,name
329,011,Helsingin seutukunta,Helsingfors ekon. reg.,Helsinki sub-regional unit
330,014,Raaseporin seutukunta,Raseborgs ekon. reg.,Raasepori sub-regional unit
331,015,Porvoon seutukunta,Borgå ekon. reg.,Porvoo sub-regional unit
332,016,Loviisan seutukunta,Lovisa ekon. reg.,Loviisa sub-regional unit
333,021,Åboland-Turunmaan seutukunta,Åboland-Turunmaa ekon. reg.,Åboland-Turunmaa sub-regional unit
...,...,...,...,...
393,196,Tunturi-Lapin seutukunta,Tunturi-Lappi ekon. reg.,Tunturi-Lappi sub-regional unit
394,197,Pohjois-Lapin seutukunta,Norra Lapplands ekon. reg.,Pohjois-Lappi sub-regional unit
395,211,Mariehamns stad,Mariehamns stad,Mariehamns stad sub-regional unit
396,212,Ålands landsbygd,Ålands landsbygd,Ålands landsbygd sub-regional unit
397,213,Ålands skärgård,Ålands skärgård,Ålands skärgård sub-regional unit

In [66]:
kunnat.kunta = kunnat.kunta.astype(int)
kunnat

,id,kunta,vuosi,nimi,namn,name,geometry
0,kunta1000k_2021.1,5,2021,Alajärvi,Alajärvi,Alajärvi,"POLYGON ((24.35901 63.11643, 24.30441 63.14112..."
1,kunta1000k_2021.2,9,2021,Alavieska,Alavieska,Alavieska,"POLYGON ((24.58205 64.18645, 24.54041 64.19458..."
2,kunta1000k_2021.3,10,2021,Alavus,Alavo,Alavus,"POLYGON ((23.93159 62.75093, 23.87746 62.75778..."
3,kunta1000k_2021.4,16,2021,Asikkala,Asikkala,Asikkala,"POLYGON ((25.80747 61.31340, 25.74179 61.36463..."
4,kunta1000k_2021.5,18,2021,Askola,Askola,Askola,"POLYGON ((25.65965 60.61388, 25.64397 60.60461..."
...,...,...,...,...,...,...,...
304,kunta1000k_2021.305,977,2021,Ylivieska,Ylivieska,Ylivieska,"POLYGON ((24.90637 64.10945, 24.79071 64.13178..."
305,kunta1000k_2021.306,980,2021,Ylöjärvi,Ylöjärvi,Ylöjärvi,"POLYGON ((23.42400 62.15811, 23.37374 62.16501..."
306,kunta1000k_2021.307,981,2021,Ypäjä,Ypäjä,Ypäjä,"POLYGON ((23.26666 60.88911, 23.15524 60.89243..."
307,kunta1000k_2021.308,989,2021,Ähtäri,Etseri,Ähtäri,"POLYGON ((24.03952 62.73648, 24.01216 62.73008..."
308,kunta1000k_2021.309,992,2021,Äänekoski,Äänekoski,Äänekoski,"POLYGON ((26.06824 62.88941, 26.04580 62.89273..."

In [69]:
pd.merge(left = kunnat[['kunta','geometry']], right = mun, left_on = 'kunta', right_on ='code', how = 'inner').drop(['code','kunta'],axis=1).set_index('nimi').to_file('municipalities_multilang.json')

In [73]:
mk.code = mk.code.astype(int)
maakunnat.maakunta = maakunnat.maakunta.astype(int)
pd.merge(left = maakunnat[['maakunta','geometry']], right = mk, left_on = 'maakunta', right_on ='code', how = 'inner').drop(['code','maakunta'],axis=1).set_index('nimi').to_file('regions_multilang.json')

C:\Users\tuomas.poukkula\AppData\Local\Temp\ipykernel_28924\1952223863.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mk.code = mk.code.astype(int)

In [76]:
sk.code = sk.code.astype(int)
seutukunnat.seutukunta = seutukunnat.seutukunta.astype(int)
pd.merge(left = seutukunnat[['seutukunta','geometry']], right = sk, left_on = 'seutukunta', right_on ='code', how = 'inner').drop(['code','seutukunta'],axis=1).set_index('nimi').to_file('subregions_multilang.json')

C:\Users\tuomas.poukkula\AppData\Local\Temp\ipykernel_28924\2036448108.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sk.code = sk.code.astype(int)

In [75]:
seutukunnat

,id,seutukunta,vuosi,nimi,namn,name,geometry
0,seutukunta1000k_2021.1,11,2021,Helsinki,Helsingfors,Helsinki,"MULTIPOLYGON (((25.37282 60.26162, 25.37291 60..."
1,seutukunta1000k_2021.2,14,2021,Raasepori,Raseborg,Raasepori,"MULTIPOLYGON (((23.52347 60.08027, 23.52438 60..."
2,seutukunta1000k_2021.3,15,2021,Porvoo,Borgå,Porvoo,"MULTIPOLYGON (((25.67803 60.37720, 25.67918 60..."
3,seutukunta1000k_2021.4,16,2021,Loviisa,Lovisa,Loviisa,"MULTIPOLYGON (((25.98236 60.46516, 25.98447 60..."
4,seutukunta1000k_2021.5,21,2021,Åboland-Turunmaa,Åboland-Turunmaa,Åboland-Turunmaa,"MULTIPOLYGON (((21.37728 60.46027, 21.37759 60..."
...,...,...,...,...,...,...,...
64,seutukunta1000k_2021.65,196,2021,Tunturi-Lappi,Tunturi-Lappi,Tunturi-Lappi,"POLYGON ((24.87021 66.93788, 24.85464 66.96306..."
65,seutukunta1000k_2021.66,197,2021,Pohjois-Lappi,Norra Lappland,Pohjois-Lappi,"POLYGON ((26.51797 66.94292, 26.61970 66.98900..."
66,seutukunta1000k_2021.67,211,2021,Mariehamns stad,Mariehamns stad,Mariehamns stad,"MULTIPOLYGON (((19.95771 60.06094, 19.95971 60..."
67,seutukunta1000k_2021.68,212,2021,Ålands landsbygd,Ålands landsbygd,Ålands landsbygd,"MULTIPOLYGON (((20.21086 60.53485, 20.21290 60..."
68,seutukunta1000k_2021.69,213,2021,Ålands skärgård,Ålands skärgård,Ålands skärgård,"MULTIPOLYGON (((20.98174 60.64060, 20.98515 60..."

In [1]:
import pandas as pd
import numpy as np

import requests

In [20]:
# Municipal query body
mun_payload = {
  "query": [
    {
      "code": "Alue 2021",
      "selection": {
        "filter": "item",
        "values": [
          "SSS",
          "020",
          "005",
          "009",
          "010",
          "016",
          "018",
          "019",
          "035",
          "043",
          "046",
          "047",
          "049",
          "050",
          "051",
          "052",
          "060",
          "061",
          "062",
          "065",
          "069",
          "071",
          "072",
          "074",
          "075",
          "076",
          "077",
          "078",
          "079",
          "081",
          "082",
          "086",
          "111",
          "090",
          "091",
          "097",
          "098",
          "102",
          "103",
          "105",
          "106",
          "108",
          "109",
          "139",
          "140",
          "142",
          "143",
          "145",
          "146",
          "153",
          "148",
          "149",
          "151",
          "152",
          "165",
          "167",
          "169",
          "170",
          "171",
          "172",
          "176",
          "177",
          "178",
          "179",
          "181",
          "182",
          "186",
          "202",
          "204",
          "205",
          "208",
          "211",
          "213",
          "214",
          "216",
          "217",
          "218",
          "224",
          "226",
          "230",
          "231",
          "232",
          "233",
          "235",
          "236",
          "239",
          "240",
          "320",
          "241",
          "322",
          "244",
          "245",
          "249",
          "250",
          "256",
          "257",
          "260",
          "261",
          "263",
          "265",
          "271",
          "272",
          "273",
          "275",
          "276",
          "280",
          "284",
          "285",
          "286",
          "287",
          "288",
          "290",
          "291",
          "295",
          "297",
          "300",
          "301",
          "304",
          "305",
          "312",
          "316",
          "317",
          "318",
          "398",
          "399",
          "400",
          "407",
          "402",
          "403",
          "405",
          "408",
          "410",
          "416",
          "417",
          "418",
          "420",
          "421",
          "422",
          "423",
          "425",
          "426",
          "444",
          "430",
          "433",
          "434",
          "435",
          "436",
          "438",
          "440",
          "441",
          "475",
          "478",
          "480",
          "481",
          "483",
          "484",
          "489",
          "491",
          "494",
          "495",
          "498",
          "499",
          "500",
          "503",
          "504",
          "505",
          "508",
          "507",
          "529",
          "531",
          "535",
          "536",
          "538",
          "541",
          "543",
          "545",
          "560",
          "561",
          "562",
          "563",
          "564",
          "309",
          "576",
          "577",
          "578",
          "445",
          "580",
          "581",
          "599",
          "583",
          "854",
          "584",
          "588",
          "592",
          "593",
          "595",
          "598",
          "601",
          "604",
          "607",
          "608",
          "609",
          "611",
          "638",
          "614",
          "615",
          "616",
          "619",
          "620",
          "623",
          "624",
          "625",
          "626",
          "630",
          "631",
          "635",
          "636",
          "678",
          "710",
          "680",
          "681",
          "683",
          "684",
          "686",
          "687",
          "689",
          "691",
          "694",
          "697",
          "698",
          "700",
          "702",
          "704",
          "707",
          "729",
          "732",
          "734",
          "736",
          "790",
          "738",
          "739",
          "740",
          "742",
          "743",
          "746",
          "747",
          "748",
          "791",
          "749",
          "751",
          "753",
          "755",
          "758",
          "759",
          "761",
          "762",
          "765",
          "766",
          "768",
          "771",
          "777",
          "778",
          "781",
          "783",
          "831",
          "832",
          "833",
          "834",
          "837",
          "844",
          "845",
          "846",
          "848",
          "849",
          "850",
          "851",
          "853",
          "857",
          "858",
          "859",
          "886",
          "887",
          "889",
          "890",
          "892",
          "893",
          "895",
          "785",
          "905",
          "908",
          "092",
          "915",
          "918",
          "921",
          "922",
          "924",
          "925",
          "927",
          "931",
          "934",
          "935",
          "936",
          "941",
          "946",
          "976",
          "977",
          "980",
          "981",
          "989",
          "992"
        ]
      }
    }
  ],
  "response": {
    "format": "json-stat2"
  }
}

# Region query body
reg_payload = {
  "query": [
    {
      "code": "Alue 2021",
      "selection": {
        "filter": "item",
        "values": [
          "SSS",
          "MK01",
          "MK02",
          "MK04",
          "MK05",
          "MK06",
          "MK07",
          "MK08",
          "MK09",
          "MK10",
          "MK11",
          "MK12",
          "MK13",
          "MK14",
          "MK15",
          "MK16",
          "MK17",
          "MK18",
          "MK19",
          "MK21"
        ]
      }
    }
  ],
  "response": {
    "format": "json-stat2"
  }
}
# Sub-region query body
sub_reg_payload = {
  "query": [
    {
      "code": "Alue 2021",
      "selection": {
        "filter": "item",
        "values": [
          "SSS",
          "SK011",
          "SK014",
          "SK015",
          "SK016",
          "SK021",
          "SK022",
          "SK023",
          "SK024",
          "SK025",
          "SK041",
          "SK043",
          "SK044",
          "SK051",
          "SK052",
          "SK053",
          "SK061",
          "SK063",
          "SK064",
          "SK068",
          "SK069",
          "SK071",
          "SK081",
          "SK082",
          "SK091",
          "SK093",
          "SK101",
          "SK103",
          "SK105",
          "SK111",
          "SK112",
          "SK113",
          "SK114",
          "SK115",
          "SK122",
          "SK124",
          "SK125",
          "SK131",
          "SK132",
          "SK133",
          "SK134",
          "SK135",
          "SK138",
          "SK141",
          "SK142",
          "SK144",
          "SK146",
          "SK152",
          "SK153",
          "SK154",
          "SK161",
          "SK162",
          "SK171",
          "SK173",
          "SK174",
          "SK175",
          "SK176",
          "SK177",
          "SK178",
          "SK181",
          "SK182",
          "SK191",
          "SK192",
          "SK193",
          "SK194",
          "SK196",
          "SK197",
          "SK211",
          "SK212",
          "SK213"
        ]
      }
    }
  ],
  "response": {
    "format": "json-stat2"
  }
}


queries = {'Maakunta':reg_payload,
           'Seutukunta':sub_reg_payload,
           'Kunta':mun_payload}

url = "https://pxdata.stat.fi:443/PxWeb/api/v1/fi/Kuntien_avainluvut/2021/kuntien_avainluvut_2021_viimeisin.px"
    
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36',
 'Content-Type': 'application/json'}
    
json = requests.post(url, json = queries['Maakunta'], headers = headers).json()



cities = list(json['dimension']['Alue 2021']['category']['label'].values())
    
dimensions = list(json['dimension']['Tiedot']['category']['label'].values())

values = json['value']

cities_df = pd.DataFrame(cities, columns = ['Maakunta'])
cities_df['index'] = 0
dimensions_df = pd.DataFrame(dimensions, columns = ['dimensions'])
dimensions_df['index'] = 0

data = pd.merge(left = cities_df, right = dimensions_df, on = 'index', how = 'outer').drop('index',axis = 1)
data['value'] = values
data = pd.pivot_table(data, values = 'value', index = ['Maakunta'], columns = 'dimensions')

In [21]:
json

{'class': 'dataset',
 'label': 'Kuntien avainluvut muuttujina Alue 2021 ja Tiedot',
 'source': 'Tilastokeskus',
 'updated': '2022-06-17T11.52.00Z',
 'id': ['Alue 2021', 'Tiedot'],
 'size': [20, 32],
 'dimension': {'Alue 2021': {'label': 'Alue 2021',
   'category': {'index': {'SSS': 0,
     'MK01': 1,
     'MK02': 2,
     'MK04': 3,
     'MK05': 4,
     'MK06': 5,
     'MK07': 6,
     'MK08': 7,
     'MK09': 8,
     'MK10': 9,
     'MK11': 10,
     'MK12': 11,
     'MK13': 12,
     'MK14': 13,
     'MK15': 14,
     'MK16': 15,
     'MK17': 16,
     'MK18': 17,
     'MK19': 18,
     'MK21': 19},
    'label': {'SSS': 'KOKO MAA',
     'MK01': 'Uudenmaan maakunta',
     'MK02': 'Varsinais-Suomen maakunta',
     'MK04': 'Satakunnan maakunta',
     'MK05': 'Kanta-Hämeen maakunta',
     'MK06': 'Pirkanmaan maakunta',
     'MK07': 'Päijät-Hämeen maakunta',
     'MK08': 'Kymenlaakson maakunta',
     'MK09': 'Etelä-Karjalan maakunta',
     'MK10': 'Etelä-Savon maakunta',
     'MK11': 'Pohjois-Savon maakunta',
     'MK12': 'Pohjois-Karjalan maakunta',
     'MK13': 'Keski-Suomen maakunta',
     'MK14': 'Etelä-Pohjanmaan maakunta',
     'MK15': 'Pohjanmaan maakunta',
     'MK16': 'Keski-Pohjanmaan maakunta',
     'MK17': 'Pohjois-Pohjanmaan maakunta',
     'MK18': 'Kainuun maakunta',
     'MK19': 'Lapin maakunta',
     'MK21': 'Ahvenanmaa'}}},
  'Tiedot': {'label': 'Tiedot',
   'category': {'index': {'M408': 0,
     'M411': 1,
     'M476': 2,
     'M391': 3,
     'M421': 4,
     'M478': 5,
     'M404': 6,
     'M410': 7,
     'M303': 8,
     'M297': 9,
     'M302': 10,
     'M44': 11,
     'M62': 12,
     'M70': 13,
     'M488': 14,
     'M486': 15,
     'M137': 16,
     'M140': 17,
     'M130': 18,
     'M162': 19,
     'M78': 20,
     'M485': 21,
     'M152': 22,
     'M72': 23,
     'M84': 24,
     'M106': 25,
     'M151': 26,
     'M499': 27,
     'M496': 28,
     'M495': 29,
     'M497': 30,
     'M498': 31},
    'label': {'M408': 'Taajama-aste, %, 2020',
     'M411': 'Väkiluku, 2021',
     'M476': 'Väkiluvun muutos edellisestä vuodesta, %, 2021',
     'M391': 'Alle 15-vuotiaiden osuus väestöstä, %, 2021',
     'M421': '15-64 -vuotiaiden osuus väestöstä, %, 2021',
     'M478': 'Yli 64-vuotiaiden osuus väestöstä, %, 2021',
     'M404': 'Ruotsinkielisten osuus väestöstä, %, 2021',
     'M410': 'Ulkomaan kansalaisten osuus väestöstä, %, 2021',
     'M303': 'Syntyneiden enemmyys, henkilöä, 2021',
     'M297': 'Kuntien välinen muuttovoitto/-tappio, henkilöä, 2021',
     'M302': 'Perheiden lukumäärä, 2020',
     'M44': 'Asuntokuntien lukumäärä, 2021',
     'M62': 'Rivi- ja pientaloissa asuvien asuntokuntien osuus, %, 2021',
     'M70': 'Vuokra-asunnoissa asuvien asuntokuntien osuus, %, 2020',
     'M488': 'Vähintään toisen asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2020',
     'M486': 'Korkea-asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2020',
     'M137': 'Alueella asuvan työllisen työvoiman määrä, 2020',
     'M140': 'Työllisyysaste, %, 2020',
     'M130': 'Asuinkunnassaan työssäkäyvien osuus, %, 2020',
     'M162': 'Työttömien osuus työvoimasta, %, 2020',
     'M78': 'Eläkeläisten osuus väestöstä, %, 2020',
     'M485': 'Taloudellinen huoltosuhde, 2020',
     'M152': 'Alueella olevien työpaikkojen lukumäärä, 2020',
     'M72': 'Alkutuotannon työpaikkojen osuus, %, 2020',
     'M84': 'Jalostuksen työpaikkojen osuus, %, 2020',
     'M106': 'Palvelujen työpaikkojen osuus, %, 2020',
     'M151': 'Työpaikkaomavaraisuus, 2020',
     'M499': 'Vuosikate, euroa/asukas, 2020',
     'M496': 'Lainakanta, euroa/asukas, 2020',
     'M495': 'Konsernin lainakanta, euroa/asukas, 2020',
     'M497': 'Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2020',
     'M498': 'Sosiaali- ja terveystoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2020'},
    'unit': {'M408': {'base': '?', 'decimals': 1},
     'M411': {'base': '?', 'decimals': 0},
     'M476': {'base': '?', 'decimals': 1},
     'M391': {'base': '?', 'decimals': 1},
     'M421': {'base': '?', 'decimals': 1},
     'M478': {'base': '?', 'decimals': 1},
     'M404': {'base': '?', 'decimals': 1},
     'M410': {'base': '?', 'decimals': 1},
     'M303': {'base': '?', 'decimals': 0},
     'M297': {'base': '?', 'decimals': 0},
     'M302': {'base': '?', 'decimals': 0},
     'M44': {'base': '?', 'decimals': 0},
     'M62': {'base': '?', 'decimals': 1},
     'M70': {'base': '?', 'decimals': 1},
     'M488': {'base': '?', 'decimals': 1},
     'M486': {'base': '?', 'decimals': 1},
     'M137': {'base': '?', 'decimals': 0},
     'M140': {'base': '?', 'decimals': 1},
     'M130': {'base': '?', 'decimals': 1},
     'M162': {'base': '?', 'decimals': 1},
     'M78': {'base': '?', 'decimals': 1},
     'M485': {'base': '?', 'decimals': 1},
     'M152': {'base': '?', 'decimals': 0},
     'M72': {'base': '?', 'decimals': 1},
     'M84': {'base': '?', 'decimals': 1},
     'M106': {'base': '?', 'decimals': 1},
     'M151': {'base': '?', 'decimals': 1},
     'M499': {'base': '?', 'decimals': 1},
     'M496': {'base': '?', 'decimals': 1},
     'M495': {'base': '?', 'decimals': 1},
     'M497': {'base': '?', 'decimals': 1},
     'M498': {'base': '?', 'decimals': 1}}}}},
 'value': [86.5,
  5548241,
  0.3,
  15.4,
  61.6,
  23.1,
  5.2,
  5.3,
  -8065,
  0,
  1467653,
  2793636,
  38.2,
  34.4,
  74.2,
  32.6,
  2284673,
  69.5,
  64.9,
  13.3,
  26,
  142.2,
  2284665,
  2.7,
  20.5,
  75.4,
  100,
  738.8,
  3448.4,
  7453.8,
  2078.8,
  3622.3,
  95.6,
  1714741,
  0.7,
  16.1,
  65.7,
  18.1,
  7.6,
  9.7,
  4257,
  -2461,
  444606,
  844561,
  23.7,
  40.5,
  74.5,
  39.7,
  768692,
  71.1,
  57.5,
  12.9,
  20.1,
  121.5,
  797633,
  0.5,
  16.3,
  81.8,
  103.8,
  988.5,
  3044.4,
  8919,
  2247.3,
  3253.4,
  85.8,
  483477,
  0.4,
  14.5,
  61.5,
  24,
  5.7,
  5.1,
  -926,
  1155,
  128539,
  248584,
  37.2,
  33.4,
  74.2,
  32.1,
  199102,
  69.4,
  58.7,
  13.2,
  27,
  141.8,
  193786,
  2.8,
  22.2,
  73.5,
  97.3,
  532.6,
  3072.3,
  5268.1,
  1942.7,
  3570,
  83.6,
  214281,
  -0.5,
  14.1,
  57.8,
  28.1,
  0.4,
  3.4,
  -1215,
  -577,
  58979,
  110295,
  54.2,
  27.3,
  71.5,
  26.5,
  83472,
  69.5,
  68.6,
  13.4,
  31.5,
  158.1,
  83682,
  3.5,
  27.9,
  67.1,
  100.3,
  596.9,
  2666.5,
  4850.1,
  1855.4,
  3789.4,
  82.6,
  170213,
  -0.2,
  14.6,
  59,
  26.4,
  0.4,
  3.2,
  -738,
  48,
  46193,
  86817,
  45.8,
  28.6,
  72.9,
  28.8,
  69254,
  71.5,
  55.1,
  11.7,
  29.5,
  146.3,
  62551,
  3.3,
  24.5,
  70.9,
  90.3,
  609.6,
  3441.7,
  5446.5,
  1785.5,
  3619.7,
  88.7,
  527478,
  0.9,
  15.2,
  62.5,
  22.3,
  0.4,
  3.4,
  -401,
  3375,
  138425,
  270785,
  33.8,
  35.5,
  76.6,
  33.6,
  217568,
  69.2,
  60.4,
  13,
  25.3,
  140.3,
  211843,
  1.9,
  21.7,
  74.9,
  97.4,
  706.8,
  3361.6,
  6767.8,
  2044.5,
  3506.1,
  87.4,
  205124,
  -0.3,
  14,
  58.2,
  27.7,
  0.4,
  3.7,
  -1084,
  -63,
  54639,
  108737,
  36.8,
  34.1,
  71.1,
  27.4,
  77524,
  67.1,
  65.3,
  16.3,
  31,
  165.4,
  73091,
  2.8,
  26.4,
  69.3,
  94.3,
  866.6,
  5478.7,
  7720.4,
  1886.9,
  3586.6,
  88.3,
  161391,
  -0.9,
  12.9,
  57.9,
  29.2,
  0.8,
  3.8,
  -1251,
  -437,
  43839,
  86255,
  45.7,
  29.8,
  72.4,
  26.5,
  60838,
  66.7,
  76.6,
  15.7,
  33.4,
  167.6,
  59628,
  2.4,
  21.2,
  75,
  98,
  763.5,
  4216.3,
  7479.3,
  2051.9,
  4219.6,
  84.1,
  126107,
  -0.6,
  12.8,
  58.7,
  28.5,
  0.2,
  4,
  -974,
  -505,
  33986,
  67551,
  46.2,
  31.6,
  73,
  28,
  47467,
  65.6,
  73.5,
  15.4,
  32.1,
  167.4,
  46401,
  3.1,
  22.7,
  72.7,
  97.8,
  484.5,
  3016.4,
  6729.6,
  1799,
  4032.2,
  72.2,
  131688,
  -0.8,
  12.1,
  55.4,
  32.5,
  0.2,
  2.3,
  -1248,
  -56,
  35780,
  70694,
  48.4,
  29.1,
  72,
  26.4,
  48568,
  67.7,
  83.5,
  13.6,
  36.3,
  173.2,
  48321,
  6.3,
  19.8,
  72.4,
  99.5,
  770,
  4200.9,
  7857.9,
  1773.1,
  4503.1,
  76.4,
  248363,
  0,
  14.2,
  59.4,
  26.4,
  0.1,
  2.3,
  -1179,
  707,
  66915,
  129054,
  41.7,
  33,
  75.1,
  28.9,
  96967,
  67.9,
  74.1,
  13.6,
  30.6,
  156,
  95722,
  5.7,
  19.9,
  73.1,
  98.7,
  551.8,
  3598.7,
  8233.3,
  1977.9,
  4174.5,
  72.8,
  163281,
  -0.2,
  13.4,
  58.7,
  27.9,
  0.1,
  2.8,
  -916,
  -64,
  43314,
  86272,
  49.1,
  32.5,
  74.5,
  27,
  59372,
  63.6,
  71.2,
  16.9,
  31.6,
  175.4,
  58837,
  5.3,
  21.5,
  71.9,
  99.1,
  836.1,
  2498.9,
  5436.8,
  1844.1,
  3920,
  81.5,
  272683,
  0,
  15.2,
  60.7,
  24.1,
  0.2,
  2.4,
  -662,
  63,
  71717,
  140374,
  40.7,
  34.9,
  75.7,
  30.8,
  105045,
  66,
  73.6,
  15.5,
  27.3,
  159.5,
  103233,
  3.3,
  21.8,
  73.5,
  98.3,
  589.7,
  3140.6,
  7979.1,
  1913.2,
  3576,
  73.8,
  191762,
  -0.2,
  16.1,
  57.4,
  26.6,
  0.3,
  1.9,
  -634,
  -130,
  52700,
  92502,
  60.6,
  25.3,
  72.4,
  26.2,
  76659,
  72.2,
  70.7,
  10.6,
  29.9,
  150.7,
  75352,
  7.6,
  24.6,
  66.4,
  98.3,
  581.9,
  4335,
  7992.8,
  2018.1,
  3977.2,
  84.6,
  176041,
  0.1,
  16.8,
  59.6,
  23.6,
  50.6,
  5.9,
  -81,
  -725,
  48120,
  82628,
  52.4,
  28.1,
  73.3,
  31.7,
  73717,
  73.2,
  66.6,
  10.3,
  25.7,
  138.5,
  74907,
  5.2,
  29.7,
  63.8,
  101.6,
  740.5,
  4218.3,
  7462.7,
  2381.4,
  3634.8,
  79.5,
  67915,
  -0.1,
  18.4,
  57.3,
  24.3,
  9,
  2.3,
  -34,
  -215,
  18585,
  30877,
  61.2,
  26.7,
  72,
  26.2,
  27352,
  73.2,
  80.8,
  10.2,
  27,
  148.6,
  27775,
  6.4,
  22.6,
  69.9,
  101.5,
  632,
  5220,
  9355.9,
  2104.1,
  3829.7,
  84.2,
  415603,
  0.4,
  18.5,
  61,
  20.5,
  0.2,
  2.4,
  295,
  129,
  106931,
  197411,
  46.7,
  32.8,
  75.9,
  30.5,
  163920,
  68.5,
  75.7,
  13.3,
  24.1,
  152.5,
  162329,
  4,
  22.6,
  72.3,
  99,
  541.1,
  4186.2,
  6575,
  2193.1,
  3633.8,
  74.7,
  71255,
  -0.6,
  13.6,
  56.6,
  29.8,
  0.1,
  2.5,
  -562,
  -277,
  19277,
  36812,
  50.3,
  28.6,
  73.9,
  25.6,
  27098,
  68.5,
  80.1,
  12.3,
  34.3,
  164.5,
  27152,
  5.6,
  19.8,
  73.7,
  100.2,
  222.2,
  3503.3,
  12494.3,
  2407.4,
  4787.7,
  78.3,
  176494,
  -0.1,
  14.6,
  58.7,
  26.6,
  0.3,
  2.4,
  -742,
  86,
  46853,
  89126,
  52.5,
  31.8,
  75.1,
  27.6,
  68369,
  67.5,
  80.7,
  14.9,
  30.5,
  158.4,
  68372,
  3.8,
  20.3,
  74,
  100,
  599.2,
  3544.7,
  5792.5,
  2059.2,
  4328.3,
  63.8,
  30344,
  0.7,
  16.4,
  60.2,
  23.4,
  86,
  12.1,
  30,
  -53,
  8255,
  14301,
  62.9,
  27.6,
  69.1,
  29.2,
  13689,
  76.5,
  48.9,
  9.3,
  23.6,
  120.1,
  14050,
  3.5,
  13.9,
  79.7,
  102.6,
  516.8,
  1637.7,
  2579.2,
  2500.5,
  1936.3],
 'role': {'metric': ['Tiedot']},
 'version': '2.0',
 'extension': {'px': {'decimals': 0}}}

In [4]:
def get_region_names():
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36',
 'Content-Type': 'application/json'}
    df = None
    for lang in ['fi','sv','en']:
        url = f"https://pxdata.stat.fi:443/PxWeb/api/v1/{lang}/Kuntien_avainluvut/2021/kuntien_avainluvut_2021_viimeisin.px"
        json = requests.get(url, headers=headers).json()
        dff = pd.DataFrame([{'id':i, {'fi':'nimi','sv':'namn','en':'name'}[lang]:name} for i,name in zip(json['variables'][0]['values'],json['variables'][0]['valueTexts'])])
        if df is None:
            df = dff
        else:
            df = pd.merge(left = df, right = dff, on = 'id', how = 'inner')
    df = df.astype({'id':'category','nimi':'category', 'namn':'category', 'name':'category'})
    return df.set_index('id')
reg_names = get_region_names()

reg_names

,nimi,namn,name
id,,,
SSS,KOKO MAA,HELA LANDET,WHOLE COUNTRY
020,Akaa,Ackas,Akaa
005,Alajärvi,Alajärvi,Alajärvi
009,Alavieska,Alavieska,Alavieska
010,Alavus,Alavo,Alavus
...,...,...,...
SK196,Tunturi-Lapin seutukunta,Tunturi-Lappi ekon. reg.,Tunturi-Lappi sub-regional unit
SK197,Pohjois-Lapin seutukunta,Norra Lapplands ekon. reg.,Pohjois-Lappi sub-regional unit
SK211,Mariehamns stad,Mariehamns stad,Mariehamns stad sub-regional unit
SK212,Ålands landsbygd,Ålands landsbygd,Ålands landsbygd sub-regional unit
SK213,Ålands skärgård,Ålands skärgård,Ålands skärgård sub-regional unit

In [151]:
reg_names[reg_names.id.str.contains('MK')]

,id,nimi,namn,name
310,MK01,Uudenmaan maakunta,Nylands landskap,Uusimaa
311,MK02,Varsinais-Suomen maakunta,Egentliga Finlands landskap,Southwest Finland
312,MK04,Satakunnan maakunta,Satakunta landskap,Satakunta
313,MK05,Kanta-Hämeen maakunta,Egentliga Tavastlands landskap,Kanta-Häme
314,MK06,Pirkanmaan maakunta,Birkalands landskap,Pirkanmaa
315,MK07,Päijät-Hämeen maakunta,Päijänne-Tavastlands landskap,Päijät-Häme
316,MK08,Kymenlaakson maakunta,Kymmenedalens landskap,Kymenlaakso
317,MK09,Etelä-Karjalan maakunta,Södra Karelens landskap,South Karelia
318,MK10,Etelä-Savon maakunta,Södra Savolax landskap,South Savo
319,MK11,Pohjois-Savon maakunta,Norra Savolax landskap,North Savo
320,MK12,Pohjois-Karjalan maakunta,Norra Karelens landskap,North Karelia
321,MK13,Keski-Suomen maakunta,Mellersta Finlands landskap,Central Finland
322,MK14,Etelä-Pohjanmaan maakunta,Södra Österbottens landskap,South Ostrobothnia
323,MK15,Pohjanmaan maakunta,Österbottens landskap,Ostrobothnia
324,MK16,Keski-Pohjanmaan maakunta,Mellersta Österbottens landskap,Central Ostrobothnia
325,MK17,Pohjois-Pohjanmaan maakunta,Norra Österbottens landskap,North Ostrobothnia
326,MK18,Kainuun maakunta,Kajanalands landskap,Kainuu
327,MK19,Lapin maakunta,Lapplands landskap,Lapland
328,MK21,Ahvenanmaa,Åland,Åland

In [28]:
requests.get('https://pxdata.stat.fi:443/PxWeb/api/v1/fi/Kuntien_avainluvut/2021/kuntien_avainluvut_2021_aikasarja.px').json()['variables'][1]

{'code': 'Tiedot',
 'text': 'Tiedot',
 'values': ['M408',
  'M411',
  'M476',
  'M391',
  'M421',
  'M478',
  'M404',
  'M410',
  'M303',
  'M297',
  'M302',
  'M44',
  'M62',
  'M70',
  'M488',
  'M486',
  'M137',
  'M140',
  'M130',
  'M162',
  'M78',
  'M485',
  'M152',
  'M72',
  'M84',
  'M106',
  'M151',
  'M499',
  'M496',
  'M495',
  'M497',
  'M498'],
 'valueTexts': ['Taajama-aste, %',
  'Väkiluku',
  'Väkiluvun muutos edellisestä vuodesta, %',
  'Alle 15-vuotiaiden osuus väestöstä, %',
  '15-64 -vuotiaiden osuus väestöstä, %',
  'Yli 64-vuotiaiden osuus väestöstä, %',
  'Ruotsinkielisten osuus väestöstä, %',
  'Ulkomaan kansalaisten osuus väestöstä, %',
  'Syntyneiden enemmyys, henkilöä',
  'Kuntien välinen muuttovoitto/-tappio, henkilöä',
  'Perheiden lukumäärä',
  'Asuntokuntien lukumäärä',
  'Rivi- ja pientaloissa asuvien asuntokuntien osuus, %',
  'Vuokra-asunnoissa asuvien asuntokuntien osuus, %',
  'Vähintään toisen asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %',
  'Korkea-asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %',
  'Alueella asuvan työllisen työvoiman määrä',
  'Työllisyysaste, %',
  'Asuinkunnassaan työssäkäyvien osuus, %',
  'Työttömien osuus työvoimasta, %',
  'Eläkeläisten osuus väestöstä, %',
  'Taloudellinen huoltosuhde',
  'Alueella olevien työpaikkojen lukumäärä',
  'Alkutuotannon työpaikkojen osuus, %',
  'Jalostuksen työpaikkojen osuus, %',
  'Palvelujen työpaikkojen osuus, %',
  'Työpaikkaomavaraisuus',
  'Vuosikate, euroa/asukas',
  'Lainakanta, euroa/asukas',
  'Konsernin lainakanta, euroa/asukas',
  'Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset, euroa/asukas',
  'Sosiaali- ja terveystoiminta yhteensä, nettokäyttökustannukset, euroa/asukas']}

In [31]:
def get_series_indicator_names():
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36',
 'Content-Type': 'application/json'}
    df = None
    for lang in ['fi','sv','en']:
        url = f"https://pxdata.stat.fi:443/PxWeb/api/v1/{lang}/Kuntien_avainluvut/2021/kuntien_avainluvut_2021_aikasarja.px"
        json = requests.get(url, headers=headers).json()
        dff = pd.DataFrame([{'id':i, {'fi':'nimi','sv':'namn','en':'name'}[lang]:name} for i,name in zip(json['variables'][1]['values'],json['variables'][1]['valueTexts'])])
        if df is None:
            df = dff
        else:
            df = pd.merge(left = df, right = dff, on = 'id', how = 'inner')
    return df.to_dict('records')
pd.DataFrame(get_series_indicator_names())

,id,nimi,namn,name
0,M408,"Taajama-aste, %","Tätortsgrad, %","Degree of urbanisation, %"
1,M411,Väkiluku,Folkmängd,Population
2,M476,"Väkiluvun muutos edellisestä vuodesta, %","Förändring i folkmängden från året innan, %","Population change from the previous year, %"
3,M391,"Alle 15-vuotiaiden osuus väestöstä, %","Andelen personer under 15 år av befolkningen, %",Share of persons aged under 15 of the populati...
4,M421,"15-64 -vuotiaiden osuus väestöstä, %","Andelen 15–64-åringar av befolkningen, %",Share of persons aged 15 to 64 of the populati...
5,M478,"Yli 64-vuotiaiden osuus väestöstä, %","Andelen personer över 64 år av befolkningen, %",Share of persons aged over 64 of the populatio...
6,M404,"Ruotsinkielisten osuus väestöstä, %","Andelen svenskspråkiga av befolkningen, %","Share of Swedish-speakers of the population, %"
7,M410,"Ulkomaan kansalaisten osuus väestöstä, %","Andelen utländska medborgare av befolkningen, %","Share of foreign citizens of the population, %"
8,M303,"Syntyneiden enemmyys, henkilöä","Födelseöverskott, personer","Excess of births, persons"
9,M297,"Kuntien välinen muuttovoitto/-tappio, henkilöä",Inflyttningsöverskott/-underskott mellan kommu...,"Intermunicipal migration gain/loss, persons"
10,M302,Perheiden lukumäärä,Antal familjer,Number of families
11,M44,Asuntokuntien lukumäärä,Antal bostadshushåll,Number of household-dwelling units
12,M62,Rivi- ja pientaloissa asuvien asuntokuntien os...,Andelen bostadshushåll som bor i rad- eller sm...,Share of household-dwelling units living in te...
13,M70,"Vuokra-asunnoissa asuvien asuntokuntien osuus, %","Andelen bostadshushåll som bor i hyresbostäder, %",Share of household-dwelling units living in re...
14,M488,Vähintään toisen asteen tutkinnon suorittaneid...,Andelen personer som avlagt examen på minst an...,Share of persons aged 15 or over with at least...
15,M486,Korkea-asteen tutkinnon suorittaneiden osuus 1...,Andelen personer som avlagt examen på högre ni...,Share of persons aged 15 or over with tertiary...
16,M137,Alueella asuvan työllisen työvoiman määrä,Inom området bosatt sysselsatt arbetskraft,Employed labour force resident in the area
17,M140,"Työllisyysaste, %","Relativt sysselsättningstal, %","Employment rate, %"
18,M130,"Asuinkunnassaan työssäkäyvien osuus, %",Andelen personer som arbetar i sin bostadskomm...,Share of persons working in their municipality...
19,M162,"Työttömien osuus työvoimasta, %","Arbetslösas andel av arbetskraften, %",Proportion of the unemployed among the labour ...
20,M78,"Eläkeläisten osuus väestöstä, %","Andelen pensionärer av befolkningen, %","Proportion of pensioners of the population, %"
21,M485,Taloudellinen huoltosuhde,Ekonomisk försörjningskvot,Economic dependency ratio
22,M152,Alueella olevien työpaikkojen lukumäärä,Antalet arbetsplatser i kommunen,Number of workplaces in the area
23,M72,"Alkutuotannon työpaikkojen osuus, %","Andelen arbetsplatser inom primärproduktionen, %","Share of workplaces in primary production, %"
24,M84,"Jalostuksen työpaikkojen osuus, %","Andelen arbetsplatser inom förädling, %","Share of workplaces in secondary production, %"
25,M106,"Palvelujen työpaikkojen osuus, %","Andelen arbetsplatser inom tjänster, %","Share of workplaces in services, %"
26,M151,Työpaikkaomavaraisuus,Arbetsplatssufficiens,Workplace self-sufficiency
27,M499,"Vuosikate, euroa/asukas","Årsbidrag, €/invånare","Annual contribution margin, EUR per capita"
28,M496,"Lainakanta, euroa/asukas","Lånestock, €/invånare","Loan stock, EUR per capita"
29,M495,"Konsernin lainakanta, euroa/asukas","Koncernens årsbidrag, €/invånare","Group loan stock, EUR per capita"
30,M497,"Opetus- ja kulttuuritoiminta yhteensä, nettokä...","Undervisnings- och kulturverksamhet totalt, ne...","Educational and cultural activities, total, op..."
31,M498,"Sosiaali- ja terveystoiminta yhteensä, nettokä...","Social- och hälsovård totalt, nettodriftskostn...","Social and health care activities, total, oper..."

In [71]:
def get_latest_indicator_names():
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36',
 'Content-Type': 'application/json'}
    df = None
    for lang in ['fi','sv','en']:
        url = f"https://pxdata.stat.fi:443/PxWeb/api/v1/{lang}/Kuntien_avainluvut/2021/kuntien_avainluvut_2021_viimeisin.px"
        json = requests.get(url, headers=headers).json()
        dff = pd.DataFrame([{'id':i, {'fi':'nimi','sv':'namn','en':'name'}[lang]:name} for i,name in zip(json['variables'][1]['values'],json['variables'][1]['valueTexts'])])
        if df is None:
            df = dff
        else:
            df = pd.merge(left = df, right = dff, on = 'id', how = 'inner')
    return df.drop('id',axis=1).set_index('name')
get_latest_indicator_names()

,nimi,namn
name,,
"Degree of urbanisation, %, 2020","Taajama-aste, %, 2020","Tätortsgrad, %, 2020"
"Population, 2021","Väkiluku, 2021","Folkmängd, 2021"
"Population change from the previous year, %, 2021","Väkiluvun muutos edellisestä vuodesta, %, 2021","Förändring i folkmängden från året innan, %, 2021"
"Share of persons aged under 15 of the population, %, 2021","Alle 15-vuotiaiden osuus väestöstä, %, 2021","Andelen personer under 15 år av befolkningen, ..."
"Share of persons aged 15 to 64 of the population, %, 2021","15-64 -vuotiaiden osuus väestöstä, %, 2021","Andelen 15–64-åringar av befolkningen, %, 2021"
"Share of persons aged over 64 of the population, %, 2021","Yli 64-vuotiaiden osuus väestöstä, %, 2021","Andelen personer över 64 år av befolkningen, %..."
"Share of Swedish-speakers of the population, %, 2021","Ruotsinkielisten osuus väestöstä, %, 2021","Andelen svenskspråkiga av befolkningen, %, 2021"
"Share of foreign citizens of the population, %, 2021","Ulkomaan kansalaisten osuus väestöstä, %, 2021","Andelen utländska medborgare av befolkningen, ..."
"Excess of births, persons, 2021","Syntyneiden enemmyys, henkilöä, 2021","Födelseöverskott, personer, 2021"
"Intermunicipal migration gain/loss, persons, 2021","Kuntien välinen muuttovoitto/-tappio, henkilöä...",Inflyttningsöverskott/-underskott mellan kommu...
"Number of families, 2020","Perheiden lukumäärä, 2020","Antal familjer, 2020"
"Number of household-dwelling units, 2021","Asuntokuntien lukumäärä, 2021","Antal bostadshushåll, 2021"
"Share of household-dwelling units living in terraced houses and detached houses, %, 2021",Rivi- ja pientaloissa asuvien asuntokuntien os...,Andelen bostadshushåll som bor i rad- eller sm...
"Share of household-dwelling units living in rental dwellings, %, 2020","Vuokra-asunnoissa asuvien asuntokuntien osuus,...",Andelen bostadshushåll som bor i hyresbostäder...
"Share of persons aged 15 or over with at least upper secondary qualifications, %, 2020",Vähintään toisen asteen tutkinnon suorittaneid...,Andelen personer som avlagt examen på minst an...
"Share of persons aged 15 or over with tertiary level qualifications, %, 2020",Korkea-asteen tutkinnon suorittaneiden osuus 1...,Andelen personer som avlagt examen på högre ni...
"Employed labour force resident in the area, 2020","Alueella asuvan työllisen työvoiman määrä, 2020","Inom området bosatt sysselsatt arbetskraft, 2020"
"Employment rate, %, 2020","Työllisyysaste, %, 2020","Relativt sysselsättningstal, %, 2020"
"Share of persons working in their municipality of residence, %, 2020","Asuinkunnassaan työssäkäyvien osuus, %, 2020",Andelen personer som arbetar i sin bostadskomm...
"Proportion of the unemployed among the labour force, %, 2020","Työttömien osuus työvoimasta, %, 2020","Arbetslösas andel av arbetskraften, %, 2020"
"Proportion of pensioners of the population, %, 2020","Eläkeläisten osuus väestöstä, %, 2020","Andelen pensionärer av befolkningen, %, 2020"
"Economic dependency ratio, 2020","Taloudellinen huoltosuhde, 2020","Ekonomisk försörjningskvot, 2020"
"Number of workplaces in the area, 2020","Alueella olevien työpaikkojen lukumäärä, 2020","Antalet arbetsplatser i kommunen, 2020"
"Share of workplaces in primary production, %, 2020","Alkutuotannon työpaikkojen osuus, %, 2020","Andelen arbetsplatser inom primärproduktionen,..."
"Share of workplaces in secondary production, %, 2020","Jalostuksen työpaikkojen osuus, %, 2020","Andelen arbetsplatser inom förädling, %, 2020"
"Share of workplaces in services, %, 2020","Palvelujen työpaikkojen osuus, %, 2020","Andelen arbetsplatser inom tjänster, %, 2020"
"Workplace self-sufficiency, 2020","Työpaikkaomavaraisuus, 2020","Arbetsplatssufficiens, 2020"
"Annual contribution margin, EUR per capita, 2020","Vuosikate, euroa/asukas, 2020","Årsbidrag, €/invånare, 2020"
"Loan stock, EUR per capita, 2020","Lainakanta, euroa/asukas, 2020","Lånestock, €/invånare, 2020"
"Group loan stock, EUR per capita, 2020","Konsernin lainakanta, euroa/asukas, 2020","Koncernens årsbidrag, €/invånare, 2020"
"Educational and cultural activities, total, operating net costs, EUR per capita, 2020","Opetus- ja kulttuuritoiminta yhteensä, nettokä...","Undervisnings- och kulturverksamhet totalt, ne..."
"Social and health care activities, total, operating net costs, EUR per capita, 2020","Sosiaali- ja terveystoiminta yhteensä, nettokä...","Social- och hälsovård totalt, nettodriftskostn..."

In [19]:
df_series = None
for lang in ['fi','sv','en']:
    url = f"https://pxdata.stat.fi:443/PxWeb/api/v1/{lang}/Kuntien_avainluvut/2021/kuntien_avainluvut_2021_aikasarja.px"
    json = requests.get(url, headers=headers).json()
    dff_series = pd.DataFrame([{'id':i, {'fi':'nimi','sv':'namn','en':'name'}[lang]:name} for i,name in zip(json['variables'][0]['values'],json['variables'][0]['valueTexts'])])
    if df_series is None:
        df_series = dff_series
    else:
        df_series = pd.merge(left = df_series, right = dff_series, on = 'id', how = 'inner')
df_series

,id,nimi,namn,name
0,SSS,KOKO MAA,HELA LANDET,WHOLE COUNTRY
1,020,Akaa,Ackas,Akaa
2,005,Alajärvi,Alajärvi,Alajärvi
3,009,Alavieska,Alavieska,Alavieska
4,010,Alavus,Alavo,Alavus
...,...,...,...,...
393,SK196,Tunturi-Lapin seutukunta,Tunturi-Lappi ekon. reg.,Tunturi-Lappi sub-regional unit
394,SK197,Pohjois-Lapin seutukunta,Norra Lapplands ekon. reg.,Pohjois-Lappi sub-regional unit
395,SK211,Mariehamns stad,Mariehamns stad,Mariehamns stad sub-regional unit
396,SK212,Ålands landsbygd,Ålands landsbygd,Ålands landsbygd sub-regional unit
397,SK213,Ålands skärgård,Ålands skärgård,Ålands skärgård sub-regional unit

In [5]:
list(json['dimension']['Alue 2021']['category']['index'].values())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [6]:
list(json['dimension']['Alue 2021']['category']['label'].values())

['KOKO MAA',
 'Uudenmaan maakunta',
 'Varsinais-Suomen maakunta',
 'Satakunnan maakunta',
 'Kanta-Hämeen maakunta',
 'Pirkanmaan maakunta',
 'Päijät-Hämeen maakunta',
 'Kymenlaakson maakunta',
 'Etelä-Karjalan maakunta',
 'Etelä-Savon maakunta',
 'Pohjois-Savon maakunta',
 'Pohjois-Karjalan maakunta',
 'Keski-Suomen maakunta',
 'Etelä-Pohjanmaan maakunta',
 'Pohjanmaan maakunta',
 'Keski-Pohjanmaan maakunta',
 'Pohjois-Pohjanmaan maakunta',
 'Kainuun maakunta',
 'Lapin maakunta',
 'Ahvenanmaa']

In [11]:
region_fin = pd.DataFrame([{'index':i, 'nimi':v} for i,v in zip(list(json['dimension']['Alue 2021']['category']['index'].values()),list(json['dimension']['Alue 2021']['category']['label'].values()))])
region_fin

    index                         nimi
0       0                     KOKO MAA
1       1           Uudenmaan maakunta
2       2    Varsinais-Suomen maakunta
3       3          Satakunnan maakunta
4       4        Kanta-Hämeen maakunta
5       5          Pirkanmaan maakunta
6       6       Päijät-Hämeen maakunta
7       7        Kymenlaakson maakunta
8       8      Etelä-Karjalan maakunta
9       9         Etelä-Savon maakunta
10     10       Pohjois-Savon maakunta
11     11    Pohjois-Karjalan maakunta
12     12        Keski-Suomen maakunta
13     13    Etelä-Pohjanmaan maakunta
14     14          Pohjanmaan maakunta
15     15    Keski-Pohjanmaan maakunta
16     16  Pohjois-Pohjanmaan maakunta
17     17             Kainuun maakunta
18     18               Lapin maakunta
19     19                   Ahvenanmaa

In [66]:
def get_data():
    
    # Query url
    url = "https://pxdata.stat.fi:443/PxWeb/api/v1/en/Kuntien_avainluvut/2021/kuntien_avainluvut_2021_viimeisin.px"
    
    payload ={
  "query": [
    {
      "code": "Alue 2021",
      "selection": {
        "filter": "item",
        "values": [
          "SSS",
          "020",
          "005",
          "009",
          "010",
          "016",
          "018",
          "019",
          "035",
          "043",
          "046",
          "047",
          "049",
          "050",
          "051",
          "052",
          "060",
          "061",
          "062",
          "065",
          "069",
          "071",
          "072",
          "074",
          "075",
          "076",
          "077",
          "078",
          "079",
          "081",
          "082",
          "086",
          "111",
          "090",
          "091",
          "097",
          "098",
          "102",
          "103",
          "105",
          "106",
          "108",
          "109",
          "139",
          "140",
          "142",
          "143",
          "145",
          "146",
          "153",
          "148",
          "149",
          "151",
          "152",
          "165",
          "167",
          "169",
          "170",
          "171",
          "172",
          "176",
          "177",
          "178",
          "179",
          "181",
          "182",
          "186",
          "202",
          "204",
          "205",
          "208",
          "211",
          "213",
          "214",
          "216",
          "217",
          "218",
          "224",
          "226",
          "230",
          "231",
          "232",
          "233",
          "235",
          "236",
          "239",
          "240",
          "320",
          "241",
          "322",
          "244",
          "245",
          "249",
          "250",
          "256",
          "257",
          "260",
          "261",
          "263",
          "265",
          "271",
          "272",
          "273",
          "275",
          "276",
          "280",
          "284",
          "285",
          "286",
          "287",
          "288",
          "290",
          "291",
          "295",
          "297",
          "300",
          "301",
          "304",
          "305",
          "312",
          "316",
          "317",
          "318",
          "398",
          "399",
          "400",
          "407",
          "402",
          "403",
          "405",
          "408",
          "410",
          "416",
          "417",
          "418",
          "420",
          "421",
          "422",
          "423",
          "425",
          "426",
          "444",
          "430",
          "433",
          "434",
          "435",
          "436",
          "438",
          "440",
          "441",
          "475",
          "478",
          "480",
          "481",
          "483",
          "484",
          "489",
          "491",
          "494",
          "495",
          "498",
          "499",
          "500",
          "503",
          "504",
          "505",
          "508",
          "507",
          "529",
          "531",
          "535",
          "536",
          "538",
          "541",
          "543",
          "545",
          "560",
          "561",
          "562",
          "563",
          "564",
          "309",
          "576",
          "577",
          "578",
          "445",
          "580",
          "581",
          "599",
          "583",
          "854",
          "584",
          "588",
          "592",
          "593",
          "595",
          "598",
          "601",
          "604",
          "607",
          "608",
          "609",
          "611",
          "638",
          "614",
          "615",
          "616",
          "619",
          "620",
          "623",
          "624",
          "625",
          "626",
          "630",
          "631",
          "635",
          "636",
          "678",
          "710",
          "680",
          "681",
          "683",
          "684",
          "686",
          "687",
          "689",
          "691",
          "694",
          "697",
          "698",
          "700",
          "702",
          "704",
          "707",
          "729",
          "732",
          "734",
          "736",
          "790",
          "738",
          "739",
          "740",
          "742",
          "743",
          "746",
          "747",
          "748",
          "791",
          "749",
          "751",
          "753",
          "755",
          "758",
          "759",
          "761",
          "762",
          "765",
          "766",
          "768",
          "771",
          "777",
          "778",
          "781",
          "783",
          "831",
          "832",
          "833",
          "834",
          "837",
          "844",
          "845",
          "846",
          "848",
          "849",
          "850",
          "851",
          "853",
          "857",
          "858",
          "859",
          "886",
          "887",
          "889",
          "890",
          "892",
          "893",
          "895",
          "785",
          "905",
          "908",
          "092",
          "915",
          "918",
          "921",
          "922",
          "924",
          "925",
          "927",
          "931",
          "934",
          "935",
          "936",
          "941",
          "946",
          "976",
          "977",
          "980",
          "981",
          "989",
          "992",
          "MK01",
          "MK02",
          "MK04",
          "MK05",
          "MK06",
          "MK07",
          "MK08",
          "MK09",
          "MK10",
          "MK11",
          "MK12",
          "MK13",
          "MK14",
          "MK15",
          "MK16",
          "MK17",
          "MK18",
          "MK19",
          "MK21",
          "SK011",
          "SK014",
          "SK015",
          "SK016",
          "SK021",
          "SK022",
          "SK023",
          "SK024",
          "SK025",
          "SK041",
          "SK043",
          "SK044",
          "SK051",
          "SK052",
          "SK053",
          "SK061",
          "SK063",
          "SK064",
          "SK068",
          "SK069",
          "SK071",
          "SK081",
          "SK082",
          "SK091",
          "SK093",
          "SK101",
          "SK103",
          "SK105",
          "SK111",
          "SK112",
          "SK113",
          "SK114",
          "SK115",
          "SK122",
          "SK124",
          "SK125",
          "SK131",
          "SK132",
          "SK133",
          "SK134",
          "SK135",
          "SK138",
          "SK141",
          "SK142",
          "SK144",
          "SK146",
          "SK152",
          "SK153",
          "SK154",
          "SK161",
          "SK162",
          "SK171",
          "SK173",
          "SK174",
          "SK175",
          "SK176",
          "SK177",
          "SK178",
          "SK181",
          "SK182",
          "SK191",
          "SK192",
          "SK193",
          "SK194",
          "SK196",
          "SK197",
          "SK211",
          "SK212",
          "SK213"
        ]
      }
    }
  ],
  "response": {
    "format": "json-stat2"
  }
    }
    
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36',
 'Content-Type': 'application/json'}
    
    json = requests.post(url, json = payload, headers = headers).json()



    cities = list(json['dimension']['Alue 2021']['category']['label'].values())
    
    dimensions = list(json['dimension']['Tiedot']['category']['label'].values())

    values = json['value']

    cities_df = pd.DataFrame(cities, columns = ['Region'])
    cities_df['index'] = 0
    dimensions_df = pd.DataFrame(dimensions, columns = ['dimensions'])
    dimensions_df['index'] = 0

    data = pd.merge(left = cities_df, right = dimensions_df, on = 'index', how = 'outer').drop('index',axis = 1)
    data['value'] = values
    data = pd.pivot_table(data, values = 'value', index = ['Region'], columns = 'dimensions')
    
    return data

data = get_data()

In [70]:
data

dimensions,"Annual contribution margin, EUR per capita, 2020","Degree of urbanisation, %, 2020","Economic dependency ratio, 2020","Educational and cultural activities, total, operating net costs, EUR per capita, 2020","Employed labour force resident in the area, 2020","Employment rate, %, 2020","Excess of births, persons, 2021","Group loan stock, EUR per capita, 2020","Intermunicipal migration gain/loss, persons, 2021","Loan stock, EUR per capita, 2020",...,"Share of persons aged 15 or over with tertiary level qualifications, %, 2020","Share of persons aged 15 to 64 of the population, %, 2021","Share of persons aged over 64 of the population, %, 2021","Share of persons aged under 15 of the population, %, 2021","Share of persons working in their municipality of residence, %, 2020","Share of workplaces in primary production, %, 2020","Share of workplaces in secondary production, %, 2020","Share of workplaces in services, %, 2020","Social and health care activities, total, operating net costs, EUR per capita, 2020","Workplace self-sufficiency, 2020"
Region,,,,,,,,,,,,,,,,,,,,,
Akaa,1066.9,87.9,149.4,1801.7,6571.0,71.5,-15.0,4623.2,64.0,3199.6,...,25.5,58.9,24.8,16.3,43.8,3.1,33.8,61.4,3252.7,67.4
Alajärvi,599.7,61.6,185.3,2322.5,3301.0,67.9,-45.0,5437.3,-93.0,2942.5,...,22.3,53.5,29.5,16.9,75.4,11.5,27.2,59.4,4142.8,100.0
Alavieska,783.1,51.6,157.9,2028.2,976.0,73.6,-6.0,4469.2,-27.0,3973.0,...,18.7,54.9,25.7,19.4,45.4,22.4,21.3,54.4,4153.8,72.1
Alavus,456.8,60.8,169.4,1990.8,4206.0,70.7,-70.0,7135.7,-68.0,4029.7,...,19.9,53.9,29.7,16.4,75.8,9.0,21.0,68.5,4354.0,96.4
Asikkala,1072.8,65.0,180.6,1752.7,2872.0,70.4,-72.0,1623.5,27.0,241.3,...,27.0,52.4,34.3,13.3,49.3,8.6,30.7,57.9,3559.3,79.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Äänekoski sub-regional unit,637.0,72.4,191.0,2015.6,7274.0,64.2,-152.0,10496.9,-135.0,4680.4,...,21.0,56.1,29.3,14.6,71.3,4.0,38.5,56.2,4043.6,102.2
Åboland-Turunmaa sub-regional unit,594.6,62.5,151.6,2300.4,8631.0,74.3,-109.0,3541.5,51.0,2708.2,...,32.2,55.3,30.7,13.9,63.2,5.2,25.8,66.5,4001.2,82.6
Åland,516.8,63.8,120.1,2500.5,13689.0,76.5,30.0,2579.2,-53.0,1637.7,...,29.2,60.2,23.4,16.4,48.9,3.5,13.9,79.7,1936.3,102.6
Ålands landsbygd sub-regional unit,352.8,46.0,113.1,2677.1,7675.0,79.4,69.0,534.9,53.0,1202.3,...,25.7,60.5,20.8,18.8,29.7,7.4,21.9,66.3,1729.6,66.5
Ålands skärgård sub-regional unit,304.6,0.0,132.6,2563.8,889.0,76.5,-14.0,0.0,-34.0,2041.1,...,25.5,54.8,33.3,11.8,59.7,14.6,7.4,72.0,2931.8,78.6

In [65]:
[region_names.loc[name,'nimi'] for name in data.index]

['Akaa',
 'Alajärvi',
 'Alavieska',
 'Alavus',
 'Asikkala',
 'Askola',
 'Aura',
 'Brändö',
 'Keski-Suomen maakunta',
 'Keski-Pohjanmaan maakunta',
 'Eckerö',
 'Enonkoski',
 'Enontekiö',
 'Espoo',
 'Etelä-Pirkanmaan seutukunta',
 'Eura',
 'Eurajoki',
 'Evijärvi',
 'Finström',
 'Forssa',
 'Forssan seutukunta',
 'Föglö',
 'Geta',
 'Haapajärvi',
 'Haapavesi',
 'Haapavesi-Siikalatvan seutukunta',
 'Hailuoto',
 'Halsua',
 'Hamina',
 'Hammarland',
 'Hankasalmi',
 'Hanko',
 'Harjavalta',
 'Hartola',
 'Hattula',
 'Hausjärvi',
 'Heinola',
 'Heinävesi',
 'Helsinki',
 'Helsingin seutukunta',
 'Hirvensalmi',
 'Hollola',
 'Huittinen',
 'Humppila',
 'Hyrynsalmi',
 'Hyvinkää',
 'Hämeenkyrö',
 'Hämeenlinna',
 'Hämeenlinnan seutukunta',
 'Ii',
 'Iisalmi',
 'Iitti',
 'Ikaalinen',
 'Ilmajoki',
 'Ilomantsi',
 'Imatra',
 'Imatran seutukunta',
 'Inari',
 'Inkoo',
 'Isojoki',
 'Isokyrö',
 'Itä-Lapin seutukunta',
 'Pietarsaari',
 'Jakobstadsregionen',
 'Janakkala',
 'Joensuu',
 'Joensuun seutukunta',
 'Jokioinen',
 'Jomala',
 'Joroinen',
 'Joutsa',
 'Joutsan seutukunta',
 'Juuka',
 'Juupajoki',
 'Juva',
 'Jyväskylä',
 'Jyväskylän seutukunta',
 'Jämijärvi',
 'Jämsä',
 'Jämsän seutukunta',
 'Järvenpää',
 'Järviseudun seutukunta',
 'Kaarina',
 'Kaavi',
 'Kainuun maakunta',
 'Kajaani',
 'Kajaanin seutukunta',
 'Kalajoki',
 'Kangasala',
 'Kangasniemi',
 'Kankaanpää',
 'Kannonkoski',
 'Kannus',
 'Kanta-Hämeen maakunta',
 'Karijoki',
 'Karkkila',
 'Karstula',
 'Karvia',
 'Kaskinen',
 'Kauhajoki',
 'Kauhava',
 'Kauniainen',
 'Kaustinen',
 'Kaustisen seutukunta',
 'Kehys-Kainuun seutukunta',
 'Keitele',
 'Kemi',
 'Kemi-Tornion seutukunta',
 'Kemijärvi',
 'Keminmaa',
 'Kempele',
 'Kerava',
 'Keski-Karjalan seutukunta',
 'Keuruu',
 'Keuruun seutukunta',
 'Kihniö',
 'Kemiönsaari',
 'Kinnula',
 'Kirkkonummi',
 'Kitee',
 'Kittilä',
 'Kiuruvesi',
 'Kivijärvi',
 'Koillis-Savon seutukunta',
 'Koillismaan seutukunta',
 'Kokemäki',
 'Kokkola',
 'Kokkolan seutukunta',
 'Kolari',
 'Konnevesi',
 'Kontiolahti',
 'Mustasaari',
 'Korsnäs',
 'Koski Tl',
 'Kotka',
 'Kotka-Haminan seutukunta',
 'Kouvola',
 'Kouvolan seutukunta',
 'Kristiinankaupunki',
 'Kruunupyy',
 'Kuhmo',
 'Kuhmoinen',
 'Kumlinge',
 'Kuopio',
 'Kuopion seutukunta',
 'Kuortane',
 'Kurikka',
 'Kustavi',
 'Kuusamo',
 'Kuusiokuntien seutukunta',
 'Kymenlaakson maakunta',
 'Kyyjärvi',
 'Kärkölä',
 'Kärsämäki',
 'Kökar',
 'Lahti',
 'Lahden seutukunta',
 'Laihia',
 'Laitila',
 'Lapinjärvi',
 'Lapinlahti',
 'Lapin maakunta',
 'Lappajärvi',
 'Lappeenranta',
 'Lappeenrannan seutukunta',
 'Lapua',
 'Luoto',
 'Laukaa',
 'Lemi',
 'Lemland',
 'Lempäälä',
 'Leppävirta',
 'Lestijärvi',
 'Lieksa',
 'Lieto',
 'Liminka',
 'Liperi',
 'Lohja',
 'Loimaa',
 'Loimaan seutukunta',
 'Loppi',
 'Lounais-Pirkanmaan seutukunta',
 'Loviisa',
 'Loviisan seutukunta',
 'Luhanka',
 'Lumijoki',
 'Lumparland',
 'Luoteis-Pirkanmaan seutukunta',
 'Luumäki',
 'Maalahti',
 'Maarianhamina',
 'Mariehamns stad',
 'Marttila',
 'Masku',
 'Merijärvi',
 'Merikarvia',
 'Miehikkälä',
 'Mikkeli',
 'Mikkelin seutukunta',
 'Muhos',
 'Multia',
 'Muonio',
 'Muurame',
 'Mynämäki',
 'Myrskylä',
 'Mäntsälä',
 'Mänttä-Vilppula',
 'Mäntyharju',
 'Naantali',
 'Nakkila',
 'Nivala',
 'Nivala-Haapajärven seutukunta',
 'Nokia',
 'Pohjois-Karjalan maakunta',
 'Pohjois-Pohjanmaan maakunta',
 'Pohjois-Savon maakunta',
 'Nousiainen',
 'Nurmes',
 'Nurmijärvi',
 'Uusikaarlepyy',
 'Närpiö',
 'Orimattila',
 'Oripää',
 'Orivesi',
 'Pohjanmaan maakunta',
 'Oulainen',
 'Oulu',
 'Oulun seutukunta',
 'Oulunkaaren seutukunta',
 'Outokumpu',
 'Padasjoki',
 'Paimio',
 'Paltamo',
 'Parainen',
 'Parikkala',
 'Parkano',
 'Pedersören kunta',
 'Pelkosenniemi',
 'Pello',
 'Perho',
 'Pertunmaa',
 'Petäjävesi',
 'Pieksämäki',
 'Pieksämäen seutukunta',
 'Pielavesi',
 'Pielisen Karjalan seutukunta',
 'Pihtipudas',
 'Pirkanmaan maakunta',
 'Pirkkala',
 'Pohjois-Lapin seutukunta',
 'Pohjois-Satakunnan seutukunta',
 'Polvijärvi',
 'Pomarkku',
 'Pori',
 'Porin seutukunta',
 'Pornainen',
 'Porvoo',
 'Porvoon seutukunta',
 'Posio',
 'Pudasjärvi',
 'Pukkila',
 'Punkalaidun',
 'Puolanka',
 'Puumala',
 'Pyhtää',
 'Pyhäjoki',
 'Pyhäjärvi',
 'Pyhäntä',
 'Pyhäranta',
 'Päijät-Hämeen maakunta',
 'Pälkäne',
 'Pöytyä',
 'Raahe',
 'Raahen seutukunta',
 'Raasepori',
 'Raaseporin seutukunta',
 'Raisio',
 'Rantasalmi',
 'Ranua',
 'Rauma',
 'Rauman seutukunta',
 'Rautalampi',
 'Rautavaara',
 'Rautjärvi',
 'Reisjärvi',
 'Riihimäki',
 'Riihimäen seutukunta',
 'Ristijärvi',
 'Rovaniemi',
 'Rovaniemen seutukunta',
 'Ruokolahti',
 'Ruovesi',
 'Rusko',
 'Rääkkylä',
 'Saarijärvi',
 'Saarijärvi-Viitasaaren seutukunta',
 'Salla',
 'Salo',
 'Salon seutukunta',
 'Saltvik',
 'Sastamala',
 'Satakunnan maakunta',
 'Sauvo',
 'Savitaipale',
 'Savonlinna',
 'Savonlinnan seutukunta',
 'Savukoski',
 'Seinäjoki',
 'Seinäjoen seutukunta',
 'Sievi',
 'Siikainen',
 'Siikajoki',
 'Siikalatva',
 'Siilinjärvi',
 'Simo',
 'Sipoo',
 'Sisä-Savon seutukunta',
 'Siuntio',
 'Sodankylä',
 'Soini',
 'Somero',
 'Sonkajärvi',
 'Sotkamo',
 'Sottunga',
 'Etelä-Karjalan maakunta',
 'Etelä-Pohjanmaan maakunta',
 'Etelä-Savon maakunta',
 'Varsinais-Suomen maakunta',
 'Sulkava',
 'Sund',
 'Suomussalmi',
 'Suonenjoki',
 'Suupohjan seutukunta',
 'Sydösterbotten',
 'Sysmä',
 'Säkylä',
 'Taipalsaari',
 'Taivalkoski',
 'Taivassalo',
 'Tammela',
 'Tampere',
 'Tampereen seutukunta',
 'Tervo',
 'Tervola',
 'Teuva',
 'Tohmajärvi',
 'Toholampi',
 'Toivakka',
 'Tornio',
 'Torniolaakson seutukunta',
 'Tunturi-Lapin seutukunta',
 'Turku',
 'Turun seutukunta',
 'Tuusniemi',
 'Tuusula',
 'Tyrnävä',
 'Ulvila',
 'Urjala',
 'Utajärvi',
 'Utsjoki',
 'Uurainen',
 'Uusikaupunki',
 'Uudenmaan maakunta',
 'Vaala',
 'Vaasa',
 'Vaasan seutukunta',
 'Vakka-Suomen seutukunta',
 'Valkeakoski',
 'Vantaa',
 'Varkaus',
 'Varkauden seutukunta',
 'Vehmaa',
 'Vesanto',
 'Vesilahti',
 'Veteli',
 'Vieremä',
 'Vihti',
 'Viitasaari',
 'Vimpeli',
 'Virolahti',
 'Virrat',
 'Vårdö',
 'Vöyri',
 'KOKO MAA',
 'Ylitornio',
 'Ylivieska',
 'Ylivieskan seutukunta',
 'Ylä-Pirkanmaan seutukunta',
 'Ylä-Savon seutukunta',
 'Ylöjärvi',
 'Ypäjä',
 'Ähtäri',
 'Äänekoski',
 'Äänekosken seutukunta',
 'Åboland-Turunmaan seutukunta',
 'Ahvenanmaa',
 'Ålands landsbygd',
 'Ålands skärgård']

In [64]:
region_names = pd.DataFrame(get_region_names()).set_index('name')
region_names

,nimi,namn
name,,
WHOLE COUNTRY,KOKO MAA,HELA LANDET
Akaa,Akaa,Ackas
Alajärvi,Alajärvi,Alajärvi
Alavieska,Alavieska,Alavieska
Alavus,Alavus,Alavo
...,...,...
Tunturi-Lappi sub-regional unit,Tunturi-Lapin seutukunta,Tunturi-Lappi ekon. reg.
Pohjois-Lappi sub-regional unit,Pohjois-Lapin seutukunta,Norra Lapplands ekon. reg.
Mariehamns stad sub-regional unit,Mariehamns stad,Mariehamns stad
Ålands landsbygd sub-regional unit,Ålands landsbygd,Ålands landsbygd
Ålands skärgård sub-regional unit,Ålands skärgård,Ålands skärgård

In [47]:
indicator_names = pd.DataFrame(get_indicator_names()).set_index('id')
indicator_names.index = indicator_names.index.str[1:]
indicator_names

,nimi,namn,name
id,,,
408,"Taajama-aste, %","Tätortsgrad, %","Degree of urbanisation, %"
411,Väkiluku,Folkmängd,Population
476,"Väkiluvun muutos edellisestä vuodesta, %","Förändring i folkmängden från året innan, %","Population change from the previous year, %"
391,"Alle 15-vuotiaiden osuus väestöstä, %","Andelen personer under 15 år av befolkningen, %",Share of persons aged under 15 of the populati...
421,"15-64 -vuotiaiden osuus väestöstä, %","Andelen 15–64-åringar av befolkningen, %",Share of persons aged 15 to 64 of the populati...
478,"Yli 64-vuotiaiden osuus väestöstä, %","Andelen personer över 64 år av befolkningen, %",Share of persons aged over 64 of the populatio...
404,"Ruotsinkielisten osuus väestöstä, %","Andelen svenskspråkiga av befolkningen, %","Share of Swedish-speakers of the population, %"
410,"Ulkomaan kansalaisten osuus väestöstä, %","Andelen utländska medborgare av befolkningen, %","Share of foreign citizens of the population, %"
303,"Syntyneiden enemmyys, henkilöä","Födelseöverskott, personer","Excess of births, persons"
297,"Kuntien välinen muuttovoitto/-tappio, henkilöä",Inflyttningsöverskott/-underskott mellan kommu...,"Intermunicipal migration gain/loss, persons"
302,Perheiden lukumäärä,Antal familjer,Number of families
44,Asuntokuntien lukumäärä,Antal bostadshushåll,Number of household-dwelling units
62,Rivi- ja pientaloissa asuvien asuntokuntien os...,Andelen bostadshushåll som bor i rad- eller sm...,Share of household-dwelling units living in te...
70,"Vuokra-asunnoissa asuvien asuntokuntien osuus, %","Andelen bostadshushåll som bor i hyresbostäder, %",Share of household-dwelling units living in re...
488,Vähintään toisen asteen tutkinnon suorittaneid...,Andelen personer som avlagt examen på minst an...,Share of persons aged 15 or over with at least...
486,Korkea-asteen tutkinnon suorittaneiden osuus 1...,Andelen personer som avlagt examen på högre ni...,Share of persons aged 15 or over with tertiary...
137,Alueella asuvan työllisen työvoiman määrä,Inom området bosatt sysselsatt arbetskraft,Employed labour force resident in the area
140,"Työllisyysaste, %","Relativt sysselsättningstal, %","Employment rate, %"
130,"Asuinkunnassaan työssäkäyvien osuus, %",Andelen personer som arbetar i sin bostadskomm...,Share of persons working in their municipality...
162,"Työttömien osuus työvoimasta, %","Arbetslösas andel av arbetskraften, %",Proportion of the unemployed among the labour ...
78,"Eläkeläisten osuus väestöstä, %","Andelen pensionärer av befolkningen, %","Proportion of pensioners of the population, %"
485,Taloudellinen huoltosuhde,Ekonomisk försörjningskvot,Economic dependency ratio
152,Alueella olevien työpaikkojen lukumäärä,Antalet arbetsplatser i kommunen,Number of workplaces in the area
72,"Alkutuotannon työpaikkojen osuus, %","Andelen arbetsplatser inom primärproduktionen, %","Share of workplaces in primary production, %"
84,"Jalostuksen työpaikkojen osuus, %","Andelen arbetsplatser inom förädling, %","Share of workplaces in secondary production, %"
106,"Palvelujen työpaikkojen osuus, %","Andelen arbetsplatser inom tjänster, %","Share of workplaces in services, %"
151,Työpaikkaomavaraisuus,Arbetsplatssufficiens,Workplace self-sufficiency
499,"Vuosikate, euroa/asukas","Årsbidrag, €/invånare","Annual contribution margin, EUR per capita"
496,"Lainakanta, euroa/asukas","Lånestock, €/invånare","Loan stock, EUR per capita"
495,"Konsernin lainakanta, euroa/asukas","Koncernens årsbidrag, €/invånare","Group loan stock, EUR per capita"
497,"Opetus- ja kulttuuritoiminta yhteensä, nettokä...","Undervisnings- och kulturverksamhet totalt, ne...","Educational and cultural activities, total, op..."
498,"Sosiaali- ja terveystoiminta yhteensä, nettokä...","Social- och hälsovård totalt, nettodriftskostn...","Social and health care activities, total, oper..."

In [49]:
data.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
           dtype='int64', name='dimensions')

In [50]:
payload = {
  "query": [
    {
      "code": "Alue 2021",
      "selection": {
        "filter": "item"
        
      }
    }
  ],
  "response": {
    "format": "json-stat2"
  }
}

In [38]:
def get_data(region_level, lang = 'en'):
    
    name = {'fi':'nimi','sv':'namn','en':'name'}[lang]
    
    # Query url
    url = f"https://pxdata.stat.fi:443/PxWeb/api/v1/{lang}/Kuntien_avainluvut/2021/kuntien_avainluvut_2021_viimeisin.px"
    
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36',
 'Content-Type': 'application/json'}
    
    with open(f'mapbox/assets/{region_level}_payload.json') as f:
        payload = orjson.loads(f.read())
    
    json = requests.post(url, json = payload, headers = headers).json()

    cities = list(json['dimension']['Alue 2021']['category']['label'].values())
    
    dimensions = list(json['dimension']['Tiedot']['category']['label'].values())

    values = json['value']

    cities_df = pd.DataFrame(cities, columns = [name])
    cities_df['index'] = 0
    dimensions_df = pd.DataFrame(dimensions, columns = ['dimensions'])
    dimensions_df['index'] = 0

    data = pd.merge(left = cities_df, right = dimensions_df, on = 'index', how = 'outer').drop('index',axis = 1)
    data['value'] = values
    data = pd.pivot_table(data, values = 'value', index = [name], columns = 'dimensions')
    data = data.reset_index()
    data['region_level'] = region_level
    data = data.set_index('region_level')
    data.index = data.index.astype('category')
    data[name] = data[name].astype('category')
    
    return data
data = get_data('Region','sv')
data

dimensions,namn,"Andelen 15–64-åringar av befolkningen, %, 2021","Andelen arbetsplatser inom förädling, %, 2020","Andelen arbetsplatser inom primärproduktionen, %, 2020","Andelen arbetsplatser inom tjänster, %, 2020","Andelen bostadshushåll som bor i hyresbostäder, %, 2020","Andelen bostadshushåll som bor i rad- eller småhus, %, 2021","Andelen pensionärer av befolkningen, %, 2020","Andelen personer som arbetar i sin bostadskommun, %, 2020","Andelen personer som avlagt examen på högre nivå av befolkningen som fyllt 15 år, %, 2020",...,"Förändring i folkmängden från året innan, %, 2021","Inflyttningsöverskott/-underskott mellan kommunerna, personer, 2021","Inom området bosatt sysselsatt arbetskraft, 2020","Koncernens årsbidrag, €/invånare, 2020","Lånestock, €/invånare, 2020","Relativt sysselsättningstal, %, 2020","Social- och hälsovård totalt, nettodriftskostnader, €/invånare, 2020","Tätortsgrad, %, 2020","Undervisnings- och kulturverksamhet totalt, nettodriftskostnader, €/invånare, 2020","Årsbidrag, €/invånare, 2020"
region_level,,,,,,,,,,,,,,,,,,,,,
Region,Birkalands landskap,62.5,21.7,1.9,74.9,35.5,33.8,25.3,60.4,33.6,...,0.9,3375.0,217568.0,6767.8,3361.6,69.2,3506.1,88.7,2044.5,706.8
Region,Egentliga Finlands landskap,61.5,22.2,2.8,73.5,33.4,37.2,27.0,58.7,32.1,...,0.4,1155.0,199102.0,5268.1,3072.3,69.4,3570.0,85.8,1942.7,532.6
Region,Egentliga Tavastlands landskap,59.0,24.5,3.3,70.9,28.6,45.8,29.5,55.1,28.8,...,-0.2,48.0,69254.0,5446.5,3441.7,71.5,3619.7,82.6,1785.5,609.6
Region,HELA LANDET,61.6,20.5,2.7,75.4,34.4,38.2,26.0,64.9,32.6,...,0.3,0.0,2284673.0,7453.8,3448.4,69.5,3622.3,86.5,2078.8,738.8
Region,Kajanalands landskap,56.6,19.8,5.6,73.7,28.6,50.3,34.3,80.1,25.6,...,-0.6,-277.0,27098.0,12494.3,3503.3,68.5,4787.7,74.7,2407.4,222.2
Region,Kymmenedalens landskap,57.9,21.2,2.4,75.0,29.8,45.7,33.4,76.6,26.5,...,-0.9,-437.0,60838.0,7479.3,4216.3,66.7,4219.6,88.3,2051.9,763.5
Region,Lapplands landskap,58.7,20.3,3.8,74.0,31.8,52.5,30.5,80.7,27.6,...,-0.1,86.0,68369.0,5792.5,3544.7,67.5,4328.3,78.3,2059.2,599.2
Region,Mellersta Finlands landskap,60.7,21.8,3.3,73.5,34.9,40.7,27.3,73.6,30.8,...,0.0,63.0,105045.0,7979.1,3140.6,66.0,3576.0,81.5,1913.2,589.7
Region,Mellersta Österbottens landskap,57.3,22.6,6.4,69.9,26.7,61.2,27.0,80.8,26.2,...,-0.1,-215.0,27352.0,9355.9,5220.0,73.2,3829.7,79.5,2104.1,632.0
Region,Norra Karelens landskap,58.7,21.5,5.3,71.9,32.5,49.1,31.6,71.2,27.0,...,-0.2,-64.0,59372.0,5436.8,2498.9,63.6,3920.0,72.8,1844.1,836.1
Region,Norra Savolax landskap,59.4,19.9,5.7,73.1,33.0,41.7,30.6,74.1,28.9,...,0.0,707.0,96967.0,8233.3,3598.7,67.9,4174.5,76.4,1977.9,551.8
Region,Norra Österbottens landskap,61.0,22.6,4.0,72.3,32.8,46.7,24.1,75.7,30.5,...,0.4,129.0,163920.0,6575.0,4186.2,68.5,3633.8,84.2,2193.1,541.1
Region,Nylands landskap,65.7,16.3,0.5,81.8,40.5,23.7,20.1,57.5,39.7,...,0.7,-2461.0,768692.0,8919.0,3044.4,71.1,3253.4,95.6,2247.3,988.5
Region,Päijänne-Tavastlands landskap,58.2,26.4,2.8,69.3,34.1,36.8,31.0,65.3,27.4,...,-0.3,-63.0,77524.0,7720.4,5478.7,67.1,3586.6,87.4,1886.9,866.6
Region,Satakunta landskap,57.8,27.9,3.5,67.1,27.3,54.2,31.5,68.6,26.5,...,-0.5,-577.0,83472.0,4850.1,2666.5,69.5,3789.4,83.6,1855.4,596.9
Region,Södra Karelens landskap,58.7,22.7,3.1,72.7,31.6,46.2,32.1,73.5,28.0,...,-0.6,-505.0,47467.0,6729.6,3016.4,65.6,4032.2,84.1,1799.0,484.5
Region,Södra Savolax landskap,55.4,19.8,6.3,72.4,29.1,48.4,36.3,83.5,26.4,...,-0.8,-56.0,48568.0,7857.9,4200.9,67.7,4503.1,72.2,1773.1,770.0
Region,Södra Österbottens landskap,57.4,24.6,7.6,66.4,25.3,60.6,29.9,70.7,26.2,...,-0.2,-130.0,76659.0,7992.8,4335.0,72.2,3977.2,73.8,2018.1,581.9
Region,Åland,60.2,13.9,3.5,79.7,27.6,62.9,23.6,48.9,29.2,...,0.7,-53.0,13689.0,2579.2,1637.7,76.5,1936.3,63.8,2500.5,516.8
Region,Österbottens landskap,59.6,29.7,5.2,63.8,28.1,52.4,25.7,66.6,31.7,...,0.1,-725.0,73717.0,7462.7,4218.3,73.2,3634.8,84.6,2381.4,740.5

In [76]:
df = pd.concat([get_data('Region','sv'), get_data('Sub-region','sv'), get_data('Municipality','sv')]).drop_duplicates()
df

dimensions,namn,"Andelen 15–64-åringar av befolkningen, %, 2021","Andelen arbetsplatser inom förädling, %, 2020","Andelen arbetsplatser inom primärproduktionen, %, 2020","Andelen arbetsplatser inom tjänster, %, 2020","Andelen bostadshushåll som bor i hyresbostäder, %, 2020","Andelen bostadshushåll som bor i rad- eller småhus, %, 2021","Andelen pensionärer av befolkningen, %, 2020","Andelen personer som arbetar i sin bostadskommun, %, 2020","Andelen personer som avlagt examen på högre nivå av befolkningen som fyllt 15 år, %, 2020",...,"Förändring i folkmängden från året innan, %, 2021","Inflyttningsöverskott/-underskott mellan kommunerna, personer, 2021","Inom området bosatt sysselsatt arbetskraft, 2020","Koncernens årsbidrag, €/invånare, 2020","Lånestock, €/invånare, 2020","Relativt sysselsättningstal, %, 2020","Social- och hälsovård totalt, nettodriftskostnader, €/invånare, 2020","Tätortsgrad, %, 2020","Undervisnings- och kulturverksamhet totalt, nettodriftskostnader, €/invånare, 2020","Årsbidrag, €/invånare, 2020"
region_level,,,,,,,,,,,,,,,,,,,,,
Region,Birkalands landskap,62.5,21.7,1.9,74.9,35.5,33.8,25.3,60.4,33.6,...,0.9,3375.0,217568.0,6767.8,3361.6,69.2,3506.1,88.7,2044.5,706.8
Region,Egentliga Finlands landskap,61.5,22.2,2.8,73.5,33.4,37.2,27.0,58.7,32.1,...,0.4,1155.0,199102.0,5268.1,3072.3,69.4,3570.0,85.8,1942.7,532.6
Region,Egentliga Tavastlands landskap,59.0,24.5,3.3,70.9,28.6,45.8,29.5,55.1,28.8,...,-0.2,48.0,69254.0,5446.5,3441.7,71.5,3619.7,82.6,1785.5,609.6
Region,HELA LANDET,61.6,20.5,2.7,75.4,34.4,38.2,26.0,64.9,32.6,...,0.3,0.0,2284673.0,7453.8,3448.4,69.5,3622.3,86.5,2078.8,738.8
Region,Kajanalands landskap,56.6,19.8,5.6,73.7,28.6,50.3,34.3,80.1,25.6,...,-0.6,-277.0,27098.0,12494.3,3503.3,68.5,4787.7,74.7,2407.4,222.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Municipality,Ypäjä,58.5,15.6,19.8,60.5,18.9,92.0,32.7,40.4,20.2,...,-1.4,-13.0,963.0,2228.2,1506.1,73.4,3297.8,41.1,1569.6,855.2
Municipality,Äänekoski,56.5,41.7,2.5,54.5,27.9,66.1,32.8,73.2,21.2,...,-1.4,-169.0,6391.0,10195.5,3990.7,63.8,3996.9,76.8,2027.8,596.2
Municipality,Åbo,66.4,14.6,0.4,83.7,49.9,24.4,24.0,75.7,35.8,...,0.4,-174.0,80746.0,7392.8,3666.7,63.9,3654.6,99.1,1954.9,333.9
Municipality,Östermark,51.1,26.6,16.9,54.8,15.7,95.8,38.4,62.3,17.3,...,-0.8,-9.0,1782.0,5568.1,3698.2,71.8,4335.8,66.1,1853.2,903.9
Municipality,Övertorneå,50.2,15.7,11.6,66.5,18.3,93.1,43.5,76.7,19.8,...,-1.5,1.0,1281.0,1970.7,137.3,64.7,5642.2,47.5,1819.3,558.9

In [79]:
df[df.namn.str.contains('HELA LANDET')].namn.values

array(['HELA LANDET'], dtype=object)

In [85]:
data_df = pd.concat([get_data('Region','sv'), get_data('Sub-region','sv'), get_data('Municipality','sv')]).drop_duplicates()
whole_country_df = pd.DataFrame(data_df.set_index('namn').loc['HELA LANDET'].sort_index())
whole_country_df['year'] = [stat.split(', ')[-1] for stat in whole_country_df.index]
whole_country_df['unit'] = [stat.split(', ')[-2] if len(stat.split(', ')) > 2 else '' for stat in whole_country_df.index]
whole_country_df['stat_name'] = [stat.split(', ')[0] if len(stat.split(', ')) < 4 else ', '.join(stat.split(', ')[:2]) for stat in whole_country_df.index]
data_df = data_df[data_df.namn != 'HELA LANDET']

In [88]:
whole_country_df.loc['Andelen 15–64-åringar av befolkningen, %, 2021']['HELA LANDET']

61.6

In [93]:
data_df.head().loc['Region'][['namn', 'Andelen 15–64-åringar av befolkningen, %, 2021']].namn.values

array(['Birkalands landskap', 'Egentliga Finlands landskap',
       'Egentliga Tavastlands landskap', 'Kajanalands landskap',
       'Kymmenedalens landskap'], dtype=object)

In [61]:
df = pd.concat([get_data('Region','fi'), get_data('Sub-region','fi'), get_data('Municipality','fi')])
df[df.duplicated(subset=['nimi'], keep=False)]

dimensions,nimi,"15-64 -vuotiaiden osuus väestöstä, %, 2021","Alkutuotannon työpaikkojen osuus, %, 2020","Alle 15-vuotiaiden osuus väestöstä, %, 2021","Alueella asuvan työllisen työvoiman määrä, 2020","Alueella olevien työpaikkojen lukumäärä, 2020","Asuinkunnassaan työssäkäyvien osuus, %, 2020","Asuntokuntien lukumäärä, 2021","Eläkeläisten osuus väestöstä, %, 2020","Jalostuksen työpaikkojen osuus, %, 2020",...,"Työllisyysaste, %, 2020","Työpaikkaomavaraisuus, 2020","Työttömien osuus työvoimasta, %, 2020","Ulkomaan kansalaisten osuus väestöstä, %, 2021","Vuokra-asunnoissa asuvien asuntokuntien osuus, %, 2020","Vuosikate, euroa/asukas, 2020","Vähintään toisen asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2020","Väkiluku, 2021","Väkiluvun muutos edellisestä vuodesta, %, 2021","Yli 64-vuotiaiden osuus väestöstä, %, 2021"
region_level,,,,,,,,,,,,,,,,,,,,,
Region,KOKO MAA,61.6,2.7,15.4,2284673.0,2284665.0,64.9,2793636.0,26.0,20.5,...,69.5,100.0,13.3,5.3,34.4,738.8,74.2,5548241.0,0.3,23.1
Municipality,KOKO MAA,61.6,2.7,15.4,2284673.0,2284665.0,64.9,2793636.0,26.0,20.5,...,69.5,100.0,13.3,5.3,34.4,738.8,74.2,5548241.0,0.3,23.1

In [42]:
pd.concat([get_data('Region','fi'), get_data('Sub-region','fi'), get_data('Municipality','fi')]).memory_usage(deep='True')

Index                                                                                     27340
nimi                                                                                      30988
15-64 -vuotiaiden osuus väestöstä, %, 2021                                                 3200
Alkutuotannon työpaikkojen osuus, %, 2020                                                  3200
Alle 15-vuotiaiden osuus väestöstä, %, 2021                                                3200
Alueella asuvan työllisen työvoiman määrä, 2020                                            3200
Alueella olevien työpaikkojen lukumäärä, 2020                                              3200
Asuinkunnassaan työssäkäyvien osuus, %, 2020                                               3200
Asuntokuntien lukumäärä, 2021                                                              3200
Eläkeläisten osuus väestöstä, %, 2020                                                      3200
Jalostuksen työpaikkojen osuus, %, 2020                                                    3200
Konsernin lainakanta, euroa/asukas, 2020                                                   3200
Korkea-asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2020               3200
Kuntien välinen muuttovoitto/-tappio, henkilöä, 2021                                       3200
Lainakanta, euroa/asukas, 2020                                                             3200
Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2020         3200
Palvelujen työpaikkojen osuus, %, 2020                                                     3200
Perheiden lukumäärä, 2020                                                                  3200
Rivi- ja pientaloissa asuvien asuntokuntien osuus, %, 2021                                 3200
Ruotsinkielisten osuus väestöstä, %, 2021                                                  3200
Sosiaali- ja terveystoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2020         3200
Syntyneiden enemmyys, henkilöä, 2021                                                       3200
Taajama-aste, %, 2020                                                                      3200
Taloudellinen huoltosuhde, 2020                                                            3200
Työllisyysaste, %, 2020                                                                    3200
Työpaikkaomavaraisuus, 2020                                                                3200
Työttömien osuus työvoimasta, %, 2020                                                      3200
Ulkomaan kansalaisten osuus väestöstä, %, 2021                                             3200
Vuokra-asunnoissa asuvien asuntokuntien osuus, %, 2020                                     3200
Vuosikate, euroa/asukas, 2020                                                              3200
Vähintään toisen asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2020     3200
Väkiluku, 2021                                                                             3200
Väkiluvun muutos edellisestä vuodesta, %, 2021                                             3200
Yli 64-vuotiaiden osuus väestöstä, %, 2021                                                 3200
dtype: int64

In [82]:
data_fin = data.copy()
data_fin.index = [region_names.loc[name,'namn'] for name in data_fin.index]
data_fin.columns = [latest_indicator_names.loc[name,'namn'] for name in data_fin.columns]
data_fin

,"Årsbidrag, €/invånare, 2020","Tätortsgrad, %, 2020","Ekonomisk försörjningskvot, 2020","Undervisnings- och kulturverksamhet totalt, nettodriftskostnader, €/invånare, 2020","Inom området bosatt sysselsatt arbetskraft, 2020","Relativt sysselsättningstal, %, 2020","Födelseöverskott, personer, 2021","Koncernens årsbidrag, €/invånare, 2020","Inflyttningsöverskott/-underskott mellan kommunerna, personer, 2021","Lånestock, €/invånare, 2020",...,"Andelen personer som avlagt examen på högre nivå av befolkningen som fyllt 15 år, %, 2020","Andelen 15–64-åringar av befolkningen, %, 2021","Andelen personer över 64 år av befolkningen, %, 2021","Andelen personer under 15 år av befolkningen, %, 2021","Andelen personer som arbetar i sin bostadskommun, %, 2020","Andelen arbetsplatser inom primärproduktionen, %, 2020","Andelen arbetsplatser inom förädling, %, 2020","Andelen arbetsplatser inom tjänster, %, 2020","Social- och hälsovård totalt, nettodriftskostnader, €/invånare, 2020","Arbetsplatssufficiens, 2020"
Mellersta Finlands landskap,589.7,81.5,159.5,1913.2,105045.0,66.0,-662.0,7979.1,63.0,3140.6,...,30.8,60.7,24.1,15.2,73.6,3.3,21.8,73.5,3576.0,98.3
Mellersta Österbottens landskap,632.0,79.5,148.6,2104.1,27352.0,73.2,-34.0,9355.9,-215.0,5220.0,...,26.2,57.3,24.3,18.4,80.8,6.4,22.6,69.9,3829.7,101.5
Kajanalands landskap,222.2,74.7,164.5,2407.4,27098.0,68.5,-562.0,12494.3,-277.0,3503.3,...,25.6,56.6,29.8,13.6,80.1,5.6,19.8,73.7,4787.7,100.2
Egentliga Tavastlands landskap,609.6,82.6,146.3,1785.5,69254.0,71.5,-738.0,5446.5,48.0,3441.7,...,28.8,59.0,26.4,14.6,55.1,3.3,24.5,70.9,3619.7,90.3
Kymmenedalens landskap,763.5,88.3,167.6,2051.9,60838.0,66.7,-1251.0,7479.3,-437.0,4216.3,...,26.5,57.9,29.2,12.9,76.6,2.4,21.2,75.0,4219.6,98.0
Lapplands landskap,599.2,78.3,158.4,2059.2,68369.0,67.5,-742.0,5792.5,86.0,3544.7,...,27.6,58.7,26.6,14.6,80.7,3.8,20.3,74.0,4328.3,100.0
Norra Karelens landskap,836.1,72.8,175.4,1844.1,59372.0,63.6,-916.0,5436.8,-64.0,2498.9,...,27.0,58.7,27.9,13.4,71.2,5.3,21.5,71.9,3920.0,99.1
Norra Österbottens landskap,541.1,84.2,152.5,2193.1,163920.0,68.5,295.0,6575.0,129.0,4186.2,...,30.5,61.0,20.5,18.5,75.7,4.0,22.6,72.3,3633.8,99.0
Norra Savolax landskap,551.8,76.4,156.0,1977.9,96967.0,67.9,-1179.0,8233.3,707.0,3598.7,...,28.9,59.4,26.4,14.2,74.1,5.7,19.9,73.1,4174.5,98.7
Österbottens landskap,740.5,84.6,138.5,2381.4,73717.0,73.2,-81.0,7462.7,-725.0,4218.3,...,31.7,59.6,23.6,16.8,66.6,5.2,29.7,63.8,3634.8,101.6
Birkalands landskap,706.8,88.7,140.3,2044.5,217568.0,69.2,-401.0,6767.8,3375.0,3361.6,...,33.6,62.5,22.3,15.2,60.4,1.9,21.7,74.9,3506.1,97.4
Päijänne-Tavastlands landskap,866.6,87.4,165.4,1886.9,77524.0,67.1,-1084.0,7720.4,-63.0,5478.7,...,27.4,58.2,27.7,14.0,65.3,2.8,26.4,69.3,3586.6,94.3
Satakunta landskap,596.9,83.6,158.1,1855.4,83472.0,69.5,-1215.0,4850.1,-577.0,2666.5,...,26.5,57.8,28.1,14.1,68.6,3.5,27.9,67.1,3789.4,100.3
Södra Karelens landskap,484.5,84.1,167.4,1799.0,47467.0,65.6,-974.0,6729.6,-505.0,3016.4,...,28.0,58.7,28.5,12.8,73.5,3.1,22.7,72.7,4032.2,97.8
Södra Österbottens landskap,581.9,73.8,150.7,2018.1,76659.0,72.2,-634.0,7992.8,-130.0,4335.0,...,26.2,57.4,26.6,16.1,70.7,7.6,24.6,66.4,3977.2,98.3
Södra Savolax landskap,770.0,72.2,173.2,1773.1,48568.0,67.7,-1248.0,7857.9,-56.0,4200.9,...,26.4,55.4,32.5,12.1,83.5,6.3,19.8,72.4,4503.1,99.5
Egentliga Finlands landskap,532.6,85.8,141.8,1942.7,199102.0,69.4,-926.0,5268.1,1155.0,3072.3,...,32.1,61.5,24.0,14.5,58.7,2.8,22.2,73.5,3570.0,97.3
Nylands landskap,988.5,95.6,121.5,2247.3,768692.0,71.1,4257.0,8919.0,-2461.0,3044.4,...,39.7,65.7,18.1,16.1,57.5,0.5,16.3,81.8,3253.4,103.8
HELA LANDET,738.8,86.5,142.2,2078.8,2284673.0,69.5,-8065.0,7453.8,0.0,3448.4,...,32.6,61.6,23.1,15.4,64.9,2.7,20.5,75.4,3622.3,100.0
Åland,516.8,63.8,120.1,2500.5,13689.0,76.5,30.0,2579.2,-53.0,1637.7,...,29.2,60.2,23.4,16.4,48.9,3.5,13.9,79.7,1936.3,102.6

In [87]:
pd.DataFrame(data_fin.reset_index().to_dict('records')).set_index('index')

,"Årsbidrag, €/invånare, 2020","Tätortsgrad, %, 2020","Ekonomisk försörjningskvot, 2020","Undervisnings- och kulturverksamhet totalt, nettodriftskostnader, €/invånare, 2020","Inom området bosatt sysselsatt arbetskraft, 2020","Relativt sysselsättningstal, %, 2020","Födelseöverskott, personer, 2021","Koncernens årsbidrag, €/invånare, 2020","Inflyttningsöverskott/-underskott mellan kommunerna, personer, 2021","Lånestock, €/invånare, 2020",...,"Andelen personer som avlagt examen på högre nivå av befolkningen som fyllt 15 år, %, 2020","Andelen 15–64-åringar av befolkningen, %, 2021","Andelen personer över 64 år av befolkningen, %, 2021","Andelen personer under 15 år av befolkningen, %, 2021","Andelen personer som arbetar i sin bostadskommun, %, 2020","Andelen arbetsplatser inom primärproduktionen, %, 2020","Andelen arbetsplatser inom förädling, %, 2020","Andelen arbetsplatser inom tjänster, %, 2020","Social- och hälsovård totalt, nettodriftskostnader, €/invånare, 2020","Arbetsplatssufficiens, 2020"
index,,,,,,,,,,,,,,,,,,,,,
Mellersta Finlands landskap,589.7,81.5,159.5,1913.2,105045.0,66.0,-662.0,7979.1,63.0,3140.6,...,30.8,60.7,24.1,15.2,73.6,3.3,21.8,73.5,3576.0,98.3
Mellersta Österbottens landskap,632.0,79.5,148.6,2104.1,27352.0,73.2,-34.0,9355.9,-215.0,5220.0,...,26.2,57.3,24.3,18.4,80.8,6.4,22.6,69.9,3829.7,101.5
Kajanalands landskap,222.2,74.7,164.5,2407.4,27098.0,68.5,-562.0,12494.3,-277.0,3503.3,...,25.6,56.6,29.8,13.6,80.1,5.6,19.8,73.7,4787.7,100.2
Egentliga Tavastlands landskap,609.6,82.6,146.3,1785.5,69254.0,71.5,-738.0,5446.5,48.0,3441.7,...,28.8,59.0,26.4,14.6,55.1,3.3,24.5,70.9,3619.7,90.3
Kymmenedalens landskap,763.5,88.3,167.6,2051.9,60838.0,66.7,-1251.0,7479.3,-437.0,4216.3,...,26.5,57.9,29.2,12.9,76.6,2.4,21.2,75.0,4219.6,98.0
Lapplands landskap,599.2,78.3,158.4,2059.2,68369.0,67.5,-742.0,5792.5,86.0,3544.7,...,27.6,58.7,26.6,14.6,80.7,3.8,20.3,74.0,4328.3,100.0
Norra Karelens landskap,836.1,72.8,175.4,1844.1,59372.0,63.6,-916.0,5436.8,-64.0,2498.9,...,27.0,58.7,27.9,13.4,71.2,5.3,21.5,71.9,3920.0,99.1
Norra Österbottens landskap,541.1,84.2,152.5,2193.1,163920.0,68.5,295.0,6575.0,129.0,4186.2,...,30.5,61.0,20.5,18.5,75.7,4.0,22.6,72.3,3633.8,99.0
Norra Savolax landskap,551.8,76.4,156.0,1977.9,96967.0,67.9,-1179.0,8233.3,707.0,3598.7,...,28.9,59.4,26.4,14.2,74.1,5.7,19.9,73.1,4174.5,98.7
Österbottens landskap,740.5,84.6,138.5,2381.4,73717.0,73.2,-81.0,7462.7,-725.0,4218.3,...,31.7,59.6,23.6,16.8,66.6,5.2,29.7,63.8,3634.8,101.6
Birkalands landskap,706.8,88.7,140.3,2044.5,217568.0,69.2,-401.0,6767.8,3375.0,3361.6,...,33.6,62.5,22.3,15.2,60.4,1.9,21.7,74.9,3506.1,97.4
Päijänne-Tavastlands landskap,866.6,87.4,165.4,1886.9,77524.0,67.1,-1084.0,7720.4,-63.0,5478.7,...,27.4,58.2,27.7,14.0,65.3,2.8,26.4,69.3,3586.6,94.3
Satakunta landskap,596.9,83.6,158.1,1855.4,83472.0,69.5,-1215.0,4850.1,-577.0,2666.5,...,26.5,57.8,28.1,14.1,68.6,3.5,27.9,67.1,3789.4,100.3
Södra Karelens landskap,484.5,84.1,167.4,1799.0,47467.0,65.6,-974.0,6729.6,-505.0,3016.4,...,28.0,58.7,28.5,12.8,73.5,3.1,22.7,72.7,4032.2,97.8
Södra Österbottens landskap,581.9,73.8,150.7,2018.1,76659.0,72.2,-634.0,7992.8,-130.0,4335.0,...,26.2,57.4,26.6,16.1,70.7,7.6,24.6,66.4,3977.2,98.3
Södra Savolax landskap,770.0,72.2,173.2,1773.1,48568.0,67.7,-1248.0,7857.9,-56.0,4200.9,...,26.4,55.4,32.5,12.1,83.5,6.3,19.8,72.4,4503.1,99.5
Egentliga Finlands landskap,532.6,85.8,141.8,1942.7,199102.0,69.4,-926.0,5268.1,1155.0,3072.3,...,32.1,61.5,24.0,14.5,58.7,2.8,22.2,73.5,3570.0,97.3
Nylands landskap,988.5,95.6,121.5,2247.3,768692.0,71.1,4257.0,8919.0,-2461.0,3044.4,...,39.7,65.7,18.1,16.1,57.5,0.5,16.3,81.8,3253.4,103.8
HELA LANDET,738.8,86.5,142.2,2078.8,2284673.0,69.5,-8065.0,7453.8,0.0,3448.4,...,32.6,61.6,23.1,15.4,64.9,2.7,20.5,75.4,3622.3,100.0
Åland,516.8,63.8,120.1,2500.5,13689.0,76.5,30.0,2579.2,-53.0,1637.7,...,29.2,60.2,23.4,16.4,48.9,3.5,13.9,79.7,1936.3,102.6

In [78]:
latest_indicator_names = get_latest_indicator_names()

In [79]:
latest_indicator_names

,nimi,namn
name,,
"Degree of urbanisation, %, 2020","Taajama-aste, %, 2020","Tätortsgrad, %, 2020"
"Population, 2021","Väkiluku, 2021","Folkmängd, 2021"
"Population change from the previous year, %, 2021","Väkiluvun muutos edellisestä vuodesta, %, 2021","Förändring i folkmängden från året innan, %, 2021"
"Share of persons aged under 15 of the population, %, 2021","Alle 15-vuotiaiden osuus väestöstä, %, 2021","Andelen personer under 15 år av befolkningen, ..."
"Share of persons aged 15 to 64 of the population, %, 2021","15-64 -vuotiaiden osuus väestöstä, %, 2021","Andelen 15–64-åringar av befolkningen, %, 2021"
"Share of persons aged over 64 of the population, %, 2021","Yli 64-vuotiaiden osuus väestöstä, %, 2021","Andelen personer över 64 år av befolkningen, %..."
"Share of Swedish-speakers of the population, %, 2021","Ruotsinkielisten osuus väestöstä, %, 2021","Andelen svenskspråkiga av befolkningen, %, 2021"
"Share of foreign citizens of the population, %, 2021","Ulkomaan kansalaisten osuus väestöstä, %, 2021","Andelen utländska medborgare av befolkningen, ..."
"Excess of births, persons, 2021","Syntyneiden enemmyys, henkilöä, 2021","Födelseöverskott, personer, 2021"
"Intermunicipal migration gain/loss, persons, 2021","Kuntien välinen muuttovoitto/-tappio, henkilöä...",Inflyttningsöverskott/-underskott mellan kommu...
"Number of families, 2020","Perheiden lukumäärä, 2020","Antal familjer, 2020"
"Number of household-dwelling units, 2021","Asuntokuntien lukumäärä, 2021","Antal bostadshushåll, 2021"
"Share of household-dwelling units living in terraced houses and detached houses, %, 2021",Rivi- ja pientaloissa asuvien asuntokuntien os...,Andelen bostadshushåll som bor i rad- eller sm...
"Share of household-dwelling units living in rental dwellings, %, 2020","Vuokra-asunnoissa asuvien asuntokuntien osuus,...",Andelen bostadshushåll som bor i hyresbostäder...
"Share of persons aged 15 or over with at least upper secondary qualifications, %, 2020",Vähintään toisen asteen tutkinnon suorittaneid...,Andelen personer som avlagt examen på minst an...
"Share of persons aged 15 or over with tertiary level qualifications, %, 2020",Korkea-asteen tutkinnon suorittaneiden osuus 1...,Andelen personer som avlagt examen på högre ni...
"Employed labour force resident in the area, 2020","Alueella asuvan työllisen työvoiman määrä, 2020","Inom området bosatt sysselsatt arbetskraft, 2020"
"Employment rate, %, 2020","Työllisyysaste, %, 2020","Relativt sysselsättningstal, %, 2020"
"Share of persons working in their municipality of residence, %, 2020","Asuinkunnassaan työssäkäyvien osuus, %, 2020",Andelen personer som arbetar i sin bostadskomm...
"Proportion of the unemployed among the labour force, %, 2020","Työttömien osuus työvoimasta, %, 2020","Arbetslösas andel av arbetskraften, %, 2020"
"Proportion of pensioners of the population, %, 2020","Eläkeläisten osuus väestöstä, %, 2020","Andelen pensionärer av befolkningen, %, 2020"
"Economic dependency ratio, 2020","Taloudellinen huoltosuhde, 2020","Ekonomisk försörjningskvot, 2020"
"Number of workplaces in the area, 2020","Alueella olevien työpaikkojen lukumäärä, 2020","Antalet arbetsplatser i kommunen, 2020"
"Share of workplaces in primary production, %, 2020","Alkutuotannon työpaikkojen osuus, %, 2020","Andelen arbetsplatser inom primärproduktionen,..."
"Share of workplaces in secondary production, %, 2020","Jalostuksen työpaikkojen osuus, %, 2020","Andelen arbetsplatser inom förädling, %, 2020"
"Share of workplaces in services, %, 2020","Palvelujen työpaikkojen osuus, %, 2020","Andelen arbetsplatser inom tjänster, %, 2020"
"Workplace self-sufficiency, 2020","Työpaikkaomavaraisuus, 2020","Arbetsplatssufficiens, 2020"
"Annual contribution margin, EUR per capita, 2020","Vuosikate, euroa/asukas, 2020","Årsbidrag, €/invånare, 2020"
"Loan stock, EUR per capita, 2020","Lainakanta, euroa/asukas, 2020","Lånestock, €/invånare, 2020"
"Group loan stock, EUR per capita, 2020","Konsernin lainakanta, euroa/asukas, 2020","Koncernens årsbidrag, €/invånare, 2020"
"Educational and cultural activities, total, operating net costs, EUR per capita, 2020","Opetus- ja kulttuuritoiminta yhteensä, nettokä...","Undervisnings- och kulturverksamhet totalt, ne..."
"Social and health care activities, total, operating net costs, EUR per capita, 2020","Sosiaali- ja terveystoiminta yhteensä, nettokä...","Social- och hälsovård totalt, nettodriftskostn..."

In [93]:
whole_country_df = pd.DataFrame(data.loc['WHOLE COUNTRY'])
whole_country_df.columns = ['KOKO MAA']
pd.DataFrame(whole_country_df.reset_index().to_dict('records')).set_index('dimensions')

                                                     KOKO MAA
dimensions
Annual contribution margin, EUR per capita, 2020        738.8
Degree of urbanisation, %, 2020                          86.5
Economic dependency ratio, 2020                         142.2
Educational and cultural activities, total, ope...     2078.8
Employed labour force resident in the area, 2020    2284673.0
Employment rate, %, 2020                                 69.5
Excess of births, persons, 2021                       -8065.0
Group loan stock, EUR per capita, 2020                 7453.8
Intermunicipal migration gain/loss, persons, 2021         0.0
Loan stock, EUR per capita, 2020                       3448.4
Number of families, 2020                            1467653.0
Number of household-dwelling units, 2021            2793636.0
Number of workplaces in the area, 2020              2284665.0
Population change from the previous year, %, 2021         0.3
Population, 2021                                    5548241.0
Proportion of pensioners of the population, %, ...       26.0
Proportion of the unemployed among the labour f...       13.3
Share of Swedish-speakers of the population, %,...        5.2
Share of foreign citizens of the population, %,...        5.3
Share of household-dwelling units living in ren...       34.4
Share of household-dwelling units living in ter...       38.2
Share of persons aged 15 or over with at least ...       74.2
Share of persons aged 15 or over with tertiary ...       32.6
Share of persons aged 15 to 64 of the populatio...       61.6
Share of persons aged over 64 of the population...       23.1
Share of persons aged under 15 of the populatio...       15.4
Share of persons working in their municipality ...       64.9
Share of workplaces in primary production, %, 2020        2.7
Share of workplaces in secondary production, %,...       20.5
Share of workplaces in services, %, 2020                 75.4
Social and health care activities, total, opera...     3622.3
Workplace self-sufficiency, 2020                        100.0

In [62]:
mun_series_payload = {
  "query": [
    {
      "code": "Alue 2021",
      "selection": {
        "filter": "item",
        "values": [
          "020",
          "005",
          "009",
          "010",
          "016",
          "018",
          "019",
          "035",
          "043",
          "046",
          "047",
          "049",
          "050",
          "051",
          "052",
          "060",
          "061",
          "062",
          "065",
          "069",
          "071",
          "072",
          "074",
          "075",
          "076",
          "077",
          "078",
          "079",
          "081",
          "082",
          "086",
          "111",
          "090",
          "091",
          "097",
          "098",
          "102",
          "103",
          "105",
          "106",
          "108",
          "109",
          "139",
          "140",
          "142",
          "143",
          "145",
          "146",
          "153",
          "148",
          "149",
          "151",
          "152",
          "165",
          "167",
          "169",
          "170",
          "171",
          "172",
          "176",
          "177",
          "178",
          "179",
          "181",
          "182",
          "186",
          "202",
          "204",
          "205",
          "208",
          "211",
          "213",
          "214",
          "216",
          "217",
          "218",
          "224",
          "226",
          "230",
          "231",
          "232",
          "233",
          "235",
          "236",
          "239",
          "240",
          "320",
          "241",
          "322",
          "244",
          "245",
          "249",
          "250",
          "256",
          "257",
          "260",
          "261",
          "263",
          "265",
          "271",
          "272",
          "273",
          "275",
          "276",
          "280",
          "284",
          "285",
          "286",
          "287",
          "288",
          "290",
          "291",
          "295",
          "297",
          "300",
          "301",
          "304",
          "305",
          "312",
          "316",
          "317",
          "318",
          "398",
          "399",
          "400",
          "407",
          "402",
          "403",
          "405",
          "408",
          "410",
          "416",
          "417",
          "418",
          "420",
          "421",
          "422",
          "423",
          "425",
          "426",
          "444",
          "430",
          "433",
          "434",
          "435",
          "436",
          "438",
          "440",
          "441",
          "475",
          "478",
          "480",
          "481",
          "483",
          "484",
          "489",
          "491",
          "494",
          "495",
          "498",
          "499",
          "500",
          "503",
          "504",
          "505",
          "508",
          "507",
          "529",
          "531",
          "535",
          "536",
          "538",
          "541",
          "543",
          "545",
          "560",
          "561",
          "562",
          "563",
          "564",
          "309",
          "576",
          "577",
          "578",
          "445",
          "580",
          "581",
          "599",
          "583",
          "854",
          "584",
          "588",
          "592",
          "593",
          "595",
          "598",
          "601",
          "604",
          "607",
          "608",
          "609",
          "611",
          "638",
          "614",
          "615",
          "616",
          "619",
          "620",
          "623",
          "624",
          "625",
          "626",
          "630",
          "631",
          "635",
          "636",
          "678",
          "710",
          "680",
          "681",
          "683",
          "684",
          "686",
          "687",
          "689",
          "691",
          "694",
          "697",
          "698",
          "700",
          "702",
          "704",
          "707",
          "729",
          "732",
          "734",
          "736",
          "790",
          "738",
          "739",
          "740",
          "742",
          "743",
          "746",
          "747",
          "748",
          "791",
          "749",
          "751",
          "753",
          "755",
          "758",
          "759",
          "761",
          "762",
          "765",
          "766",
          "768",
          "771",
          "777",
          "778",
          "781",
          "783",
          "831",
          "832",
          "833",
          "834",
          "837",
          "844",
          "845",
          "846",
          "848",
          "849",
          "850",
          "851",
          "853",
          "857",
          "858",
          "859",
          "886",
          "887",
          "889",
          "890",
          "892",
          "893",
          "895",
          "785",
          "905",
          "908",
          "092",
          "915",
          "918",
          "921",
          "922",
          "924",
          "925",
          "927",
          "931",
          "934",
          "935",
          "936",
          "941",
          "946",
          "976",
          "977",
          "980",
          "981",
          "989",
          "992"
        ]
      }
    },
    {
      "code": "Vuosi",
      "selection": {
        "filter": "item"
      }
    }
  ],
  "response": {
    "format": "json-stat2"
  }
}

# Region timeseries body
reg_series_payload = {
  "query": [
    {
      "code": "Alue 2021",
      "selection": {
        "filter": "item",
        "values": [
          "SSS",
          "MK01",
          "MK02",
          "MK04",
          "MK05",
          "MK06",
          "MK07",
          "MK08",
          "MK09",
          "MK10",
          "MK11",
          "MK12",
          "MK13",
          "MK14",
          "MK15",
          "MK16",
          "MK17",
          "MK18",
          "MK19",
          "MK21"
        ]
      }
    }
  ],
  "response": {
    "format": "json-stat2"
  }
}
# Sub-region timeseries body
subreg_series_payload = {
  "query": [
    {
      "code": "Alue 2021",
      "selection": {
        "filter": "item",
        "values": [
          "SK011",
          "SK014",
          "SK015",
          "SK016",
          "SK021",
          "SK022",
          "SK023",
          "SK024",
          "SK025",
          "SK041",
          "SK043",
          "SK044",
          "SK051",
          "SK052",
          "SK053",
          "SK061",
          "SK063",
          "SK064",
          "SK068",
          "SK069",
          "SK071",
          "SK081",
          "SK082",
          "SK091",
          "SK093",
          "SK101",
          "SK103",
          "SK105",
          "SK111",
          "SK112",
          "SK113",
          "SK114",
          "SK115",
          "SK122",
          "SK124",
          "SK125",
          "SK131",
          "SK132",
          "SK133",
          "SK134",
          "SK135",
          "SK138",
          "SK141",
          "SK142",
          "SK144",
          "SK146",
          "SK152",
          "SK153",
          "SK154",
          "SK161",
          "SK162",
          "SK171",
          "SK173",
          "SK174",
          "SK175",
          "SK176",
          "SK177",
          "SK178",
          "SK181",
          "SK182",
          "SK191",
          "SK192",
          "SK193",
          "SK194",
          "SK196",
          "SK197",
          "SK211",
          "SK212",
          "SK213"
        ]
      }
    }
  ],
  "response": {
    "format": "json-stat2"
  }
}

time_series_queries = {'Region':reg_series_payload,
           'Sub-region':subreg_series_payload,
            'Municipality':mun_series_payload
           }

def get_timeseries_data(region_level, split = 3):
    
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36',
 'Content-Type': 'application/json'}
    
    with open(f'mapbox/assets/{region_level}_series_payload.json') as f:
        payload = orjson.loads(f.read())
    
    series_url = "https://pxdata.stat.fi:443/PxWeb/api/v1/en/Kuntien_avainluvut/2021/kuntien_avainluvut_2021_aikasarja.px"
    
    if region_level == 'Municipality':
        
        year_lists = np.array_split([str(c) for c in requests.get(series_url, headers = headers).json()['variables'][-1]['values']], split)
        
        dfs = []
        
        for year_list in year_lists:
            payload['query'][-1]['selection'] = {'filter': 'item', 'values': list(year_list)}
            
            json = requests.post(series_url, json = payload, headers = headers).json()
            cities = list(json['dimension']['Alue 2021']['category']['label'].keys())
    
            dimensions = list(json['dimension']['Tiedot']['category']['label'].keys())
            years = list(json['dimension']['Vuosi']['category']['label'].values())
            
            values = json['value']

            cities_df = pd.DataFrame(cities, columns = ['Region'])
            cities_df['Region'] = cities_df['Region'].astype('category')
            cities_df['index'] = 0
            dimensions_df = pd.DataFrame(dimensions, columns = ['dimensions'])
            dimensions_df['dimensions'] = dimensions_df['dimensions'].astype('category')
            dimensions_df['index'] = 0
            years_df = pd.DataFrame(years, columns = ['Year'])
            years_df['Year'] = years_df['Year'].astype('category')
            years_df['index'] = 0

            data = pd.merge(left = pd.merge(left = cities_df, right = dimensions_df, on = 'index', how = 'outer'),
                            right = years_df, how = 'outer', on = 'index').drop('index',axis = 1)

            data['value'] = values
            dfs.append(data.set_index('Region'))
        data = pd.concat(dfs)
        data.dropna(axis=0,inplace=True)
        return data

        
    else:
    
        json = requests.post(series_url, json = payload, headers = headers).json()
        


        cities = list(json['dimension']['Alue 2021']['category']['label'].keys())

        dimensions = list(json['dimension']['Tiedot']['category']['label'].keys())
        years = list(json['dimension']['Vuosi']['category']['label'].values())



        values = json['value']

        cities_df = pd.DataFrame(cities, columns = ['Region'])
        cities_df['Region'] = cities_df['Region'].astype('category')
        cities_df['index'] = 0
        dimensions_df = pd.DataFrame(dimensions, columns = ['dimensions'])
        dimensions_df['dimensions'] = dimensions_df['dimensions'].astype('category')
        dimensions_df['index'] = 0
        years_df = pd.DataFrame(years, columns = ['Year'])
        years_df['Year'] = years_df['Year'].astype('category')
        years_df['index'] = 0

        data = pd.merge(left = pd.merge(left = cities_df, right = dimensions_df, on = 'index', how = 'outer'),
                        right = years_df, how = 'outer', on = 'index').drop('index',axis = 1)

        data['value'] = values
        data.dropna(axis=0,inplace=True)
    
        return data.set_index('Region')
get_timeseries_data('Municipality')

       dimensions  Year   value
Region
020          M408  1987    85.2
020          M408  1988    85.1
020          M408  1989    85.2
020          M408  1990    86.0
020          M408  1991    85.5
...           ...   ...     ...
992          M498  2016  3543.1
992          M498  2017  3498.9
992          M498  2018  3536.3
992          M498  2019  3652.4
992          M498  2020  3996.9

[254925 rows x 3 columns]

In [45]:
df = get_timeseries_data('Region')
df

       dimensions  Year   value
Region
SSS          M408  1987    77.7
SSS          M408  1988    77.7
SSS          M408  1989    78.1
SSS          M408  1990    80.6
SSS          M408  1991    80.7
...           ...   ...     ...
MK21         M498  2016  1827.9
MK21         M498  2017  1747.5
MK21         M498  2018  1824.0
MK21         M498  2019  1905.9
MK21         M498  2020  1936.3

[16500 rows x 3 columns]

In [46]:
df.memory_usage(deep=True)

Index          18275
dimensions     19518
Year           19707
value         132000
dtype: int64

In [155]:
reg_names[reg_names.id=='SK68']

Empty DataFrame
Columns: [id, nimi, namn, name]
Index: []

In [3]:
def get_series_indicator_names():
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36',
 'Content-Type': 'application/json'}
    df = None
    for lang in ['fi','sv','en']:
        url = f"https://pxdata.stat.fi:443/PxWeb/api/v1/{lang}/Kuntien_avainluvut/2021/kuntien_avainluvut_2021_aikasarja.px"
        json = requests.get(url, headers=headers).json()
        dff = pd.DataFrame([{'id':i, {'fi':'nimi','sv':'namn','en':'name'}[lang]:name} for i,name in zip(json['variables'][1]['values'],json['variables'][1]['valueTexts'])])
        if df is None:
            df = dff
        else:
            df = pd.merge(left = df, right = dff, on = 'id', how = 'inner')
    df = df.astype({'id':'category','nimi':'category', 'namn':'category', 'name':'category'})
    return df.set_index('id')
series_indicator_names= get_series_indicator_names()
series_indicator_names

,nimi,namn,name
id,,,
M408,"Taajama-aste, %","Tätortsgrad, %","Degree of urbanisation, %"
M411,Väkiluku,Folkmängd,Population
M476,"Väkiluvun muutos edellisestä vuodesta, %","Förändring i folkmängden från året innan, %","Population change from the previous year, %"
M391,"Alle 15-vuotiaiden osuus väestöstä, %","Andelen personer under 15 år av befolkningen, %",Share of persons aged under 15 of the populati...
M421,"15-64 -vuotiaiden osuus väestöstä, %","Andelen 15–64-åringar av befolkningen, %",Share of persons aged 15 to 64 of the populati...
M478,"Yli 64-vuotiaiden osuus väestöstä, %","Andelen personer över 64 år av befolkningen, %",Share of persons aged over 64 of the populatio...
M404,"Ruotsinkielisten osuus väestöstä, %","Andelen svenskspråkiga av befolkningen, %","Share of Swedish-speakers of the population, %"
M410,"Ulkomaan kansalaisten osuus väestöstä, %","Andelen utländska medborgare av befolkningen, %","Share of foreign citizens of the population, %"
M303,"Syntyneiden enemmyys, henkilöä","Födelseöverskott, personer","Excess of births, persons"
M297,"Kuntien välinen muuttovoitto/-tappio, henkilöä",Inflyttningsöverskott/-underskott mellan kommu...,"Intermunicipal migration gain/loss, persons"
M302,Perheiden lukumäärä,Antal familjer,Number of families
M44,Asuntokuntien lukumäärä,Antal bostadshushåll,Number of household-dwelling units
M62,Rivi- ja pientaloissa asuvien asuntokuntien os...,Andelen bostadshushåll som bor i rad- eller sm...,Share of household-dwelling units living in te...
M70,"Vuokra-asunnoissa asuvien asuntokuntien osuus, %","Andelen bostadshushåll som bor i hyresbostäder, %",Share of household-dwelling units living in re...
M488,Vähintään toisen asteen tutkinnon suorittaneid...,Andelen personer som avlagt examen på minst an...,Share of persons aged 15 or over with at least...
M486,Korkea-asteen tutkinnon suorittaneiden osuus 1...,Andelen personer som avlagt examen på högre ni...,Share of persons aged 15 or over with tertiary...
M137,Alueella asuvan työllisen työvoiman määrä,Inom området bosatt sysselsatt arbetskraft,Employed labour force resident in the area
M140,"Työllisyysaste, %","Relativt sysselsättningstal, %","Employment rate, %"
M130,"Asuinkunnassaan työssäkäyvien osuus, %",Andelen personer som arbetar i sin bostadskomm...,Share of persons working in their municipality...
M162,"Työttömien osuus työvoimasta, %","Arbetslösas andel av arbetskraften, %",Proportion of the unemployed among the labour ...
M78,"Eläkeläisten osuus väestöstä, %","Andelen pensionärer av befolkningen, %","Proportion of pensioners of the population, %"
M485,Taloudellinen huoltosuhde,Ekonomisk försörjningskvot,Economic dependency ratio
M152,Alueella olevien työpaikkojen lukumäärä,Antalet arbetsplatser i kommunen,Number of workplaces in the area
M72,"Alkutuotannon työpaikkojen osuus, %","Andelen arbetsplatser inom primärproduktionen, %","Share of workplaces in primary production, %"
M84,"Jalostuksen työpaikkojen osuus, %","Andelen arbetsplatser inom förädling, %","Share of workplaces in secondary production, %"
M106,"Palvelujen työpaikkojen osuus, %","Andelen arbetsplatser inom tjänster, %","Share of workplaces in services, %"
M151,Työpaikkaomavaraisuus,Arbetsplatssufficiens,Workplace self-sufficiency
M499,"Vuosikate, euroa/asukas","Årsbidrag, €/invånare","Annual contribution margin, EUR per capita"
M496,"Lainakanta, euroa/asukas","Lånestock, €/invånare","Loan stock, EUR per capita"
M495,"Konsernin lainakanta, euroa/asukas","Koncernens årsbidrag, €/invånare","Group loan stock, EUR per capita"
M497,"Opetus- ja kulttuuritoiminta yhteensä, nettokä...","Undervisnings- och kulturverksamhet totalt, ne...","Educational and cultural activities, total, op..."
M498,"Sosiaali- ja terveystoiminta yhteensä, nettokä...","Social- och hälsovård totalt, nettodriftskostn...","Social and health care activities, total, oper..."

In [114]:
df_fi = df.copy()

df_fi['dimensions'] = [series_indicator_names.loc[name,'nimi'] for name in df_fi['dimensions']]
df_fi.index = [region_names.loc[name, 'nimi'] for name in df_fi.index]
df_fi

                                                   dimensions  Year   value
KOKO MAA                                      Taajama-aste, %  1987    77.7
KOKO MAA                                      Taajama-aste, %  1988    77.7
KOKO MAA                                      Taajama-aste, %  1989    78.1
KOKO MAA                                      Taajama-aste, %  1990    80.6
KOKO MAA                                      Taajama-aste, %  1991    80.7
...                                                       ...   ...     ...
Ahvenanmaa  Sosiaali- ja terveystoiminta yhteensä, nettokä...  2016  1827.9
Ahvenanmaa  Sosiaali- ja terveystoiminta yhteensä, nettokä...  2017  1747.5
Ahvenanmaa  Sosiaali- ja terveystoiminta yhteensä, nettokä...  2018  1824.0
Ahvenanmaa  Sosiaali- ja terveystoiminta yhteensä, nettokä...  2019  1905.9
Ahvenanmaa  Sosiaali- ja terveystoiminta yhteensä, nettokä...  2020  1936.3

[16500 rows x 3 columns]

In [120]:
regions_series_data = get_timeseries_data('Region')
regions_series_data.head()

                              dimensions  Year  value
Region
WHOLE COUNTRY  Degree of urbanisation, %  1987   77.7
WHOLE COUNTRY  Degree of urbanisation, %  1988   77.7
WHOLE COUNTRY  Degree of urbanisation, %  1989   78.1
WHOLE COUNTRY  Degree of urbanisation, %  1990   80.6
WHOLE COUNTRY  Degree of urbanisation, %  1991   80.7

In [121]:
whole_country_series_df = regions_series_data.loc['WHOLE COUNTRY']

regions_series_data.drop('WHOLE COUNTRY', axis=0, inplace = True)

whole_country_series_df

                                                      dimensions  Year   value
Region
WHOLE COUNTRY                          Degree of urbanisation, %  1987    77.7
WHOLE COUNTRY                          Degree of urbanisation, %  1988    77.7
WHOLE COUNTRY                          Degree of urbanisation, %  1989    78.1
WHOLE COUNTRY                          Degree of urbanisation, %  1990    80.6
WHOLE COUNTRY                          Degree of urbanisation, %  1991    80.7
...                                                          ...   ...     ...
WHOLE COUNTRY  Social and health care activities, total, oper...  2016  3256.6
WHOLE COUNTRY  Social and health care activities, total, oper...  2017  3226.6
WHOLE COUNTRY  Social and health care activities, total, oper...  2018  3318.5
WHOLE COUNTRY  Social and health care activities, total, oper...  2019  3481.7
WHOLE COUNTRY  Social and health care activities, total, oper...  2020  3622.3

[825 rows x 3 columns]

In [122]:
regions_series_data

                                                dimensions  Year   value
Region
Uusimaa                          Degree of urbanisation, %  1987    92.4
Uusimaa                          Degree of urbanisation, %  1988    92.1
Uusimaa                          Degree of urbanisation, %  1989    92.3
Uusimaa                          Degree of urbanisation, %  1990    93.6
Uusimaa                          Degree of urbanisation, %  1991    93.6
...                                                    ...   ...     ...
Åland    Social and health care activities, total, oper...  2016  1827.9
Åland    Social and health care activities, total, oper...  2017  1747.5
Åland    Social and health care activities, total, oper...  2018  1824.0
Åland    Social and health care activities, total, oper...  2019  1905.9
Åland    Social and health care activities, total, oper...  2020  1936.3

[15675 rows x 3 columns]

In [127]:
regions_series_data_fi = regions_series_data.copy().rename(columns = {'Year':'Vuosi'})
regions_series_data_fi.index = [region_names.loc[name, 'nimi'] for name in regions_series_data_fi.index]
regions_series_data_fi['dimensions'] = [series_indicator_names.loc[name,'nimi'] for name in regions_series_data_fi['dimensions']]
regions_series_data_fi

,dimensions,Vuosi,value
Uudenmaan maakunta,"Taajama-aste, %",1987,92.4
Uudenmaan maakunta,"Taajama-aste, %",1988,92.1
Uudenmaan maakunta,"Taajama-aste, %",1989,92.3
Uudenmaan maakunta,"Taajama-aste, %",1990,93.6
Uudenmaan maakunta,"Taajama-aste, %",1991,93.6
...,...,...,...
Ahvenanmaa,"Sosiaali- ja terveystoiminta yhteensä, nettokä...",2016,1827.9
Ahvenanmaa,"Sosiaali- ja terveystoiminta yhteensä, nettokä...",2017,1747.5
Ahvenanmaa,"Sosiaali- ja terveystoiminta yhteensä, nettokä...",2018,1824.0
Ahvenanmaa,"Sosiaali- ja terveystoiminta yhteensä, nettokä...",2019,1905.9
Ahvenanmaa,"Sosiaali- ja terveystoiminta yhteensä, nettokä...",2020,1936.3

In [125]:
regions_series_data_fi

['Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Uudenmaan maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',
 'Varsinais-Suomen maakunta',

In [133]:

whole_country_series_df_fi = whole_country_series_df.copy().rename(columns = {'Year':'Vuosi'})
whole_country_series_df_fi.index.name = 'KOKO MAA'
whole_country_series_df_fi.index= whole_country_series_df_fi.index.str.replace('WHOLE COUNTRY', 'KOKO MAA')
whole_country_series_df_fi['dimensions'] = [series_indicator_names.loc[name,'nimi'] for name in whole_country_series_df_fi['dimensions']]
whole_country_series_df_fi

                                                 dimensions  Vuosi   value
KOKO MAA
KOKO MAA                                    Taajama-aste, %   1987    77.7
KOKO MAA                                    Taajama-aste, %   1988    77.7
KOKO MAA                                    Taajama-aste, %   1989    78.1
KOKO MAA                                    Taajama-aste, %   1990    80.6
KOKO MAA                                    Taajama-aste, %   1991    80.7
...                                                     ...    ...     ...
KOKO MAA  Sosiaali- ja terveystoiminta yhteensä, nettokä...   2016  3256.6
KOKO MAA  Sosiaali- ja terveystoiminta yhteensä, nettokä...   2017  3226.6
KOKO MAA  Sosiaali- ja terveystoiminta yhteensä, nettokä...   2018  3318.5
KOKO MAA  Sosiaali- ja terveystoiminta yhteensä, nettokä...   2019  3481.7
KOKO MAA  Sosiaali- ja terveystoiminta yhteensä, nettokä...   2020  3622.3

[825 rows x 3 columns]

In [137]:
pd.DataFrame(whole_country_series_df_fi.reset_index().to_dict('records')).set_index('KOKO MAA').dropna()

                                                 dimensions  Vuosi   value
KOKO MAA
KOKO MAA                                    Taajama-aste, %   1987    77.7
KOKO MAA                                    Taajama-aste, %   1988    77.7
KOKO MAA                                    Taajama-aste, %   1989    78.1
KOKO MAA                                    Taajama-aste, %   1990    80.6
KOKO MAA                                    Taajama-aste, %   1991    80.7
...                                                     ...    ...     ...
KOKO MAA  Sosiaali- ja terveystoiminta yhteensä, nettokä...   2016  3256.6
KOKO MAA  Sosiaali- ja terveystoiminta yhteensä, nettokä...   2017  3226.6
KOKO MAA  Sosiaali- ja terveystoiminta yhteensä, nettokä...   2018  3318.5
KOKO MAA  Sosiaali- ja terveystoiminta yhteensä, nettokä...   2019  3481.7
KOKO MAA  Sosiaali- ja terveystoiminta yhteensä, nettokä...   2020  3622.3

[825 rows x 3 columns]

In [143]:
pd.DataFrame(regions_series_data_fi.reset_index().to_dict('records')).set_index('index').loc['Uudenmaan maakunta'].reset_index()

,index,dimensions,Vuosi,value
0,Uudenmaan maakunta,"Taajama-aste, %",1987,92.4
1,Uudenmaan maakunta,"Taajama-aste, %",1988,92.1
2,Uudenmaan maakunta,"Taajama-aste, %",1989,92.3
3,Uudenmaan maakunta,"Taajama-aste, %",1990,93.6
4,Uudenmaan maakunta,"Taajama-aste, %",1991,93.6
...,...,...,...,...
820,Uudenmaan maakunta,"Sosiaali- ja terveystoiminta yhteensä, nettokä...",2016,2865.0
821,Uudenmaan maakunta,"Sosiaali- ja terveystoiminta yhteensä, nettokä...",2017,2848.5
822,Uudenmaan maakunta,"Sosiaali- ja terveystoiminta yhteensä, nettokä...",2018,2888.8
823,Uudenmaan maakunta,"Sosiaali- ja terveystoiminta yhteensä, nettokä...",2019,3114.8
824,Uudenmaan maakunta,"Sosiaali- ja terveystoiminta yhteensä, nettokä...",2020,3253.4

In [144]:
whole_country_series_df

                                                      dimensions  Year   value
Region
WHOLE COUNTRY                          Degree of urbanisation, %  1987    77.7
WHOLE COUNTRY                          Degree of urbanisation, %  1988    77.7
WHOLE COUNTRY                          Degree of urbanisation, %  1989    78.1
WHOLE COUNTRY                          Degree of urbanisation, %  1990    80.6
WHOLE COUNTRY                          Degree of urbanisation, %  1991    80.7
...                                                          ...   ...     ...
WHOLE COUNTRY  Social and health care activities, total, oper...  2016  3256.6
WHOLE COUNTRY  Social and health care activities, total, oper...  2017  3226.6
WHOLE COUNTRY  Social and health care activities, total, oper...  2018  3318.5
WHOLE COUNTRY  Social and health care activities, total, oper...  2019  3481.7
WHOLE COUNTRY  Social and health care activities, total, oper...  2020  3622.3

[825 rows x 3 columns]

In [200]:
mun_data = regions_series_data = get_timeseries_data('Municipality')

In [201]:
mun_data.tail()

        dimensions  Year   value
Region
308             31  2016  3543.1
308             31  2017  3498.9
308             31  2018  3536.3
308             31  2019  3652.4
308             31  2020  3996.9

In [202]:
mun_data.memory_usage(deep=True)

Index         2039400
dimensions    2039400
Year          1019700
value         2039400
dtype: int64

In [170]:
mun_data.head()

                       dimensions  Year  value
Region
Akaa    Degree of urbanisation, %  1987   85.2
Akaa    Degree of urbanisation, %  1988   85.1
Akaa    Degree of urbanisation, %  1989   85.2
Akaa    Degree of urbanisation, %  1990   86.0
Akaa    Degree of urbanisation, %  1991   85.5

In [203]:
mun_data.index = mun_data.index.astype('category')
mun_data['dimensions'] = mun_data['dimensions'].astype('category')
mun_data['Year'] = mun_data['Year'].astype('category')
mun_data['value'] = mun_data['value'].astype('float32')

In [204]:
mun_data.memory_usage(deep=True)

Index          520618
dimensions     256253
Year           256277
value         1019700
dtype: int64

In [174]:
540902/ 18060900

0.029948784390589615

In [193]:
mun_data.tail()

,dimensions,Year,value
Region,,,
Äänekoski,"Social and health care activities, total, oper...",2016,3543.100098
Äänekoski,"Social and health care activities, total, oper...",2017,3498.899902
Äänekoski,"Social and health care activities, total, oper...",2018,3536.300049
Äänekoski,"Social and health care activities, total, oper...",2019,3652.399902
Äänekoski,"Social and health care activities, total, oper...",2020,3996.899902

In [184]:
mun_data.value = np.round(mun_data.value,2)

C:\Users\tuomas.poukkula\Anaconda3\lib\site-packages\pandas\core\series.py:2442: RuntimeWarning: overflow encountered in multiply
  result = self._values.round(decimals)

In [185]:
mun_data.head()

                       dimensions  Year    value
Region
Akaa    Degree of urbanisation, %  1987  85.1875
Akaa    Degree of urbanisation, %  1988  85.1250
Akaa    Degree of urbanisation, %  1989  85.1875
Akaa    Degree of urbanisation, %  1990  86.0000
Akaa    Degree of urbanisation, %  1991  85.5000

In [194]:
mun_data.round({'value':2})

,dimensions,Year,value
Region,,,
Akaa,"Degree of urbanisation, %",1987,85.199997
Akaa,"Degree of urbanisation, %",1988,85.099998
Akaa,"Degree of urbanisation, %",1989,85.199997
Akaa,"Degree of urbanisation, %",1990,86.000000
Akaa,"Degree of urbanisation, %",1991,85.500000
...,...,...,...
Äänekoski,"Social and health care activities, total, oper...",2016,3543.100098
Äänekoski,"Social and health care activities, total, oper...",2017,3498.899902
Äänekoski,"Social and health care activities, total, oper...",2018,3536.300049
Äänekoski,"Social and health care activities, total, oper...",2019,3652.399902
Äänekoski,"Social and health care activities, total, oper...",2020,3996.899902

In [214]:
sub_reg_payload

{'query': [{'code': 'Alue 2021',
   'selection': {'filter': 'item',
    'values': ['SSS',
     'SK011',
     'SK014',
     'SK015',
     'SK016',
     'SK021',
     'SK022',
     'SK023',
     'SK024',
     'SK025',
     'SK041',
     'SK043',
     'SK044',
     'SK051',
     'SK052',
     'SK053',
     'SK061',
     'SK063',
     'SK064',
     'SK068',
     'SK069',
     'SK071',
     'SK081',
     'SK082',
     'SK091',
     'SK093',
     'SK101',
     'SK103',
     'SK105',
     'SK111',
     'SK112',
     'SK113',
     'SK114',
     'SK115',
     'SK122',
     'SK124',
     'SK125',
     'SK131',
     'SK132',
     'SK133',
     'SK134',
     'SK135',
     'SK138',
     'SK141',
     'SK142',
     'SK144',
     'SK146',
     'SK152',
     'SK153',
     'SK154',
     'SK161',
     'SK162',
     'SK171',
     'SK173',
     'SK174',
     'SK175',
     'SK176',
     'SK177',
     'SK178',
     'SK181',
     'SK182',
     'SK191',
     'SK192',
     'SK193',
     'SK194',
     'SK196',
     'SK197',
     'SK211',
     'SK212',
     'SK213']}}],
 'response': {'format': 'json-stat2'}}

In [211]:
subreg_series_payload

{'query': [{'code': 'Alue 2021',
   'selection': {'filter': 'item',
    'values': ['SK011',
     'SK014',
     'SK015',
     'SK016',
     'SK021',
     'SK022',
     'SK023',
     'SK024',
     'SK025',
     'SK041',
     'SK043',
     'SK044',
     'SK051',
     'SK052',
     'SK053',
     'SK061',
     'SK063',
     'SK064',
     'SK068',
     'SK069',
     'SK071',
     'SK081',
     'SK082',
     'SK091',
     'SK093',
     'SK101',
     'SK103',
     'SK105',
     'SK111',
     'SK112',
     'SK113',
     'SK114',
     'SK115',
     'SK122',
     'SK124',
     'SK125',
     'SK131',
     'SK132',
     'SK133',
     'SK134',
     'SK135',
     'SK138',
     'SK141',
     'SK142',
     'SK144',
     'SK146',
     'SK152',
     'SK153',
     'SK154',
     'SK161',
     'SK162',
     'SK171',
     'SK173',
     'SK174',
     'SK175',
     'SK176',
     'SK177',
     'SK178',
     'SK181',
     'SK182',
     'SK191',
     'SK192',
     'SK193',
     'SK194',
     'SK196',
     'SK197',
     'SK211',
     'SK212',
     'SK213']}}],
 'response': {'format': 'json-stat2'}}

In [23]:
import orjson


with open('mapbox/assets/subreg_series_payload.json', encoding='utf-8') as f:
    rp = orjson.loads(f.read())
rp

{'query': [{'code': 'Alue 2021',
   'selection': {'filter': 'item',
    'values': ['SK011',
     'SK014',
     'SK015',
     'SK016',
     'SK021',
     'SK022',
     'SK023',
     'SK024',
     'SK025',
     'SK041',
     'SK043',
     'SK044',
     'SK051',
     'SK052',
     'SK053',
     'SK061',
     'SK063',
     'SK064',
     'SK068',
     'SK069',
     'SK071',
     'SK081',
     'SK082',
     'SK091',
     'SK093',
     'SK101',
     'SK103',
     'SK105',
     'SK111',
     'SK112',
     'SK113',
     'SK114',
     'SK115',
     'SK122',
     'SK124',
     'SK125',
     'SK131',
     'SK132',
     'SK133',
     'SK134',
     'SK135',
     'SK138',
     'SK141',
     'SK142',
     'SK144',
     'SK146',
     'SK152',
     'SK153',
     'SK154',
     'SK161',
     'SK162',
     'SK171',
     'SK173',
     'SK174',
     'SK175',
     'SK176',
     'SK177',
     'SK178',
     'SK181',
     'SK182',
     'SK191',
     'SK192',
     'SK193',
     'SK194',
     'SK196',
     'SK197',
     'SK211',
     'SK212',
     'SK213']}}],
 'response': {'format': 'json-stat2'}}

In [20]:
import os
os.listdir('mapbox/assets')

['en.PNG',
 'favicon.ico',
 'fi.PNG',
 'gofore_logo_white.svg',
 'images',
 'manifest.json',
 'municipalities_multilang.json',
 'mun_payload.json',
 'mun_series_payload.json',
 'offline.html',
 'regions_multilang.json',
 'reg_payload.json',
 'reg_series_payload.json',
 'subregions_multilang.json',
 'subreg_payload.json',
 'subreg_series_payload.json',
 'sv.PNG',
 'sw01.js']

In [8]:
region_names = get_region_names()
region_names

,nimi,namn,name
id,,,
SSS,KOKO MAA,HELA LANDET,WHOLE COUNTRY
020,Akaa,Ackas,Akaa
005,Alajärvi,Alajärvi,Alajärvi
009,Alavieska,Alavieska,Alavieska
010,Alavus,Alavo,Alavus
...,...,...,...
SK196,Tunturi-Lapin seutukunta,Tunturi-Lappi ekon. reg.,Tunturi-Lappi sub-regional unit
SK197,Pohjois-Lapin seutukunta,Norra Lapplands ekon. reg.,Pohjois-Lappi sub-regional unit
SK211,Mariehamns stad,Mariehamns stad,Mariehamns stad sub-regional unit
SK212,Ålands landsbygd,Ålands landsbygd,Ålands landsbygd sub-regional unit
SK213,Ålands skärgård,Ålands skärgård,Ålands skärgård sub-regional unit

In [9]:
series_indicator_names = get_series_indicator_names()
series_indicator_names

,nimi,namn,name
id,,,
M408,"Taajama-aste, %","Tätortsgrad, %","Degree of urbanisation, %"
M411,Väkiluku,Folkmängd,Population
M476,"Väkiluvun muutos edellisestä vuodesta, %","Förändring i folkmängden från året innan, %","Population change from the previous year, %"
M391,"Alle 15-vuotiaiden osuus väestöstä, %","Andelen personer under 15 år av befolkningen, %",Share of persons aged under 15 of the populati...
M421,"15-64 -vuotiaiden osuus väestöstä, %","Andelen 15–64-åringar av befolkningen, %",Share of persons aged 15 to 64 of the populati...
M478,"Yli 64-vuotiaiden osuus väestöstä, %","Andelen personer över 64 år av befolkningen, %",Share of persons aged over 64 of the populatio...
M404,"Ruotsinkielisten osuus väestöstä, %","Andelen svenskspråkiga av befolkningen, %","Share of Swedish-speakers of the population, %"
M410,"Ulkomaan kansalaisten osuus väestöstä, %","Andelen utländska medborgare av befolkningen, %","Share of foreign citizens of the population, %"
M303,"Syntyneiden enemmyys, henkilöä","Födelseöverskott, personer","Excess of births, persons"
M297,"Kuntien välinen muuttovoitto/-tappio, henkilöä",Inflyttningsöverskott/-underskott mellan kommu...,"Intermunicipal migration gain/loss, persons"
M302,Perheiden lukumäärä,Antal familjer,Number of families
M44,Asuntokuntien lukumäärä,Antal bostadshushåll,Number of household-dwelling units
M62,Rivi- ja pientaloissa asuvien asuntokuntien os...,Andelen bostadshushåll som bor i rad- eller sm...,Share of household-dwelling units living in te...
M70,"Vuokra-asunnoissa asuvien asuntokuntien osuus, %","Andelen bostadshushåll som bor i hyresbostäder, %",Share of household-dwelling units living in re...
M488,Vähintään toisen asteen tutkinnon suorittaneid...,Andelen personer som avlagt examen på minst an...,Share of persons aged 15 or over with at least...
M486,Korkea-asteen tutkinnon suorittaneiden osuus 1...,Andelen personer som avlagt examen på högre ni...,Share of persons aged 15 or over with tertiary...
M137,Alueella asuvan työllisen työvoiman määrä,Inom området bosatt sysselsatt arbetskraft,Employed labour force resident in the area
M140,"Työllisyysaste, %","Relativt sysselsättningstal, %","Employment rate, %"
M130,"Asuinkunnassaan työssäkäyvien osuus, %",Andelen personer som arbetar i sin bostadskomm...,Share of persons working in their municipality...
M162,"Työttömien osuus työvoimasta, %","Arbetslösas andel av arbetskraften, %",Proportion of the unemployed among the labour ...
M78,"Eläkeläisten osuus väestöstä, %","Andelen pensionärer av befolkningen, %","Proportion of pensioners of the population, %"
M485,Taloudellinen huoltosuhde,Ekonomisk försörjningskvot,Economic dependency ratio
M152,Alueella olevien työpaikkojen lukumäärä,Antalet arbetsplatser i kommunen,Number of workplaces in the area
M72,"Alkutuotannon työpaikkojen osuus, %","Andelen arbetsplatser inom primärproduktionen, %","Share of workplaces in primary production, %"
M84,"Jalostuksen työpaikkojen osuus, %","Andelen arbetsplatser inom förädling, %","Share of workplaces in secondary production, %"
M106,"Palvelujen työpaikkojen osuus, %","Andelen arbetsplatser inom tjänster, %","Share of workplaces in services, %"
M151,Työpaikkaomavaraisuus,Arbetsplatssufficiens,Workplace self-sufficiency
M499,"Vuosikate, euroa/asukas","Årsbidrag, €/invånare","Annual contribution margin, EUR per capita"
M496,"Lainakanta, euroa/asukas","Lånestock, €/invånare","Loan stock, EUR per capita"
M495,"Konsernin lainakanta, euroa/asukas","Koncernens årsbidrag, €/invånare","Group loan stock, EUR per capita"
M497,"Opetus- ja kulttuuritoiminta yhteensä, nettokä...","Undervisnings- och kulturverksamhet totalt, ne...","Educational and cultural activities, total, op..."
M498,"Sosiaali- ja terveystoiminta yhteensä, nettokä...","Social- och hälsovård totalt, nettodriftskostn...","Social and health care activities, total, oper..."

In [5]:
import numpy as np
df = get_timeseries_data('Municipality')

df

       dimensions  Year   value
Region
020          M408  2011    86.8
020          M408  2012    86.8
020          M408  2013    86.7
020          M408  2014    87.0
020          M408  2015    88.4
...           ...   ...     ...
992          M498  2016  3543.1
992          M498  2017  3498.9
992          M498  2018  3536.3
992          M498  2019  3652.4
992          M498  2020  3996.9

[306837 rows x 3 columns]

In [6]:
df.memory_usage(deep=True)

Index          640510
dimensions     309855
Year           307808
value         2454696
dtype: int64

In [77]:
df.dtypes

dimensions    category
Year          category
value          float64
dtype: object

In [78]:
df.shape

(306837, 3)

In [102]:
def apply_index_name(index):
    return region_names.loc[index]['name']
def apply_indicator_name(index):
    return series_indicator_names.loc[index]['name']

In [25]:
df.index.map(apply_index_name)

CategoricalIndex(['Akaa', 'Akaa', 'Akaa', 'Akaa', 'Akaa', 'Akaa', 'Akaa',
                  'Akaa', 'Akaa', 'Akaa',
                  ...
                  'Äänekoski', 'Äänekoski', 'Äänekoski', 'Äänekoski',
                  'Äänekoski', 'Äänekoski', 'Äänekoski', 'Äänekoski',
                  'Äänekoski', 'Äänekoski'],
                 categories=['Alajärvi', 'Alavieska', 'Alavus', 'Asikkala', 'Askola', 'Aura', 'Akaa', 'Brändö', ...], ordered=False, dtype='category', name='Region', length=306837)

In [26]:
df.index = df.index.map(apply_index_name)

In [13]:
region_names.loc['SK196']

nimi           Tunturi-Lapin seutukunta
namn           Tunturi-Lappi ekon. reg.
name    Tunturi-Lappi sub-regional unit
Name: SK196, dtype: object

In [31]:
df.dimensions = df.dimensions.map(apply_indicator_name)

In [32]:
df

                                                  dimensions  Year   value
Region
Akaa                               Degree of urbanisation, %  2011    86.8
Akaa                               Degree of urbanisation, %  2012    86.8
Akaa                               Degree of urbanisation, %  2013    86.7
Akaa                               Degree of urbanisation, %  2014    87.0
Akaa                               Degree of urbanisation, %  2015    88.4
...                                                      ...   ...     ...
Äänekoski  Social and health care activities, total, oper...  2016  3543.1
Äänekoski  Social and health care activities, total, oper...  2017  3498.9
Äänekoski  Social and health care activities, total, oper...  2018  3536.3
Äänekoski  Social and health care activities, total, oper...  2019  3652.4
Äänekoski  Social and health care activities, total, oper...  2020  3996.9

[306837 rows x 3 columns]

In [33]:
df.memory_usage(deep=True)

Index          644726
dimensions     311154
Year           307808
value         2454696
dtype: int64

In [103]:
df = get_timeseries_data('Region')
df.index = df.index.map(apply_index_name)
df.dimensions = df.dimensions.map(apply_indicator_name)
df

                                                      dimensions  Year   value
Region
WHOLE COUNTRY                          Degree of urbanisation, %  1987    77.7
WHOLE COUNTRY                          Degree of urbanisation, %  1988    77.7
WHOLE COUNTRY                          Degree of urbanisation, %  1989    78.1
WHOLE COUNTRY                          Degree of urbanisation, %  1990    80.6
WHOLE COUNTRY                          Degree of urbanisation, %  1991    80.7
...                                                          ...   ...     ...
Åland          Social and health care activities, total, oper...  2016  1827.9
Åland          Social and health care activities, total, oper...  2017  1747.5
Åland          Social and health care activities, total, oper...  2018  1824.0
Åland          Social and health care activities, total, oper...  2019  1905.9
Åland          Social and health care activities, total, oper...  2020  1936.3

[16500 rows x 3 columns]

In [105]:
[c for c in df['dimensions'].unique() if "'" in c]

[]

In [100]:
key_figure = 'Tätortsgrad, %'
dff = df.loc[['Åland']].query(f"dimensions=='{key_figure}'")
dff

            dimensions  Year  value
Region
Åland   Tätortsgrad, %  1987   52.5
Åland   Tätortsgrad, %  1988   52.4
Åland   Tätortsgrad, %  1989   53.7
Åland   Tätortsgrad, %  1990   55.8
Åland   Tätortsgrad, %  1991   55.4
Åland   Tätortsgrad, %  1992   55.3
Åland   Tätortsgrad, %  1993   55.2
Åland   Tätortsgrad, %  1994   55.9
Åland   Tätortsgrad, %  1995   56.8
Åland   Tätortsgrad, %  1996   57.0
Åland   Tätortsgrad, %  1997   56.7
Åland   Tätortsgrad, %  1998   57.0
Åland   Tätortsgrad, %  1999   56.6
Åland   Tätortsgrad, %  2000   57.6
Åland   Tätortsgrad, %  2001   57.6
Åland   Tätortsgrad, %  2002   57.0
Åland   Tätortsgrad, %  2003   56.9
Åland   Tätortsgrad, %  2004   56.7
Åland   Tätortsgrad, %  2005   56.6
Åland   Tätortsgrad, %  2006   61.3
Åland   Tätortsgrad, %  2007   61.2
Åland   Tätortsgrad, %  2008   61.1
Åland   Tätortsgrad, %  2009   61.3
Åland   Tätortsgrad, %  2010   60.2
Åland   Tätortsgrad, %  2011   60.1
Åland   Tätortsgrad, %  2012   60.3
Åland   Tätortsgrad, %  2013   60.6
Åland   Tätortsgrad, %  2014   60.8
Åland   Tätortsgrad, %  2015   61.7
Åland   Tätortsgrad, %  2016   62.5
Åland   Tätortsgrad, %  2017   62.6
Åland   Tätortsgrad, %  2018   62.8
Åland   Tätortsgrad, %  2019   63.7
Åland   Tätortsgrad, %  2020   63.8

In [106]:
name = dff.dimensions.values[0]
region = 'Landskap'
dff = dff.reset_index().rename(columns = {'value':name, 'Region':region, 'Year': 'År'})
dff

   Landskap      dimensions    År  Tätortsgrad, %
0     Åland  Tätortsgrad, %  1987            52.5
1     Åland  Tätortsgrad, %  1988            52.4
2     Åland  Tätortsgrad, %  1989            53.7
3     Åland  Tätortsgrad, %  1990            55.8
4     Åland  Tätortsgrad, %  1991            55.4
5     Åland  Tätortsgrad, %  1992            55.3
6     Åland  Tätortsgrad, %  1993            55.2
7     Åland  Tätortsgrad, %  1994            55.9
8     Åland  Tätortsgrad, %  1995            56.8
9     Åland  Tätortsgrad, %  1996            57.0
10    Åland  Tätortsgrad, %  1997            56.7
11    Åland  Tätortsgrad, %  1998            57.0
12    Åland  Tätortsgrad, %  1999            56.6
13    Åland  Tätortsgrad, %  2000            57.6
14    Åland  Tätortsgrad, %  2001            57.6
15    Åland  Tätortsgrad, %  2002            57.0
16    Åland  Tätortsgrad, %  2003            56.9
17    Åland  Tätortsgrad, %  2004            56.7
18    Åland  Tätortsgrad, %  2005            56.6
19    Åland  Tätortsgrad, %  2006            61.3
20    Åland  Tätortsgrad, %  2007            61.2
21    Åland  Tätortsgrad, %  2008            61.1
22    Åland  Tätortsgrad, %  2009            61.3
23    Åland  Tätortsgrad, %  2010            60.2
24    Åland  Tätortsgrad, %  2011            60.1
25    Åland  Tätortsgrad, %  2012            60.3
26    Åland  Tätortsgrad, %  2013            60.6
27    Åland  Tätortsgrad, %  2014            60.8
28    Åland  Tätortsgrad, %  2015            61.7
29    Åland  Tätortsgrad, %  2016            62.5
30    Åland  Tätortsgrad, %  2017            62.6
31    Åland  Tätortsgrad, %  2018            62.8
32    Åland  Tätortsgrad, %  2019            63.7
33    Åland  Tätortsgrad, %  2020            63.8

In [109]:
dff.År = dff.År.astype(int)

In [110]:
import plotly.express as px
fig = px.line(dff, x = 'År', y = name, color = region, hover_data = [region,'År',name])

fig

In [48]:
reg_names.reset_index().to_dict('records')

[{'id': 'SSS',
  'nimi': 'KOKO MAA',
  'namn': 'HELA LANDET',
  'name': 'WHOLE COUNTRY'},
 {'id': '020', 'nimi': 'Akaa', 'namn': 'Ackas', 'name': 'Akaa'},
 {'id': '005', 'nimi': 'Alajärvi', 'namn': 'Alajärvi', 'name': 'Alajärvi'},
 {'id': '009', 'nimi': 'Alavieska', 'namn': 'Alavieska', 'name': 'Alavieska'},
 {'id': '010', 'nimi': 'Alavus', 'namn': 'Alavo', 'name': 'Alavus'},
 {'id': '016', 'nimi': 'Asikkala', 'namn': 'Asikkala', 'name': 'Asikkala'},
 {'id': '018', 'nimi': 'Askola', 'namn': 'Askola', 'name': 'Askola'},
 {'id': '019', 'nimi': 'Aura', 'namn': 'Aura', 'name': 'Aura'},
 {'id': '035', 'nimi': 'Brändö', 'namn': 'Brändö', 'name': 'Brändö'},
 {'id': '043', 'nimi': 'Eckerö', 'namn': 'Eckerö', 'name': 'Eckerö'},
 {'id': '046', 'nimi': 'Enonkoski', 'namn': 'Enonkoski', 'name': 'Enonkoski'},
 {'id': '047', 'nimi': 'Enontekiö', 'namn': 'Enontekis', 'name': 'Enontekiö'},
 {'id': '049', 'nimi': 'Espoo', 'namn': 'Esbo', 'name': 'Espoo'},
 {'id': '050', 'nimi': 'Eura', 'namn': 'Eura', 'name': 'Eura'},
 {'id': '051', 'nimi': 'Eurajoki', 'namn': 'Euraåminne', 'name': 'Eurajoki'},
 {'id': '052', 'nimi': 'Evijärvi', 'namn': 'Evijärvi', 'name': 'Evijärvi'},
 {'id': '060', 'nimi': 'Finström', 'namn': 'Finström', 'name': 'Finström'},
 {'id': '061', 'nimi': 'Forssa', 'namn': 'Forssa', 'name': 'Forssa'},
 {'id': '062', 'nimi': 'Föglö', 'namn': 'Föglö', 'name': 'Föglö'},
 {'id': '065', 'nimi': 'Geta', 'namn': 'Geta', 'name': 'Geta'},
 {'id': '069',
  'nimi': 'Haapajärvi',
  'namn': 'Haapajärvi',
  'name': 'Haapajärvi'},
 {'id': '071', 'nimi': 'Haapavesi', 'namn': 'Haapavesi', 'name': 'Haapavesi'},
 {'id': '072', 'nimi': 'Hailuoto', 'namn': 'Karlö', 'name': 'Hailuoto'},
 {'id': '074', 'nimi': 'Halsua', 'namn': 'Halso', 'name': 'Halsua'},
 {'id': '075', 'nimi': 'Hamina', 'namn': 'Fredrikshamn', 'name': 'Hamina'},
 {'id': '076',
  'nimi': 'Hammarland',
  'namn': 'Hammarland',
  'name': 'Hammarland'},
 {'id': '077',
  'nimi': 'Hankasalmi',
  'namn': 'Hankasalmi',
  'name': 'Hankasalmi'},
 {'id': '078', 'nimi': 'Hanko', 'namn': 'Hangö', 'name': 'Hanko'},
 {'id': '079',
  'nimi': 'Harjavalta',
  'namn': 'Harjavalta',
  'name': 'Harjavalta'},
 {'id': '081', 'nimi': 'Hartola', 'namn': 'Gustav Adolfs', 'name': 'Hartola'},
 {'id': '082', 'nimi': 'Hattula', 'namn': 'Hattula', 'name': 'Hattula'},
 {'id': '086', 'nimi': 'Hausjärvi', 'namn': 'Hausjärvi', 'name': 'Hausjärvi'},
 {'id': '111', 'nimi': 'Heinola', 'namn': 'Heinola', 'name': 'Heinola'},
 {'id': '090', 'nimi': 'Heinävesi', 'namn': 'Heinävesi', 'name': 'Heinävesi'},
 {'id': '091', 'nimi': 'Helsinki', 'namn': 'Helsingfors', 'name': 'Helsinki'},
 {'id': '097',
  'nimi': 'Hirvensalmi',
  'namn': 'Hirvensalmi',
  'name': 'Hirvensalmi'},
 {'id': '098', 'nimi': 'Hollola', 'namn': 'Hollola', 'name': 'Hollola'},
 {'id': '102', 'nimi': 'Huittinen', 'namn': 'Vittis', 'name': 'Huittinen'},
 {'id': '103', 'nimi': 'Humppila', 'namn': 'Humppila', 'name': 'Humppila'},
 {'id': '105',
  'nimi': 'Hyrynsalmi',
  'namn': 'Hyrynsalmi',
  'name': 'Hyrynsalmi'},
 {'id': '106', 'nimi': 'Hyvinkää', 'namn': 'Hyvinge', 'name': 'Hyvinkää'},
 {'id': '108',
  'nimi': 'Hämeenkyrö',
  'namn': 'Tavastkyro',
  'name': 'Hämeenkyrö'},
 {'id': '109',
  'nimi': 'Hämeenlinna',
  'namn': 'Tavastehus',
  'name': 'Hämeenlinna'},
 {'id': '139', 'nimi': 'Ii', 'namn': 'Ijo', 'name': 'Ii'},
 {'id': '140', 'nimi': 'Iisalmi', 'namn': 'Idensalmi', 'name': 'Iisalmi'},
 {'id': '142', 'nimi': 'Iitti', 'namn': 'Itis', 'name': 'Iitti'},
 {'id': '143', 'nimi': 'Ikaalinen', 'namn': 'Ikalis', 'name': 'Ikaalinen'},
 {'id': '145', 'nimi': 'Ilmajoki', 'namn': 'Ilmola', 'name': 'Ilmajoki'},
 {'id': '146', 'nimi': 'Ilomantsi', 'namn': 'Ilomants', 'name': 'Ilomantsi'},
 {'id': '153', 'nimi': 'Imatra', 'namn': 'Imatra', 'name': 'Imatra'},
 {'id': '148', 'nimi': 'Inari', 'namn': 'Enare', 'name': 'Inari'},
 {'id': '149', 'nimi': 'Inkoo', 'namn': 'Ingå', 'name': 'Ingå'},
 {'id': '151', 'nimi': 'Isojoki', 'namn': 'Storå', 'name': 'Isojoki'},
 {'id': '152', 'nimi': 'Isokyrö', 'namn': 'Storkyro', 'name': 'Isokyrö'},
 {'id': '165', 'nimi': 'Janakkala', 'namn': 'Janakkala', 'name': 'Janakkala'},
 {'id': '167', 'nimi': 'Joensuu', 'namn': 'Joensuu', 'name': 'Joensuu'},
 {'id': '169', 'nimi': 'Jokioinen', 'namn': 'Jockis', 'name': 'Jokioinen'},
 {'id': '170', 'nimi': 'Jomala', 'namn': 'Jomala', 'name': 'Jomala'},
 {'id': '171', 'nimi': 'Joroinen', 'namn': 'Jorois', 'name': 'Joroinen'},
 {'id': '172', 'nimi': 'Joutsa', 'namn': 'Joutsa', 'name': 'Joutsa'},
 {'id': '176', 'nimi': 'Juuka', 'namn': 'Juga', 'name': 'Juuka'},
 {'id': '177', 'nimi': 'Juupajoki', 'namn': 'Juupajoki', 'name': 'Juupajoki'},
 {'id': '178', 'nimi': 'Juva', 'namn': 'Juva', 'name': 'Juva'},
 {'id': '179', 'nimi': 'Jyväskylä', 'namn': 'Jyväskylä', 'name': 'Jyväskylä'},
 {'id': '181', 'nimi': 'Jämijärvi', 'namn': 'Jämijärvi', 'name': 'Jämijärvi'},
 {'id': '182', 'nimi': 'Jämsä', 'namn': 'Jämsä', 'name': 'Jämsä'},
 {'id': '186', 'nimi': 'Järvenpää', 'namn': 'Träskända', 'name': 'Järvenpää'},
 {'id': '202', 'nimi': 'Kaarina', 'namn': 'S:t Karins', 'name': 'Kaarina'},
 {'id': '204', 'nimi': 'Kaavi', 'namn': 'Kaavi', 'name': 'Kaavi'},
 {'id': '205', 'nimi': 'Kajaani', 'namn': 'Kajana', 'name': 'Kajaani'},
 {'id': '208', 'nimi': 'Kalajoki', 'namn': 'Kalajoki', 'name': 'Kalajoki'},
 {'id': '211', 'nimi': 'Kangasala', 'namn': 'Kangasala', 'name': 'Kangasala'},
 {'id': '213',
  'nimi': 'Kangasniemi',
  'namn': 'Kangasniemi',
  'name': 'Kangasniemi'},
 {'id': '214',
  'nimi': 'Kankaanpää',
  'namn': 'Kankaanpää',
  'name': 'Kankaanpää'},
 {'id': '216',
  'nimi': 'Kannonkoski',
  'namn': 'Kannonkoski',
  'name': 'Kannonkoski'},
 {'id': '217', 'nimi': 'Kannus', 'namn': 'Kannus', 'name': 'Kannus'},
 {'id': '218', 'nimi': 'Karijoki', 'namn': 'Bötom', 'name': 'Karijoki'},
 {'id': '224', 'nimi': 'Karkkila', 'namn': 'Högfors', 'name': 'Karkkila'},
 {'id': '226', 'nimi': 'Karstula', 'namn': 'Karstula', 'name': 'Karstula'},
 {'id': '230', 'nimi': 'Karvia', 'namn': 'Karvia', 'name': 'Karvia'},
 {'id': '231', 'nimi': 'Kaskinen', 'namn': 'Kaskö', 'name': 'Kaskinen'},
 {'id': '232', 'nimi': 'Kauhajoki', 'namn': 'Kauhajoki', 'name': 'Kauhajoki'},
 {'id': '233', 'nimi': 'Kauhava', 'namn': 'Kauhava', 'name': 'Kauhava'},
 {'id': '235',
  'nimi': 'Kauniainen',
  'namn': 'Grankulla',
  'name': 'Kauniainen'},
 {'id': '236', 'nimi': 'Kaustinen', 'namn': 'Kaustby', 'name': 'Kaustinen'},
 {'id': '239', 'nimi': 'Keitele', 'namn': 'Keitele', 'name': 'Keitele'},
 {'id': '240', 'nimi': 'Kemi', 'namn': 'Kemi', 'name': 'Kemi'},
 {'id': '320', 'nimi': 'Kemijärvi', 'namn': 'Kemijärvi', 'name': 'Kemijärvi'},
 {'id': '241', 'nimi': 'Keminmaa', 'namn': 'Keminmaa', 'name': 'Keminmaa'},
 {'id': '322', 'nimi': 'Kemiönsaari', 'namn': 'Kimitoön', 'name': 'Kimitoön'},
 {'id': '244', 'nimi': 'Kempele', 'namn': 'Kempele', 'name': 'Kempele'},
 {'id': '245', 'nimi': 'Kerava', 'namn': 'Kervo', 'name': 'Kerava'},
 {'id': '249', 'nimi': 'Keuruu', 'namn': 'Keuru', 'name': 'Keuruu'},
 {'id': '250', 'nimi': 'Kihniö', 'namn': 'Kihniö', 'name': 'Kihniö'},
 {'id': '256', 'nimi': 'Kinnula', 'namn': 'Kinnula', 'name': 'Kinnula'},
 {'id': '257',
  'nimi': 'Kirkkonummi',
  'namn': 'Kyrkslätt',
  'name': 'Kirkkonummi'},
 {'id': '260', 'nimi': 'Kitee', 'namn': 'Kides', 'name': 'Kitee'},
 {'id': '261', 'nimi': 'Kittilä', 'namn': 'Kittilä', 'name': 'Kittilä'},
 {'id': '263', 'nimi': 'Kiuruvesi', 'namn': 'Kiuruvesi', 'name': 'Kiuruvesi'},
 {'id': '265', 'nimi': 'Kivijärvi', 'namn': 'Kivijärvi', 'name': 'Kivijärvi'},
 {'id': '271', 'nimi': 'Kokemäki', 'namn': 'Kumo', 'name': 'Kokemäki'},
 {'id': '272', 'nimi': 'Kokkola', 'namn': 'Karleby', 'name': 'Kokkola'},
 {'id': '273', 'nimi': 'Kolari', 'namn': 'Kolari', 'name': 'Kolari'},
 {'id': '275', 'nimi': 'Konnevesi', 'namn': 'Konnevesi', 'name': 'Konnevesi'},
 {'id': '276',
  'nimi': 'Kontiolahti',
  'namn': 'Kontiolax',
  'name': 'Kontiolahti'},
 {'id': '280', 'nimi': 'Korsnäs', 'namn': 'Korsnäs', 'name': 'Korsnäs'},
 {'id': '284', 'nimi': 'Koski Tl', 'namn': 'Koskis', 'name': 'Koski Tl'},
 {'id': '285', 'nimi': 'Kotka', 'namn': 'Kotka', 'name': 'Kotka'},
 {'id': '286', 'nimi': 'Kouvola', 'namn': 'Kouvola', 'name': 'Kouvola'},
 {'id': '287',
  'nimi': 'Kristiinankaupunki',
  'namn': 'Kristinestad',
  'name': 'Kristinestad'},
 {'id': '288', 'nimi': 'Kruunupyy', 'namn': 'Kronoby', 'name': 'Kronoby'},
 {'id': '290', 'nimi': 'Kuhmo', 'namn': 'Kuhmo', 'name': 'Kuhmo'},
 {'id': '291', 'nimi': 'Kuhmoinen', 'namn': 'Kuhmois', 'name': 'Kuhmoinen'},
 {'id': '295', 'nimi': 'Kumlinge', 'namn': 'Kumlinge', 'name': 'Kumlinge'},
 {'id': '297', 'nimi': 'Kuopio', 'namn': 'Kuopio', 'name': 'Kuopio'},
 {'id': '300', 'nimi': 'Kuortane', 'namn': 'Kuortane', 'name': 'Kuortane'},
 {'id': '301', 'nimi': 'Kurikka', 'namn': 'Kurikka', 'name': 'Kurikka'},
 {'id': '304', 'nimi': 'Kustavi', 'namn': 'Gustavs', 'name': 'Kustavi'},
 {'id': '305', 'nimi': 'Kuusamo', 'namn': 'Kuusamo', 'name': 'Kuusamo'},
 {'id': '312', 'nimi': 'Kyyjärvi', 'namn': 'Kyyjärvi', 'name': 'Kyyjärvi'},
 {'id': '316', 'nimi': 'Kärkölä', 'namn': 'Kärkölä', 'name': 'Kärkölä'},
 {'id': '317', 'nimi': 'Kärsämäki', 'namn': 'Kärsämäki', 'name': 'Kärsämäki'},
 {'id': '318', 'nimi': 'Kökar', 'namn': 'Kökar', 'name': 'Kökar'},
 {'id': '398', 'nimi': 'Lahti', 'namn': 'Lahtis', 'name': 'Lahti'},
 {'id': '399', 'nimi': 'Laihia', 'namn': 'Laihela', 'name': 'Laihia'},
 {'id': '400', 'nimi': 'Laitila', 'namn': 'Letala', 'name': 'Laitila'},
 {'id': '407',
  'nimi': 'Lapinjärvi',
  'namn': 'Lappträsk',
  'name': 'Lapinjärvi'},
 {'id': '402',
  'nimi': 'Lapinlahti',
  'namn': 'Lapinlahti',
  'name': 'Lapinlahti'},
 {'id': '403',
  'nimi': 'Lappajärvi',
  'namn': 'Lappajärvi',
  'name': 'Lappajärvi'},
 {'id': '405',
  'nimi': 'Lappeenranta',
  'namn': 'Villmanstrand',
  'name': 'Lappeenranta'},
 {'id': '408', 'nimi': 'Lapua', 'namn': 'Lappo', 'name': 'Lapua'},
 {'id': '410', 'nimi': 'Laukaa', 'namn': 'Laukas', 'name': 'Laukaa'},
 {'id': '416', 'nimi': 'Lemi', 'namn': 'Lemi', 'name': 'Lemi'},
 {'id': '417', 'nimi': 'Lemland', 'namn': 'Lemland', 'name': 'Lemland'},
 {'id': '418', 'nimi': 'Lempäälä', 'namn': 'Lempäälä', 'name': 'Lempäälä'},
 {'id': '420',
  'nimi': 'Leppävirta',
  'namn': 'Leppävirta',
  'name': 'Leppävirta'},
 {'id': '421',
  'nimi': 'Lestijärvi',
  'namn': 'Lestijärvi',
  'name': 'Lestijärvi'},
 {'id': '422', 'nimi': 'Lieksa', 'namn': 'Lieksa', 'name': 'Lieksa'},
 {'id': '423', 'nimi': 'Lieto', 'namn': 'Lundo', 'name': 'Lieto'},
 {'id': '425', 'nimi': 'Liminka', 'namn': 'Limingo', 'name': 'Liminka'},
 {'id': '426', 'nimi': 'Liperi', 'namn': 'Libelits', 'name': 'Liperi'},
 {'id': '444', 'nimi': 'Lohja', 'namn': 'Lojo', 'name': 'Lohja'},
 {'id': '430', 'nimi': 'Loimaa', 'namn': 'Loimaa', 'name': 'Loimaa'},
 {'id': '433', 'nimi': 'Loppi', 'namn': 'Loppi', 'name': 'Loppi'},
 {'id': '434', 'nimi': 'Loviisa', 'namn': 'Lovisa', 'name': 'Loviisa'},
 {'id': '435', 'nimi': 'Luhanka', 'namn': 'Luhanka', 'name': 'Luhanka'},
 {'id': '436', 'nimi': 'Lumijoki', 'namn': 'Lumijoki', 'name': 'Lumijoki'},
 {'id': '438',
  'nimi': 'Lumparland',
  'namn': 'Lumparland',
  'name': 'Lumparland'},
 {'id': '440', 'nimi': 'Luoto', 'namn': 'Larsmo', 'name': 'Larsmo'},
 {'id': '441', 'nimi': 'Luumäki', 'namn': 'Luumäki', 'name': 'Luumäki'},
 {'id': '475', 'nimi': 'Maalahti', 'namn': 'Malax', 'name': 'Malax'},
 {'id': '478',
  'nimi': 'Maarianhamina',
  'namn': 'Mariehamn',
  'name': 'Mariehamn'},
 {'id': '480', 'nimi': 'Marttila', 'namn': 'S:t Mårtens', 'name': 'Marttila'},
 {'id': '481', 'nimi': 'Masku', 'namn': 'Masku', 'name': 'Masku'},
 {'id': '483', 'nimi': 'Merijärvi', 'namn': 'Merijärvi', 'name': 'Merijärvi'},
 {'id': '484', 'nimi': 'Merikarvia', 'namn': 'Sastmola', 'name': 'Merikarvia'},
 {'id': '489',
  'nimi': 'Miehikkälä',
  'namn': 'Miehikkälä',
  'name': 'Miehikkälä'},
 {'id': '491', 'nimi': 'Mikkeli', 'namn': 'S:t Michel', 'name': 'Mikkeli'},
 {'id': '494', 'nimi': 'Muhos', 'namn': 'Muhos', 'name': 'Muhos'},
 {'id': '495', 'nimi': 'Multia', 'namn': 'Multia', 'name': 'Multia'},
 {'id': '498', 'nimi': 'Muonio', 'namn': 'Muonio', 'name': 'Muonio'},
 {'id': '499', 'nimi': 'Mustasaari', 'namn': 'Korsholm', 'name': 'Korsholm'},
 {'id': '500', 'nimi': 'Muurame', 'namn': 'Muurame', 'name': 'Muurame'},
 {'id': '503', 'nimi': 'Mynämäki', 'namn': 'Virmo', 'name': 'Mynämäki'},
 {'id': '504', 'nimi': 'Myrskylä', 'namn': 'Mörskom', 'name': 'Myrskylä'},
 {'id': '505', 'nimi': 'Mäntsälä', 'namn': 'Mäntsälä', 'name': 'Mäntsälä'},
 {'id': '508',
  'nimi': 'Mänttä-Vilppula',
  'namn': 'Mänttä-Vilppula',
  'name': 'Mänttä-Vilppula'},
 {'id': '507',
  'nimi': 'Mäntyharju',
  'namn': 'Mäntyharju',
  'name': 'Mäntyharju'},
 {'id': '529', 'nimi': 'Naantali', 'namn': 'Nådendal', 'name': 'Naantali'},
 {'id': '531', 'nimi': 'Nakkila', 'namn': 'Nakkila', 'name': 'Nakkila'},
 {'id': '535', 'nimi': 'Nivala', 'namn': 'Nivala', 'name': 'Nivala'},
 {'id': '536', 'nimi': 'Nokia', 'namn': 'Nokia', 'name': 'Nokia'},
 {'id': '538', 'nimi': 'Nousiainen', 'namn': 'Nousis', 'name': 'Nousiainen'},
 {'id': '541', 'nimi': 'Nurmes', 'namn': 'Nurmes', 'name': 'Nurmes'},
 {'id': '543',
  'nimi': 'Nurmijärvi',
  'namn': 'Nurmijärvi',
  'name': 'Nurmijärvi'},
 {'id': '545', 'nimi': 'Närpiö', 'namn': 'Närpes', 'name': 'Närpes'},
 {'id': '560',
  'nimi': 'Orimattila',
  'namn': 'Orimattila',
  'name': 'Orimattila'},
 {'id': '561', 'nimi': 'Oripää', 'namn': 'Oripää', 'name': 'Oripää'},
 {'id': '562', 'nimi': 'Orivesi', 'namn': 'Orivesi', 'name': 'Orivesi'},
 {'id': '563', 'nimi': 'Oulainen', 'namn': 'Oulainen', 'name': 'Oulainen'},
 {'id': '564', 'nimi': 'Oulu', 'namn': 'Uleåborg', 'name': 'Oulu'},
 {'id': '309', 'nimi': 'Outokumpu', 'namn': 'Outokumpu', 'name': 'Outokumpu'},
 {'id': '576', 'nimi': 'Padasjoki', 'namn': 'Padasjoki', 'name': 'Padasjoki'},
 {'id': '577', 'nimi': 'Paimio', 'namn': 'Pemar', 'name': 'Paimio'},
 {'id': '578', 'nimi': 'Paltamo', 'namn': 'Paltamo', 'name': 'Paltamo'},
 {'id': '445', 'nimi': 'Parainen', 'namn': 'Pargas', 'name': 'Pargas'},
 {'id': '580', 'nimi': 'Parikkala', 'namn': 'Parikkala', 'name': 'Parikkala'},
 {'id': '581', 'nimi': 'Parkano', 'namn': 'Parkano', 'name': 'Parkano'},
 {'id': '599',
  'nimi': 'Pedersören kunta',
  'namn': 'Pedersöre',
  'name': 'Pedersöre'},
 {'id': '583',
  'nimi': 'Pelkosenniemi',
  'namn': 'Pelkosenniemi',
  'name': 'Pelkosenniemi'},
 {'id': '854', 'nimi': 'Pello', 'namn': 'Pello', 'name': 'Pello'},
 {'id': '584', 'nimi': 'Perho', 'namn': 'Perho', 'name': 'Perho'},
 {'id': '588', 'nimi': 'Pertunmaa', 'namn': 'Pertunmaa', 'name': 'Pertunmaa'},
 {'id': '592',
  'nimi': 'Petäjävesi',
  'namn': 'Petäjävesi',
  'name': 'Petäjävesi'},
 {'id': '593',
  'nimi': 'Pieksämäki',
  'namn': 'Pieksämäki',
  'name': 'Pieksämäki'},
 {'id': '595', 'nimi': 'Pielavesi', 'namn': 'Pielavesi', 'name': 'Pielavesi'},
 {'id': '598',
  'nimi': 'Pietarsaari',
  'namn': 'Jakobstad',
  'name': 'Jakobstad'},
 {'id': '601',
  'nimi': 'Pihtipudas',
  'namn': 'Pihtipudas',
  'name': 'Pihtipudas'},
 {'id': '604', 'nimi': 'Pirkkala', 'namn': 'Birkala', 'name': 'Pirkkala'},
 {'id': '607',
  'nimi': 'Polvijärvi',
  'namn': 'Polvijärvi',
  'name': 'Polvijärvi'},
 {'id': '608', 'nimi': 'Pomarkku', 'namn': 'Påmark', 'name': 'Pomarkku'},
 {'id': '609', 'nimi': 'Pori', 'namn': 'Björneborg', 'name': 'Pori'},
 {'id': '611', 'nimi': 'Pornainen', 'namn': 'Borgnäs', 'name': 'Pornainen'},
 {'id': '638', 'nimi': 'Porvoo', 'namn': 'Borgå', 'name': 'Porvoo'},
 {'id': '614', 'nimi': 'Posio', 'namn': 'Posio', 'name': 'Posio'},
 {'id': '615',
  'nimi': 'Pudasjärvi',
  'namn': 'Pudasjärvi',
  'name': 'Pudasjärvi'},
 {'id': '616', 'nimi': 'Pukkila', 'namn': 'Pukkila', 'name': 'Pukkila'},
 {'id': '619',
  'nimi': 'Punkalaidun',
  'namn': 'Punkalaidun',
  'name': 'Punkalaidun'},
 {'id': '620', 'nimi': 'Puolanka', 'namn': 'Puolanka', 'name': 'Puolanka'},
 {'id': '623', 'nimi': 'Puumala', 'namn': 'Puumala', 'name': 'Puumala'},
 {'id': '624', 'nimi': 'Pyhtää', 'namn': 'Pyttis', 'name': 'Pyhtää'},
 {'id': '625', 'nimi': 'Pyhäjoki', 'namn': 'Pyhäjoki', 'name': 'Pyhäjoki'},
 {'id': '626', 'nimi': 'Pyhäjärvi', 'namn': 'Pyhäjärvi', 'name': 'Pyhäjärvi'},
 {'id': '630', 'nimi': 'Pyhäntä', 'namn': 'Pyhäntä', 'name': 'Pyhäntä'},
 {'id': '631', 'nimi': 'Pyhäranta', 'namn': 'Pyhäranta', 'name': 'Pyhäranta'},
 {'id': '635', 'nimi': 'Pälkäne', 'namn': 'Pälkäne', 'name': 'Pälkäne'},
 {'id': '636', 'nimi': 'Pöytyä', 'namn': 'Pöytyä', 'name': 'Pöytyä'},
 {'id': '678', 'nimi': 'Raahe', 'namn': 'Brahestad', 'name': 'Raahe'},
 {'id': '710', 'nimi': 'Raasepori', 'namn': 'Raseborg', 'name': 'Raasepori'},
 {'id': '680', 'nimi': 'Raisio', 'namn': 'Reso', 'name': 'Raisio'},
 {'id': '681',
  'nimi': 'Rantasalmi',
  'namn': 'Rantasalmi',
  'name': 'Rantasalmi'},
 {'id': '683', 'nimi': 'Ranua', 'namn': 'Ranua', 'name': 'Ranua'},
 {'id': '684', 'nimi': 'Rauma', 'namn': 'Raumo', 'name': 'Rauma'},
 {'id': '686',
  'nimi': 'Rautalampi',
  'namn': 'Rautalampi',
  'name': 'Rautalampi'},
 {'id': '687',
  'nimi': 'Rautavaara',
  'namn': 'Rautavaara',
  'name': 'Rautavaara'},
 {'id': '689', 'nimi': 'Rautjärvi', 'namn': 'Rautjärvi', 'name': 'Rautjärvi'},
 {'id': '691', 'nimi': 'Reisjärvi', 'namn': 'Reisjärvi', 'name': 'Reisjärvi'},
 {'id': '694', 'nimi': 'Riihimäki', 'namn': 'Riihimäki', 'name': 'Riihimäki'},
 {'id': '697',
  'nimi': 'Ristijärvi',
  'namn': 'Ristijärvi',
  'name': 'Ristijärvi'},
 {'id': '698', 'nimi': 'Rovaniemi', 'namn': 'Rovaniemi', 'name': 'Rovaniemi'},
 {'id': '700', 'nimi': 'Ruokolahti', 'namn': 'Ruokolax', 'name': 'Ruokolahti'},
 {'id': '702', 'nimi': 'Ruovesi', 'namn': 'Ruovesi', 'name': 'Ruovesi'},
 {'id': '704', 'nimi': 'Rusko', 'namn': 'Rusko', 'name': 'Rusko'},
 {'id': '707', 'nimi': 'Rääkkylä', 'namn': 'Rääkkylä', 'name': 'Rääkkylä'},
 {'id': '729',
  'nimi': 'Saarijärvi',
  'namn': 'Saarijärvi',
  'name': 'Saarijärvi'},
 {'id': '732', 'nimi': 'Salla', 'namn': 'Salla', 'name': 'Salla'},
 {'id': '734', 'nimi': 'Salo', 'namn': 'Salo', 'name': 'Salo'},
 {'id': '736', 'nimi': 'Saltvik', 'namn': 'Saltvik', 'name': 'Saltvik'},
 {'id': '790', 'nimi': 'Sastamala', 'namn': 'Sastamala', 'name': 'Sastamala'},
 {'id': '738', 'nimi': 'Sauvo', 'namn': 'Sagu', 'name': 'Sauvo'},
 {'id': '739',
  'nimi': 'Savitaipale',
  'namn': 'Savitaipale',
  'name': 'Savitaipale'},
 {'id': '740', 'nimi': 'Savonlinna', 'namn': 'Nyslott', 'name': 'Savonlinna'},
 {'id': '742', 'nimi': 'Savukoski', 'namn': 'Savukoski', 'name': 'Savukoski'},
 {'id': '743', 'nimi': 'Seinäjoki', 'namn': 'Seinäjoki', 'name': 'Seinäjoki'},
 {'id': '746', 'nimi': 'Sievi', 'namn': 'Sievi', 'name': 'Sievi'},
 {'id': '747', 'nimi': 'Siikainen', 'namn': 'Siikais', 'name': 'Siikainen'},
 {'id': '748', 'nimi': 'Siikajoki', 'namn': 'Siikajoki', 'name': 'Siikajoki'},
 {'id': '791',
  'nimi': 'Siikalatva',
  'namn': 'Siikalatva',
  'name': 'Siikalatva'},
 {'id': '749',
  'nimi': 'Siilinjärvi',
  'namn': 'Siilinjärvi',
  'name': 'Siilinjärvi'},
 {'id': '751', 'nimi': 'Simo', 'namn': 'Simo', 'name': 'Simo'},
 {'id': '753', 'nimi': 'Sipoo', 'namn': 'Sibbo', 'name': 'Sipoo'},
 {'id': '755', 'nimi': 'Siuntio', 'namn': 'Sjundeå', 'name': 'Siuntio'},
 {'id': '758', 'nimi': 'Sodankylä', 'namn': 'Sodankylä', 'name': 'Sodankylä'},
 {'id': '759', 'nimi': 'Soini', 'namn': 'Soini', 'name': 'Soini'},
 {'id': '761', 'nimi': 'Somero', 'namn': 'Somero', 'name': 'Somero'},
 {'id': '762',
  'nimi': 'Sonkajärvi',
  'namn': 'Sonkajärvi',
  'name': 'Sonkajärvi'},
 {'id': '765', 'nimi': 'Sotkamo', 'namn': 'Sotkamo', 'name': 'Sotkamo'},
 {'id': '766', 'nimi': 'Sottunga', 'namn': 'Sottunga', 'name': 'Sottunga'},
 {'id': '768', 'nimi': 'Sulkava', 'namn': 'Sulkava', 'name': 'Sulkava'},
 {'id': '771', 'nimi': 'Sund', 'namn': 'Sund', 'name': 'Sund'},
 {'id': '777',
  'nimi': 'Suomussalmi',
  'namn': 'Suomussalmi',
  'name': 'Suomussalmi'},
 {'id': '778',
  'nimi': 'Suonenjoki',
  'namn': 'Suonenjoki',
  'name': 'Suonenjoki'},
 {'id': '781', 'nimi': 'Sysmä', 'namn': 'Sysmä', 'name': 'Sysmä'},

In [55]:
timeseries_region = get_timeseries_data('Sub-region')
timeseries_region

       dimensions  Year   value
Region
SK011        M408  1987    94.4
SK011        M408  1988    94.2
SK011        M408  1989    94.3
SK011        M408  1990    95.4
SK011        M408  1991    95.5
...           ...   ...     ...
SK213        M498  2016  2442.7
SK213        M498  2017  2555.0
SK213        M498  2018  2592.4
SK213        M498  2019  2709.3
SK213        M498  2020  2931.8

[56925 rows x 3 columns]

In [ ]:
timeseries_region.index.map()

In [52]:
pd.DataFrame(reg_names.reset_index().to_dict('records')).set_index('id')

,nimi,namn,name
id,,,
SSS,KOKO MAA,HELA LANDET,WHOLE COUNTRY
020,Akaa,Ackas,Akaa
005,Alajärvi,Alajärvi,Alajärvi
009,Alavieska,Alavieska,Alavieska
010,Alavus,Alavo,Alavus
...,...,...,...
SK196,Tunturi-Lapin seutukunta,Tunturi-Lappi ekon. reg.,Tunturi-Lappi sub-regional unit
SK197,Pohjois-Lapin seutukunta,Norra Lapplands ekon. reg.,Pohjois-Lappi sub-regional unit
SK211,Mariehamns stad,Mariehamns stad,Mariehamns stad sub-regional unit
SK212,Ålands landsbygd,Ålands landsbygd,Ålands landsbygd sub-regional unit
SK213,Ålands skärgård,Ålands skärgård,Ålands skärgård sub-regional unit

In [94]:
get_timeseries_data('Region')

       dimensions  Year   value
Region
SSS          M408  1987    77.7
SSS          M408  1988    77.7
SSS          M408  1989    78.1
SSS          M408  1990    80.6
SSS          M408  1991    80.7
...           ...   ...     ...
MK21         M498  2016  1827.9
MK21         M498  2017  1747.5
MK21         M498  2018  1824.0
MK21         M498  2019  1905.9
MK21         M498  2020  1936.3

[16500 rows x 3 columns]

In [124]:
fig_df = pd.DataFrame([{'x':0, 'y':0, 'text':'Ladataan aikasarjaa...'}])
default_fig = px.scatter(fig_df, x='x',y='y',text='text', template = 'none')
default_fig.update_traces(mode='text',textfont_size=25)
default_fig.update_xaxes(showgrid=False, visible=False)
default_fig.update_yaxes(showgrid=False, visible=False)
default_fig

In [115]:
help(px.scatter)

Help on function scatter in module plotly.express._chart_types:

scatter(data_frame=None, x=None, y=None, color=None, symbol=None, size=None, hover_name=None, hover_data=None, custom_data=None, text=None, facet_row=None, facet_col=None, facet_col_wrap=0, facet_row_spacing=None, facet_col_spacing=None, error_x=None, error_x_minus=None, error_y=None, error_y_minus=None, animation_frame=None, animation_group=None, category_orders=None, labels=None, orientation=None, color_discrete_sequence=None, color_discrete_map=None, color_continuous_scale=None, range_color=None, color_continuous_midpoint=None, symbol_sequence=None, symbol_map=None, opacity=None, size_max=None, marginal_x=None, marginal_y=None, trendline=None, trendline_options=None, trendline_color_override=None, trendline_scope='trace', log_x=False, log_y=False, range_x=None, range_y=None, render_mode='auto', title=None, template=None, width=None, height=None) -> plotly.graph_objs._figure.Figure
        In a scatter plot, each row of `data_frame` is represented by a symbol
        mark in 2D space.

    Parameters
    ----------
    data_frame: DataFrame or array-like or dict
        This argument needs to be passed for column names (and not keyword
        names) to be used. Array-like and dict are tranformed internally to a
        pandas DataFrame. Optional: if missing, a DataFrame gets constructed
        under the hood using the other arguments.
    x: str or int or Series or array-like
        Either a name of a column in `data_frame`, or a pandas Series or
        array_like object. Values from this column or array_like are used to
        position marks along the x axis in cartesian coordinates. Either `x` or
        `y` can optionally be a list of column references or array_likes,  in
        which case the data will be treated as if it were 'wide' rather than
        'long'.
    y: str or int or Series or array-like
        Either a name of a column in `data_frame`, or a pandas Series or
        array_like object. Values from this column or array_like are used to
        position marks along the y axis in cartesian coordinates. Either `x` or
        `y` can optionally be a list of column references or array_likes,  in
        which case the data will be treated as if it were 'wide' rather than
        'long'.
    color: str or int or Series or array-like
        Either a name of a column in `data_frame`, or a pandas Series or
        array_like object. Values from this column or array_like are used to
        assign color to marks.
    symbol: str or int or Series or array-like
        Either a name of a column in `data_frame`, or a pandas Series or
        array_like object. Values from this column or array_like are used to
        assign symbols to marks.
    size: str or int or Series or array-like
        Either a name of a column in `data_frame`, or a pandas Series or
        array_like object. Values from this column or array_like are used to
        assign mark sizes.
    hover_name: str or int or Series or array-like
        Either a name of a column in `data_frame`, or a pandas Series or
        array_like object. Values from this column or array_like appear in bold
        in the hover tooltip.
    hover_data: list of str or int, or Series or array-like, or dict
        Either a list of names of columns in `data_frame`, or pandas Series, or
        array_like objects or a dict with column names as keys, with values
        True (for default formatting) False (in order to remove this column
        from hover information), or a formatting string, for example ':.3f' or
        '|%a' or list-like data to appear in the hover tooltip or tuples with a
        bool or formatting string as first element, and list-like data to
        appear in hover as second element Values from these columns appear as
        extra data in the hover tooltip.
    custom_data: list of str or int, or Series or array-like
        Either names of columns in `data_frame`, or pandas Series, or
        array_like objects Values from these columns are extra data, to be used
        in widgets or Dash callbacks for example. This data is not user-visible
        but is included in events emitted by the figure (lasso selection etc.)
    text: str or int or Series or array-like
        Either a name of a column in `data_frame`, or a pandas Series or
        array_like object. Values from this column or array_like appear in the
        figure as text labels.
    facet_row: str or int or Series or array-like
        Either a name of a column in `data_frame`, or a pandas Series or
        array_like object. Values from this column or array_like are used to
        assign marks to facetted subplots in the vertical direction.
    facet_col: str or int or Series or array-like
        Either a name of a column in `data_frame`, or a pandas Series or
        array_like object. Values from this column or array_like are used to
        assign marks to facetted subplots in the horizontal direction.
    facet_col_wrap: int
        Maximum number of facet columns. Wraps the column variable at this
        width, so that the column facets span multiple rows. Ignored if 0, and
        forced to 0 if `facet_row` or a `marginal` is set.
    facet_row_spacing: float between 0 and 1
        Spacing between facet rows, in paper units. Default is 0.03 or 0.0.7
        when facet_col_wrap is used.
    facet_col_spacing: float between 0 and 1
        Spacing between facet columns, in paper units Default is 0.02.
    error_x: str or int or Series or array-like
        Either a name of a column in `data_frame`, or a pandas Series or
        array_like object. Values from this column or array_like are used to
        size x-axis error bars. If `error_x_minus` is `None`, error bars will
        be symmetrical, otherwise `error_x` is used for the positive direction
        only.
    error_x_minus: str or int or Series or array-like
        Either a name of a column in `data_frame`, or a pandas Series or
        array_like object. Values from this column or array_like are used to
        size x-axis error bars in the negative direction. Ignored if `error_x`
        is `None`.
    error_y: str or int or Series or array-like
        Either a name of a column in `data_frame`, or a pandas Series or
        array_like object. Values from this column or array_like are used to
        size y-axis error bars. If `error_y_minus` is `None`, error bars will
        be symmetrical, otherwise `error_y` is used for the positive direction
        only.
    error_y_minus: str or int or Series or array-like
        Either a name of a column in `data_frame`, or a pandas Series or
        array_like object. Values from this column or array_like are used to
        size y-axis error bars in the negative direction. Ignored if `error_y`
        is `None`.
    animation_frame: str or int or Series or array-like
        Either a name of a column in `data_frame`, or a pandas Series or
        array_like object. Values from this column or array_like are used to
        assign marks to animation frames.
    animation_group: str or int or Series or array-like
        Either a name of a column in `data_frame`, or a pandas Series or
        array_like object. Values from this column or array_like are used to
        provide object-constancy across animation frames: rows with matching
        `animation_group`s will be treated as if they describe the same object
        in each frame.
    category_orders: dict with str keys and list of str values (default `{}`)
        By default, in Python 3.6+, the order of categorical values in axes,
        legends and facets depends on the order in which these values are first
        encountered in `data_frame` (and no order is guaranteed by default in
        Python below 3.6). This parameter is used to force a specific ordering
        of values per column. The keys of this dict should correspond to column
        names, and the values should be lists of strings corresponding to the
        specific display order desired.
    labels: dict with str keys and str values (default `{}`)
        By default, column names are used in the figure for axis titles, legend
        entries and hovers. This parameter allows this to be overridden. The
        keys of this dict should correspond to column names, and the values
        should correspond to the desired label to be displayed.
    orientation: str, one of `'h'` for horizontal or `'v'` for vertical.
        (default `'v'` if `x` and `y` are provided and both continous or both
        categorical,  otherwise `'v'`(`'h'`) if `x`(`y`) is categorical and
        `y`(`x`) is continuous,  otherwise `'v'`(`'h'`) if only `x`(`y`) is
        provided)
    color_discrete_sequence: list of str
        Strings should define valid CSS-colors. When `color` is set and the
        values in the corresponding column are not numeric, values in that
        column are assigned colors by cycling through `color_discrete_sequence`
        in the order described in `category_orders`, unless the value of
        `color` is a key in `color_discrete_map`. Various useful color
        sequences are available in the `plotly.express.colors` submodules,
        specifically `plotly.express.colors.qualitative`.
    color_discrete_map: dict with str keys and str values (default `{}`)
        String values should define valid CSS-colors Used to override
        `color_discrete_sequence` to assign a specific colors to marks
        corresponding with specific values. Keys in `color_discrete_map` should
        be values in the column denoted by `color`. Alternatively, if the
        values of `color` are valid colors, the string `'identity'` may be
        passed to cause them to be used directly.
    color_continuous_scale: list of str
        Strings should define valid CSS-colors This list is used to build a
        continuous color scale when the column denoted by `color` contains
        numeric data. Various useful color scales are available in the
        `plotly.express.colors` submodules, specifically
        `plotly.express.colors.sequential`, `plotly.express.colors.diverging`
        and `plotly.express.colors.cyclical`.
    range_color: list of two numbers
        If provided, overrides auto-scaling on the continuous color scale.
    color_continuous_midpoint: number (default `None`)
        If set, computes the bounds of the continuous color scale to have the
        desired midpoint. Setting this value is recommended when using
        `plotly.express.colors.diverging` color scales as the inputs to
        `color_continuous_scale`.
    symbol_sequence: list of str
        Strings should define valid plotly.js symbols. When `symbol` is set,
        values in that column are assigned symbols by cycling through
        `symbol_sequence` in the order described in `category_orders`, unless
        the value of `symbol` is a key in `symbol_map`.
    symbol_map: dict with str keys and str values (default `{}`)
        String values should define plotly.js symbols Used to override
        `symbol_sequence` to assign a specific symbols to marks corresponding
        with specific values. Keys in `symbol_map` should be values in the
        column denoted by `symbol`. Alternatively, if the values of `symbol`
        are valid symbol names, the string `'identity'` may be passed to cause
        them to be used directly.
    opacity: float
        Value between 0 and 1. Sets the opacity for markers.
    size_max: int (default `20`)
        Set the maximum mark size when using `size`.
    marginal_x: str
        One of `'rug'`, `'box'`, `'violin'`, or `'histogram'`. If set, a
        horizontal subplot is drawn above the main plot, visualizing the
        x-distribution.
    marginal_y: str
        One of `'rug'`, `'box'`, `'violin'`, or `'histogram'`. If set, a
        vertical subplot is drawn to the right of the main plot, visualizing
        the y-distribution.
    trendline: str
        One of `'ols'`, `'lowess'`, `'rolling'`, `'expanding'` or `'ewm'`. If
        `'ols'`, an Ordinary Least Squares regression line will be drawn for
        each discrete-color/symbol group. If `'lowess`', a Locally Weighted
        Scatterplot Smoothing line will be drawn for each discrete-color/symbol
        group. If `'rolling`', a Rolling (e.g. rolling average, rolling median)
        line will be drawn for each discrete-color/symbol group. If
        `'expanding`', an Expanding (e.g. expanding average, expanding sum)
        line will be drawn for each discrete-color/symbol group. If `'ewm`', an
        Exponentially Weighted Moment (e.g. exponentially-weighted moving
        average) line will be drawn for each discrete-color/symbol group. See
        the docstrings for the functions in
        `plotly.express.trendline_functions` for more details on these
        functions and how to configure them with the `trendline_options`
        argument.
    trendline_options: dict
        Options passed as the first argument to the function from
        `plotly.express.trendline_functions`  named in the `trendline`
        argument.
    trendline_color_override: str
        Valid CSS color. If provided, and if `trendline` is set, all trendlines
        will be drawn in this color rather than in the same color as the traces
        from which they draw their inputs.
    trendline_scope: str (one of `'trace'` or `'overall'`, default `'trace'`)
        If `'trace'`, then one trendline is drawn per trace (i.e. per color,
        symbol, facet, animation frame etc) and if `'overall'` then one
        trendline is computed for the entire dataset, and replicated across all
        facets.
    log_x: boolean (default `False`)
        If `True`, the x-axis is log-scaled in cartesian coordinates.
    log_y: boolean (default `False`)
        If `True`, the y-axis is log-scaled in cartesian coordinates.
    range_x: list of two numbers
        If provided, overrides auto-scaling on the x-axis in cartesian
        coordinates.
    range_y: list of two numbers
        If provided, overrides auto-scaling on the y-axis in cartesian
        coordinates.
    render_mode: str
        One of `'auto'`, `'svg'` or `'webgl'`, default `'auto'` Controls the
        browser API used to draw marks. `'svg`' is appropriate for figures of
        less than 1000 data points, and will allow for fully-vectorized output.
        `'webgl'` is likely necessary for acceptable performance above 1000
        points but rasterizes part of the output.  `'auto'` uses heuristics to
        choose the mode.
    title: str
        The figure title.
    template: str or dict or plotly.graph_objects.layout.Template instance
        The figure template name (must be a key in plotly.io.templates) or
        definition.
    width: int (default `None`)
        The figure width in pixels.
    height: int (default `None`)
        The figure height in pixels.

    Returns
    -------
        plotly.graph_objects.Figure

In [128]:
import os

In [129]:
print(os.environ.get('KEY_THAT_MIGHT_EXIST'))

None

In [134]:
with open("token.txt", "x") as f:
    f.write('pk.eyJ1IjoiZ3VkdW1hbyIsImEiOiJjanNrZzA5aWoyazU3NDN0Yjl6Y25zend6In0.zkMKSjHPzqG5mQCX-yWdMw')

OSError: [Errno 22] Invalid argument: 'token.txt'

In [1]:
open(".mapbox_token").read()

'pk.eyJ1IjoiZ3VkdW1hbyIsImEiOiJjanNrZzA5aWoyazU3NDN0Yjl6Y25zend6In0.zkMKSjHPzqG5mQCX-yWdMw'

In [136]:
f = open("mapbox_token.txt")

OSError: [Errno 22] Invalid argument: 'mapbox_token.txt'

In [6]:
import requests
vanha_ennuste_url = 'https://statfin.stat.fi:443/PxWeb/api/v1/fi/StatFin_Passiivi/vaenn/statfinpas_vaenn_pxt_128v_2040.px'
vanha_tk_ennustevuodet = [int(c) for c  in requests.get(vanha_ennuste_url).json()['variables'][1]['valueTexts']]

In [7]:
vanha_tk_ennustevuodet

[2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 2025,
 2026,
 2027,
 2028,
 2029,
 2030,
 2031,
 2032,
 2033,
 2034,
 2035,
 2036,
 2037,
 2038,
 2039,
 2040]

In [9]:
def get_old_tk_forecast(city_code):
    
    # ennuste_url = 'https://statfin.stat.fi:443/PxWeb/api/v1/fi/StatFin_Passiivi/vrm/vaenn/statfinpas_vaenn_pxt_128v_2040.px'
    
    headers =  {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36',
                                'Content-Type':'application/json'
                               }
    
    
    ennuste_query = {
                          "query": [
                            {
                              "code": "Alue",
                              "selection": {
                                "filter": "item",
                                "values": [
                                    city_code
                                ]
                              }
                            },
                            {
                              "code": "Ikä",
                              "selection": {
                                "filter": "item",
                                "values": [
                                  "000",
                                  "001",
                                  "002",
                                  "003",
                                  "004",
                                  "005",
                                  "006",
                                  "007",
                                  "008",
                                  "009",
                                  "010",
                                  "011",
                                  "012",
                                  "013",
                                  "014",
                                  "015",
                                  "016",
                                  "017",
                                  "018",
                                  "019",
                                  "020",
                                  "021",
                                  "022",
                                  "023",
                                  "024",
                                  "025",
                                  "026",
                                  "027",
                                  "028",
                                  "029",
                                  "030",
                                  "031",
                                  "032",
                                  "033",
                                  "034",
                                  "035",
                                  "036",
                                  "037",
                                  "038",
                                  "039",
                                  "040",
                                  "041",
                                  "042",
                                  "043",
                                  "044",
                                  "045",
                                  "046",
                                  "047",
                                  "048",
                                  "049",
                                  "050",
                                  "051",
                                  "052",
                                  "053",
                                  "054",
                                  "055",
                                  "056",
                                  "057",
                                  "058",
                                  "059",
                                  "060",
                                  "061",
                                  "062",
                                  "063",
                                  "064",
                                  "065",
                                  "066",
                                  "067",
                                  "068",
                                  "069",
                                  "070",
                                  "071",
                                  "072",
                                  "073",
                                  "074",
                                  "075",
                                  "076",
                                  "077",
                                  "078",
                                  "079",
                                  "080",
                                  "081",
                                  "082",
                                  "083",
                                  "084",
                                  "085",
                                  "086",
                                  "087",
                                  "088",
                                  "089",
                                  "090",
                                  "091",
                                  "092",
                                  "093",
                                  "094",
                                  "095",
                                  "096",
                                  "097",
                                  "098",
                                  "099",
                                  "100-"
                                ]
                              }
                            }
                          ],
                          "response": {
                            "format": "json-stat2"
                          }
                        }
    

    
    ennuste_json = requests.post(ennuste_url,json=ennuste_query,headers=headers)
    tk_data = ennuste_json.json()
    
    tk_year_df = pd.DataFrame()
    tk_age_df = pd.DataFrame()
    tk_year_df['Vuosi'] = [int(c) for c in tk_data['dimension']['Vuosi']['category']['label'].values()]
    tk_year_df['index'] = 0
    tk_age_df['Ikä'] = [int(c) for c in tk_data['dimension']['Ikä']['category']['index'].values()]
    tk_age_df['index'] = 0
    tk_data_df = pd.merge(left=tk_age_df,right=tk_year_df,how='outer',on='index').drop_duplicates().sort_values(by=['Vuosi','Ikä'])[['Vuosi','Ikä']].rename(columns={'ikä':'Ikä'})
    tk_data_df['Tilastokeskuksen ennuste']  = tk_data['value']
    tk_data_df = tk_data_df.set_index('Vuosi')
    tk_data_df['Kaupunki'] = list(tk_data['dimension']['Alue']['category']['label'].values())[0].capitalize()
    tk_data_df = tk_data_df[['Kaupunki','Ikä','Tilastokeskuksen ennuste']]
    
    return tk_data_df

In [ ]:
get_old_tk_forecast